/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Alert, Validation } from "../packages/core/utils/helpers/types";
export { Alert, Validation } from "../packages/core/utils/helpers/types";
export namespace Components {
    interface EuiAutoComplete {
        "displayField"?: string;
        "fetchSuggestions"?: (query: string) => Promise<any[]>;
        /**
          * @default ''
         */
        "placeholder": string;
    }
    interface EuiBadge {
        /**
          * @default 'primary'
         */
        "color": 'primary' | 'success' | 'warning' | 'danger' | 'outline' | 'outline-filled' | 'pending';
        "styleValue"?: string;
        /**
          * @default 'blank'
         */
        "type": 'blank' | 'icon' | 'number' | 'text-icon' | 'text';
    }
    interface EuiButton {
        /**
          * @default "normal"
         */
        "mode": "normal" | "outline" | "text-button";
        /**
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'danger' | 'success' | 'warning';
    }
    interface EuiDropdown {
        /**
          * @default []
         */
        "data": any[];
        "displayField"?: string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default []
         */
        "suggestions": any[];
    }
    interface EuiIcon {
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 'micro'
         */
        "type": 'solid' | 'outline' | 'mini' | 'micro';
    }
    interface EuiInput {
        /**
          * @default { message: "There's an error!", type: "danger" }
         */
        "alert": Alert;
        "max"?: number;
        "min"?: number;
        /**
          * @default 'normal'
         */
        "mode": 'normal' | 'outline' | 'text-input';
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default 1
         */
        "step": number;
        /**
          * @default ''
         */
        "styleValue"?: string;
        /**
          * @default 'text'
         */
        "type": HTMLInputElement['type'];
        "validation"?: Validation;
        /**
          * External value prop (mutable so it can be updated from parent)
          * @default ''
         */
        "value": string;
    }
}
export interface EuiAutoCompleteCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiAutoCompleteElement;
}
export interface EuiDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiDropdownElement;
}
export interface EuiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiInputElement;
}
declare global {
    interface HTMLEuiAutoCompleteElementEventMap {
        "itemSelected": any;
    }
    interface HTMLEuiAutoCompleteElement extends Components.EuiAutoComplete, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiAutoCompleteElementEventMap>(type: K, listener: (this: HTMLEuiAutoCompleteElement, ev: EuiAutoCompleteCustomEvent<HTMLEuiAutoCompleteElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiAutoCompleteElementEventMap>(type: K, listener: (this: HTMLEuiAutoCompleteElement, ev: EuiAutoCompleteCustomEvent<HTMLEuiAutoCompleteElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiAutoCompleteElement: {
        prototype: HTMLEuiAutoCompleteElement;
        new (): HTMLEuiAutoCompleteElement;
    };
    interface HTMLEuiBadgeElement extends Components.EuiBadge, HTMLStencilElement {
    }
    var HTMLEuiBadgeElement: {
        prototype: HTMLEuiBadgeElement;
        new (): HTMLEuiBadgeElement;
    };
    interface HTMLEuiButtonElement extends Components.EuiButton, HTMLStencilElement {
    }
    var HTMLEuiButtonElement: {
        prototype: HTMLEuiButtonElement;
        new (): HTMLEuiButtonElement;
    };
    interface HTMLEuiDropdownElementEventMap {
        "itemSelected": any;
    }
    interface HTMLEuiDropdownElement extends Components.EuiDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiDropdownElementEventMap>(type: K, listener: (this: HTMLEuiDropdownElement, ev: EuiDropdownCustomEvent<HTMLEuiDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiDropdownElementEventMap>(type: K, listener: (this: HTMLEuiDropdownElement, ev: EuiDropdownCustomEvent<HTMLEuiDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiDropdownElement: {
        prototype: HTMLEuiDropdownElement;
        new (): HTMLEuiDropdownElement;
    };
    interface HTMLEuiIconElement extends Components.EuiIcon, HTMLStencilElement {
    }
    var HTMLEuiIconElement: {
        prototype: HTMLEuiIconElement;
        new (): HTMLEuiIconElement;
    };
    interface HTMLEuiInputElementEventMap {
        "clear": any;
    }
    interface HTMLEuiInputElement extends Components.EuiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiInputElementEventMap>(type: K, listener: (this: HTMLEuiInputElement, ev: EuiInputCustomEvent<HTMLEuiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiInputElementEventMap>(type: K, listener: (this: HTMLEuiInputElement, ev: EuiInputCustomEvent<HTMLEuiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiInputElement: {
        prototype: HTMLEuiInputElement;
        new (): HTMLEuiInputElement;
    };
    interface HTMLElementTagNameMap {
        "eui-auto-complete": HTMLEuiAutoCompleteElement;
        "eui-badge": HTMLEuiBadgeElement;
        "eui-button": HTMLEuiButtonElement;
        "eui-dropdown": HTMLEuiDropdownElement;
        "eui-icon": HTMLEuiIconElement;
        "eui-input": HTMLEuiInputElement;
    }
}
declare namespace LocalJSX {
    interface EuiAutoComplete {
        "displayField"?: string;
        "fetchSuggestions"?: (query: string) => Promise<any[]>;
        "onItemSelected"?: (event: EuiAutoCompleteCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
    }
    interface EuiBadge {
        /**
          * @default 'primary'
         */
        "color"?: 'primary' | 'success' | 'warning' | 'danger' | 'outline' | 'outline-filled' | 'pending';
        "styleValue"?: string;
        /**
          * @default 'blank'
         */
        "type"?: 'blank' | 'icon' | 'number' | 'text-icon' | 'text';
    }
    interface EuiButton {
        /**
          * @default "normal"
         */
        "mode"?: "normal" | "outline" | "text-button";
        /**
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'danger' | 'success' | 'warning';
    }
    interface EuiDropdown {
        /**
          * @default []
         */
        "data"?: any[];
        "displayField"?: string;
        "onItemSelected"?: (event: EuiDropdownCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default []
         */
        "suggestions"?: any[];
    }
    interface EuiIcon {
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default 'micro'
         */
        "type"?: 'solid' | 'outline' | 'mini' | 'micro';
    }
    interface EuiInput {
        /**
          * @default { message: "There's an error!", type: "danger" }
         */
        "alert"?: Alert;
        "max"?: number;
        "min"?: number;
        /**
          * @default 'normal'
         */
        "mode"?: 'normal' | 'outline' | 'text-input';
        "onClear"?: (event: EuiInputCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default 1
         */
        "step"?: number;
        /**
          * @default ''
         */
        "styleValue"?: string;
        /**
          * @default 'text'
         */
        "type"?: HTMLInputElement['type'];
        "validation"?: Validation;
        /**
          * External value prop (mutable so it can be updated from parent)
          * @default ''
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "eui-auto-complete": EuiAutoComplete;
        "eui-badge": EuiBadge;
        "eui-button": EuiButton;
        "eui-dropdown": EuiDropdown;
        "eui-icon": EuiIcon;
        "eui-input": EuiInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eui-auto-complete": LocalJSX.EuiAutoComplete & JSXBase.HTMLAttributes<HTMLEuiAutoCompleteElement>;
            "eui-badge": LocalJSX.EuiBadge & JSXBase.HTMLAttributes<HTMLEuiBadgeElement>;
            "eui-button": LocalJSX.EuiButton & JSXBase.HTMLAttributes<HTMLEuiButtonElement>;
            "eui-dropdown": LocalJSX.EuiDropdown & JSXBase.HTMLAttributes<HTMLEuiDropdownElement>;
            "eui-icon": LocalJSX.EuiIcon & JSXBase.HTMLAttributes<HTMLEuiIconElement>;
            "eui-input": LocalJSX.EuiInput & JSXBase.HTMLAttributes<HTMLEuiInputElement>;
        }
    }
}
