/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Alert, Validation } from "../packages/core/utils/helpers/types";
export { Alert, Validation } from "../packages/core/utils/helpers/types";
export namespace Components {
    interface EuiAutoComplete {
        "displayField"?: string;
        "fetchSuggestions"?: (query: string) => Promise<any[]>;
        /**
          * @default ''
         */
        "placeholder": string;
        "styleValue"?: string;
    }
    interface EuiBadge {
        /**
          * @default 'primary'
         */
        "color": 'primary' | 'success' | 'warning' | 'danger' | 'outline' | 'outline-filled' | 'pending';
        "styleValue"?: string;
        /**
          * @default 'blank'
         */
        "type": 'blank' | 'icon' | 'number' | 'text-icon' | 'text';
    }
    interface EuiButton {
        /**
          * @default "normal"
         */
        "mode": "normal" | "outline" | "text-button";
        /**
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'danger' | 'success' | 'warning' | 'neutral' | 'info';
    }
    interface EuiCard {
        /**
          * @default ""
         */
        "img": string;
        /**
          * @default 'classic'
         */
        "mode": "classic" | "belt" | "lollipop" | "gem" | "Flag";
        /**
          * @default "vertical"
         */
        "orientation": "horizontal" | "vertical";
        "styleValue"?: string;
    }
    interface EuiCheckbox {
        /**
          * @default "fill"
         */
        "mode": "fill" | "outline";
        /**
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
        /**
          * @default ['null', 'false', 'partial', 'true']
         */
        "states": Array<'null' | 'false' | 'partial' | 'true'>;
        "styleValue"?: string;
        /**
          * @default 'null'
         */
        "value": 'null' | 'false' | 'partial' | 'true';
    }
    interface EuiChips {
        /**
          * @default []
         */
        "data": any[];
        "displayField"?: string;
        /**
          * @default ''
         */
        "placeholder": string;
        "styleValue"?: string;
        /**
          * @default []
         */
        "suggestions": any[];
    }
    interface EuiDialogue {
        /**
          * @default "MESSAGE!"
         */
        "headerMessage": string;
        "styleValue"?: string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'danger' | 'success' | 'warning' | 'info';
    }
    interface EuiDropdown {
        /**
          * @default []
         */
        "data": any[];
        "displayField"?: string;
        /**
          * @default ''
         */
        "placeholder": string;
        "styleValue"?: string;
        /**
          * @default []
         */
        "suggestions": any[];
    }
    interface EuiIcon {
        /**
          * @default ''
         */
        "name": string;
        "styleValue"?: string;
        /**
          * @default 'micro'
         */
        "type": 'solid' | 'outline' | 'mini' | 'micro';
    }
    interface EuiInput {
        /**
          * @default { message: "There's an error!", type: "danger" }
         */
        "alert": Alert;
        "max"?: number;
        "min"?: number;
        /**
          * @default 'normal'
         */
        "mode": 'normal' | 'outline' | 'text-input';
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default true
         */
        "showClear"?: boolean;
        /**
          * @default 1
         */
        "step": number;
        "styleValue"?: string;
        /**
          * @default 'text'
         */
        "type": HTMLInputElement['type'];
        "validation"?: Validation;
        /**
          * External value prop (mutable so it can be updated from parent)
          * @default ''
         */
        "value": string;
    }
    interface EuiPaginator {
        /**
          * @default 1
         */
        "defaultCurrentPage": number;
        /**
          * @default false
         */
        "disabled": boolean;
        "styleValue"?: string;
        /**
          * @default 1
         */
        "totalPages": number;
    }
    interface EuiProgressbar {
        /**
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 0
         */
        "value": number;
    }
    interface EuiSideNav {
        /**
          * @default "ltr"
         */
        "direction": "rtl" | "ltr";
        /**
          * @default "middle"
         */
        "mode": "middle" | "start";
        /**
          * @default "full"
         */
        "size": "full" | "compact";
        "styleValue"?: string;
    }
    interface EuiSlider {
        /**
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 0
         */
        "value": number;
    }
}
export interface EuiAutoCompleteCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiAutoCompleteElement;
}
export interface EuiCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiCheckboxElement;
}
export interface EuiChipsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiChipsElement;
}
export interface EuiDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiDropdownElement;
}
export interface EuiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiInputElement;
}
export interface EuiPaginatorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiPaginatorElement;
}
export interface EuiSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiSliderElement;
}
declare global {
    interface HTMLEuiAutoCompleteElementEventMap {
        "itemSelected": any;
    }
    interface HTMLEuiAutoCompleteElement extends Components.EuiAutoComplete, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiAutoCompleteElementEventMap>(type: K, listener: (this: HTMLEuiAutoCompleteElement, ev: EuiAutoCompleteCustomEvent<HTMLEuiAutoCompleteElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiAutoCompleteElementEventMap>(type: K, listener: (this: HTMLEuiAutoCompleteElement, ev: EuiAutoCompleteCustomEvent<HTMLEuiAutoCompleteElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiAutoCompleteElement: {
        prototype: HTMLEuiAutoCompleteElement;
        new (): HTMLEuiAutoCompleteElement;
    };
    interface HTMLEuiBadgeElement extends Components.EuiBadge, HTMLStencilElement {
    }
    var HTMLEuiBadgeElement: {
        prototype: HTMLEuiBadgeElement;
        new (): HTMLEuiBadgeElement;
    };
    interface HTMLEuiButtonElement extends Components.EuiButton, HTMLStencilElement {
    }
    var HTMLEuiButtonElement: {
        prototype: HTMLEuiButtonElement;
        new (): HTMLEuiButtonElement;
    };
    interface HTMLEuiCardElement extends Components.EuiCard, HTMLStencilElement {
    }
    var HTMLEuiCardElement: {
        prototype: HTMLEuiCardElement;
        new (): HTMLEuiCardElement;
    };
    interface HTMLEuiCheckboxElementEventMap {
        "valueChange": 'null' | 'false' | 'partial' | 'true';
    }
    interface HTMLEuiCheckboxElement extends Components.EuiCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiCheckboxElementEventMap>(type: K, listener: (this: HTMLEuiCheckboxElement, ev: EuiCheckboxCustomEvent<HTMLEuiCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiCheckboxElementEventMap>(type: K, listener: (this: HTMLEuiCheckboxElement, ev: EuiCheckboxCustomEvent<HTMLEuiCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiCheckboxElement: {
        prototype: HTMLEuiCheckboxElement;
        new (): HTMLEuiCheckboxElement;
    };
    interface HTMLEuiChipsElementEventMap {
        "itemSelected": any;
    }
    interface HTMLEuiChipsElement extends Components.EuiChips, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiChipsElementEventMap>(type: K, listener: (this: HTMLEuiChipsElement, ev: EuiChipsCustomEvent<HTMLEuiChipsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiChipsElementEventMap>(type: K, listener: (this: HTMLEuiChipsElement, ev: EuiChipsCustomEvent<HTMLEuiChipsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiChipsElement: {
        prototype: HTMLEuiChipsElement;
        new (): HTMLEuiChipsElement;
    };
    interface HTMLEuiDialogueElement extends Components.EuiDialogue, HTMLStencilElement {
    }
    var HTMLEuiDialogueElement: {
        prototype: HTMLEuiDialogueElement;
        new (): HTMLEuiDialogueElement;
    };
    interface HTMLEuiDropdownElementEventMap {
        "itemSelected": any;
    }
    interface HTMLEuiDropdownElement extends Components.EuiDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiDropdownElementEventMap>(type: K, listener: (this: HTMLEuiDropdownElement, ev: EuiDropdownCustomEvent<HTMLEuiDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiDropdownElementEventMap>(type: K, listener: (this: HTMLEuiDropdownElement, ev: EuiDropdownCustomEvent<HTMLEuiDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiDropdownElement: {
        prototype: HTMLEuiDropdownElement;
        new (): HTMLEuiDropdownElement;
    };
    interface HTMLEuiIconElement extends Components.EuiIcon, HTMLStencilElement {
    }
    var HTMLEuiIconElement: {
        prototype: HTMLEuiIconElement;
        new (): HTMLEuiIconElement;
    };
    interface HTMLEuiInputElementEventMap {
        "clear": any;
    }
    interface HTMLEuiInputElement extends Components.EuiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiInputElementEventMap>(type: K, listener: (this: HTMLEuiInputElement, ev: EuiInputCustomEvent<HTMLEuiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiInputElementEventMap>(type: K, listener: (this: HTMLEuiInputElement, ev: EuiInputCustomEvent<HTMLEuiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiInputElement: {
        prototype: HTMLEuiInputElement;
        new (): HTMLEuiInputElement;
    };
    interface HTMLEuiPaginatorElementEventMap {
        "currentPage": any;
    }
    interface HTMLEuiPaginatorElement extends Components.EuiPaginator, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiPaginatorElementEventMap>(type: K, listener: (this: HTMLEuiPaginatorElement, ev: EuiPaginatorCustomEvent<HTMLEuiPaginatorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiPaginatorElementEventMap>(type: K, listener: (this: HTMLEuiPaginatorElement, ev: EuiPaginatorCustomEvent<HTMLEuiPaginatorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiPaginatorElement: {
        prototype: HTMLEuiPaginatorElement;
        new (): HTMLEuiPaginatorElement;
    };
    interface HTMLEuiProgressbarElement extends Components.EuiProgressbar, HTMLStencilElement {
    }
    var HTMLEuiProgressbarElement: {
        prototype: HTMLEuiProgressbarElement;
        new (): HTMLEuiProgressbarElement;
    };
    interface HTMLEuiSideNavElement extends Components.EuiSideNav, HTMLStencilElement {
    }
    var HTMLEuiSideNavElement: {
        prototype: HTMLEuiSideNavElement;
        new (): HTMLEuiSideNavElement;
    };
    interface HTMLEuiSliderElementEventMap {
        "valueChange": number;
    }
    interface HTMLEuiSliderElement extends Components.EuiSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEuiSliderElementEventMap>(type: K, listener: (this: HTMLEuiSliderElement, ev: EuiSliderCustomEvent<HTMLEuiSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEuiSliderElementEventMap>(type: K, listener: (this: HTMLEuiSliderElement, ev: EuiSliderCustomEvent<HTMLEuiSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEuiSliderElement: {
        prototype: HTMLEuiSliderElement;
        new (): HTMLEuiSliderElement;
    };
    interface HTMLElementTagNameMap {
        "eui-auto-complete": HTMLEuiAutoCompleteElement;
        "eui-badge": HTMLEuiBadgeElement;
        "eui-button": HTMLEuiButtonElement;
        "eui-card": HTMLEuiCardElement;
        "eui-checkbox": HTMLEuiCheckboxElement;
        "eui-chips": HTMLEuiChipsElement;
        "eui-dialogue": HTMLEuiDialogueElement;
        "eui-dropdown": HTMLEuiDropdownElement;
        "eui-icon": HTMLEuiIconElement;
        "eui-input": HTMLEuiInputElement;
        "eui-paginator": HTMLEuiPaginatorElement;
        "eui-progressbar": HTMLEuiProgressbarElement;
        "eui-side-nav": HTMLEuiSideNavElement;
        "eui-slider": HTMLEuiSliderElement;
    }
}
declare namespace LocalJSX {
    interface EuiAutoComplete {
        "displayField"?: string;
        "fetchSuggestions"?: (query: string) => Promise<any[]>;
        "onItemSelected"?: (event: EuiAutoCompleteCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        "styleValue"?: string;
    }
    interface EuiBadge {
        /**
          * @default 'primary'
         */
        "color"?: 'primary' | 'success' | 'warning' | 'danger' | 'outline' | 'outline-filled' | 'pending';
        "styleValue"?: string;
        /**
          * @default 'blank'
         */
        "type"?: 'blank' | 'icon' | 'number' | 'text-icon' | 'text';
    }
    interface EuiButton {
        /**
          * @default "normal"
         */
        "mode"?: "normal" | "outline" | "text-button";
        /**
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'danger' | 'success' | 'warning' | 'neutral' | 'info';
    }
    interface EuiCard {
        /**
          * @default ""
         */
        "img"?: string;
        /**
          * @default 'classic'
         */
        "mode"?: "classic" | "belt" | "lollipop" | "gem" | "Flag";
        /**
          * @default "vertical"
         */
        "orientation"?: "horizontal" | "vertical";
        "styleValue"?: string;
    }
    interface EuiCheckbox {
        /**
          * @default "fill"
         */
        "mode"?: "fill" | "outline";
        "onValueChange"?: (event: EuiCheckboxCustomEvent<'null' | 'false' | 'partial' | 'true'>) => void;
        /**
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
        /**
          * @default ['null', 'false', 'partial', 'true']
         */
        "states"?: Array<'null' | 'false' | 'partial' | 'true'>;
        "styleValue"?: string;
        /**
          * @default 'null'
         */
        "value"?: 'null' | 'false' | 'partial' | 'true';
    }
    interface EuiChips {
        /**
          * @default []
         */
        "data"?: any[];
        "displayField"?: string;
        "onItemSelected"?: (event: EuiChipsCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        "styleValue"?: string;
        /**
          * @default []
         */
        "suggestions"?: any[];
    }
    interface EuiDialogue {
        /**
          * @default "MESSAGE!"
         */
        "headerMessage"?: string;
        "styleValue"?: string;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'danger' | 'success' | 'warning' | 'info';
    }
    interface EuiDropdown {
        /**
          * @default []
         */
        "data"?: any[];
        "displayField"?: string;
        "onItemSelected"?: (event: EuiDropdownCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        "styleValue"?: string;
        /**
          * @default []
         */
        "suggestions"?: any[];
    }
    interface EuiIcon {
        /**
          * @default ''
         */
        "name"?: string;
        "styleValue"?: string;
        /**
          * @default 'micro'
         */
        "type"?: 'solid' | 'outline' | 'mini' | 'micro';
    }
    interface EuiInput {
        /**
          * @default { message: "There's an error!", type: "danger" }
         */
        "alert"?: Alert;
        "max"?: number;
        "min"?: number;
        /**
          * @default 'normal'
         */
        "mode"?: 'normal' | 'outline' | 'text-input';
        "onClear"?: (event: EuiInputCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default true
         */
        "showClear"?: boolean;
        /**
          * @default 1
         */
        "step"?: number;
        "styleValue"?: string;
        /**
          * @default 'text'
         */
        "type"?: HTMLInputElement['type'];
        "validation"?: Validation;
        /**
          * External value prop (mutable so it can be updated from parent)
          * @default ''
         */
        "value"?: string;
    }
    interface EuiPaginator {
        /**
          * @default 1
         */
        "defaultCurrentPage"?: number;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onCurrentPage"?: (event: EuiPaginatorCustomEvent<any>) => void;
        "styleValue"?: string;
        /**
          * @default 1
         */
        "totalPages"?: number;
    }
    interface EuiProgressbar {
        /**
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 0
         */
        "value"?: number;
    }
    interface EuiSideNav {
        /**
          * @default "ltr"
         */
        "direction"?: "rtl" | "ltr";
        /**
          * @default "middle"
         */
        "mode"?: "middle" | "start";
        /**
          * @default "full"
         */
        "size"?: "full" | "compact";
        "styleValue"?: string;
    }
    interface EuiSlider {
        "onValueChange"?: (event: EuiSliderCustomEvent<number>) => void;
        /**
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
        "styleValue"?: string;
        /**
          * @default 0
         */
        "value"?: number;
    }
    interface IntrinsicElements {
        "eui-auto-complete": EuiAutoComplete;
        "eui-badge": EuiBadge;
        "eui-button": EuiButton;
        "eui-card": EuiCard;
        "eui-checkbox": EuiCheckbox;
        "eui-chips": EuiChips;
        "eui-dialogue": EuiDialogue;
        "eui-dropdown": EuiDropdown;
        "eui-icon": EuiIcon;
        "eui-input": EuiInput;
        "eui-paginator": EuiPaginator;
        "eui-progressbar": EuiProgressbar;
        "eui-side-nav": EuiSideNav;
        "eui-slider": EuiSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eui-auto-complete": LocalJSX.EuiAutoComplete & JSXBase.HTMLAttributes<HTMLEuiAutoCompleteElement>;
            "eui-badge": LocalJSX.EuiBadge & JSXBase.HTMLAttributes<HTMLEuiBadgeElement>;
            "eui-button": LocalJSX.EuiButton & JSXBase.HTMLAttributes<HTMLEuiButtonElement>;
            "eui-card": LocalJSX.EuiCard & JSXBase.HTMLAttributes<HTMLEuiCardElement>;
            "eui-checkbox": LocalJSX.EuiCheckbox & JSXBase.HTMLAttributes<HTMLEuiCheckboxElement>;
            "eui-chips": LocalJSX.EuiChips & JSXBase.HTMLAttributes<HTMLEuiChipsElement>;
            "eui-dialogue": LocalJSX.EuiDialogue & JSXBase.HTMLAttributes<HTMLEuiDialogueElement>;
            "eui-dropdown": LocalJSX.EuiDropdown & JSXBase.HTMLAttributes<HTMLEuiDropdownElement>;
            "eui-icon": LocalJSX.EuiIcon & JSXBase.HTMLAttributes<HTMLEuiIconElement>;
            "eui-input": LocalJSX.EuiInput & JSXBase.HTMLAttributes<HTMLEuiInputElement>;
            "eui-paginator": LocalJSX.EuiPaginator & JSXBase.HTMLAttributes<HTMLEuiPaginatorElement>;
            "eui-progressbar": LocalJSX.EuiProgressbar & JSXBase.HTMLAttributes<HTMLEuiProgressbarElement>;
            "eui-side-nav": LocalJSX.EuiSideNav & JSXBase.HTMLAttributes<HTMLEuiSideNavElement>;
            "eui-slider": LocalJSX.EuiSlider & JSXBase.HTMLAttributes<HTMLEuiSliderElement>;
        }
    }
}
