import { Holiday } from '../types'

export const fixedHolidays: Holiday[] = [
    { isHoliday: true, month: 0, day: 1, name: "New Year's Day" },
    { isHoliday: false, month: 0, day: 6, name: "Epiphany" },
    { isHoliday: false, month: 0, day: 25, name: "Australia Day" },
    { isHoliday: false, month: 1, day: 14, name: "Valentine's Day" },
    { isHoliday: true, month: 2, day: 8, name: "International Women's Day" },
    { isHoliday: false, month: 2, day: 17, name: "St. Patrick's Day" },
    { isHoliday: false, month: 2, day: 20, name: "International Happiness Day" },
    { isHoliday: false, month: 2, day: 21, name: "Nowruz - Persian New Year" },
    { isHoliday: false, month: 2, day: 23, name: "World Meteorology Day" },
    { isHoliday: false, month: 2, day: 27, name: "World Theatre Day" },
    { isHoliday: false, month: 3, day: 1, name: "April Fool's Day" },
    { isHoliday: false, month: 3, day: 7, name: "World Health Day" },
    { isHoliday: true, month: 3, day: 22, name: "Earth Day" },
    { isHoliday: false, month: 3, day: 27, name: "World Graphic Design Day" },
    { isHoliday: true, month: 4, day: 1, name: "International Workers' Day" },
    { isHoliday: false, month: 4, day: 5, name: "World Midwives Day" },
    { isHoliday: false, month: 4, day: 8, name: "Red Cross / Red Crescent Day" },
    { isHoliday: false, month: 4, day: 12, name: "International Nurses Day" },
    { isHoliday: false, month: 4, day: 18, name: "International Museum Day" },
    { isHoliday: false, month: 5, day: 5, name: "World Environment Day" },
    { isHoliday: false, month: 5, day: 10, name: "World Handicrafts Day" },
    { isHoliday: false, month: 5, day: 12, name: "World Day Against Child Labour" },
    { isHoliday: false, month: 5, day: 14, name: "World Blood Donor Day" },
    { isHoliday: false, month: 5, day: 16, name: "Father's Day" },
    { isHoliday: false, month: 5, day: 17, name: "World Day to Combat Desertification" },
    { isHoliday: false, month: 5, day: 26, name: "International Day Against Drug Abuse" },
    { isHoliday: true, month: 6, day: 4, name: "Independence Day (USA)" },
    { isHoliday: false, month: 6, day: 14, name: "Bastille Day (France)" },
    { isHoliday: false, month: 7, day: 1, name: "Canada Day" },
    { isHoliday: false, month: 7, day: 1, name: "World Breastfeeding Week starts" },
    { isHoliday: false, month: 7, day: 13, name: "International Left-Handers Day" },
    { isHoliday: false, month: 7, day: 19, name: "World Photography Day" },
    { isHoliday: false, month: 8, day: 10, name: "World Suicide Prevention Day" },
    { isHoliday: false, month: 8, day: 11, name: "9/11 Attacks Memorial" },
    { isHoliday: false, month: 8, day: 21, name: "International Day of Peace" },
    { isHoliday: false, month: 8, day: 27, name: "World Tourism Day" },
    { isHoliday: false, month: 8, day: 30, name: "International Day of the Deaf" },
    { isHoliday: false, month: 8, day: 30, name: "International Translation Day" },
    { isHoliday: false, month: 9, day: 1, name: "International Day of Older Persons" },
    { isHoliday: false, month: 9, day: 4, name: "World Space Week begins" },
    { isHoliday: false, month: 9, day: 5, name: "World Teachers' Day" },
    { isHoliday: false, month: 9, day: 9, name: "World Post Day" },
    { isHoliday: false, month: 9, day: 10, name: "World Day Against Death Penalty" },
    { isHoliday: false, month: 9, day: 11, name: "International Day of the Girl" },
    { isHoliday: false, month: 9, day: 14, name: "World Standards Day" },
    { isHoliday: false, month: 9, day: 15, name: "White Cane Safety Day" },
    { isHoliday: false, month: 9, day: 16, name: "World Food Day" },
    { isHoliday: false, month: 9, day: 17, name: "International Day for the Eradication of Poverty" },
    { isHoliday: false, month: 10, day: 14, name: "World Diabetes Day" },
    { isHoliday: false, month: 10, day: 17, name: "World Students' Day" },
    { isHoliday: false, month: 10, day: 19, name: "International Men's Day" },
    { isHoliday: false, month: 10, day: 20, name: "Universal Children's Day" },
    { isHoliday: true, month: 11, day: 25, name: "Christmas" },
    { isHoliday: false, month: 11, day: 25, name: "Friendship Day" },
    { isHoliday: true, month: 11, day: 31, name: "New Year's Eve" },
];


export const jalaliHolidays: Holiday[] = [
    { isHoliday: true, month: 0, day: 0, name: "جشن نوروز / جشن سال نو" },
    { isHoliday: true, month: 0, day: 1, name: "عید نوروز" },
    { isHoliday: true, month: 0, day: 2, name: "عید نوروز" },
    { isHoliday: true, month: 0, day: 3, name: "عید نوروز" },
    { isHoliday: false, month: 0, day: 5, name: "زادروز اَشو زرتشت" },
    { isHoliday: false, month: 0, day: 11, name: "روز جمهوری اسلامی" },
    { isHoliday: true, month: 0, day: 12, name: "جشن سیزده به در" },
    { isHoliday: false, month: 0, day: 22, name: "روز دندانپزشک" },
    { isHoliday: false, month: 0, day: 24, name: "روز بزرگداشت عطار نیشابوری" },
    { isHoliday: false, month: 0, day: 28, name: "روز ارتش جمهوری اسلامی ایران" },
    { isHoliday: false, month: 0, day: 29, name: "روز علوم آزمایشگاهی" },
    { isHoliday: false, month: 1, day: 0, name: "روز بزرگداشت سعدی" },
    { isHoliday: false, month: 1, day: 2, name: "روزبزرگداشت شیخ بهایی؛ روزملی کارآفرینی؛ روز معماری" },
    { isHoliday: false, month: 1, day: 5, name: "فاجعه‌ی انفجارِ بندر عباس [1404 خورشیدی]" },
    { isHoliday: false, month: 1, day: 8, name: "روز ملی روانشناس و مشاور" },
    { isHoliday: false, month: 1, day: 9, name: "جشن چهلم نوروز؛ روز ملی خلیج فارس" },
    { isHoliday: false, month: 1, day: 11, name: "روز معلم" },
    { isHoliday: false, month: 1, day: 14, name: "جشن میانه بهار/جشن بهاربد" },
    { isHoliday: false, month: 1, day: 21, name: "زادروز مریم میرزاخانی ریاضیدان ایرانی، روز جهانی زن در ریاضیات" },
    { isHoliday: false, month: 1, day: 24, name: "روز بزرگداشت فردوسی" },
    { isHoliday: false, month: 1, day: 26, name: "روز ارتباطات و روابط عمومی" },
    { isHoliday: false, month: 1, day: 27, name: "روز بزرگداشت حکیم عمر خیام" },
    { isHoliday: false, month: 2, day: 0, name: "روز بزرگداشت ملاصدرا" },
    { isHoliday: false, month: 2, day: 1, name: "فروریختن ساختمان متروپل در آبادان" },
    { isHoliday: false, month: 2, day: 5, name: "خرداد روز،جشن خردادگان" },
    { isHoliday: true, month: 2, day: 13, name: "رحلت آیت الله خمینی" },
    { isHoliday: true, month: 2, day: 14, name: "قیام 15 خرداد" },
    { isHoliday: false, month: 2, day: 24, name: "روز ملی گل وگیاه" },
    { isHoliday: false, month: 2, day: 30, name: "سالروز زلزله رودبار و منجیل" },
    { isHoliday: false, month: 3, day: 6, name: "روز قوه قضاییه" },
    { isHoliday: false, month: 3, day: 9, name: "روز صنعت و معدن" },
    { isHoliday: false, month: 3, day: 9, name: "زادروز بابک خرمدین" },
    { isHoliday: false, month: 3, day: 9, name: "روز بزرگداشت صائب تبریزی" },
    { isHoliday: false, month: 3, day: 12, name: "جشن تیرگان" },
    { isHoliday: false, month: 3, day: 13, name: "روز قلم" },
    { isHoliday: false, month: 3, day: 21, name: "زادروز محمد خوارزمی، ریاضیدان و فیلسوف ایرانی و روز ملی فناوری اطلاعات" },
    { isHoliday: false, month: 3, day: 25, name: "روز بهزیستی و تامین اجتماعی" },
    { isHoliday: false, month: 3, day: 27, name: "اعلام پذیرش قطعنامه 598 شورای امنیت از سوی ایران" },
    { isHoliday: false, month: 4, day: 6, name: "اَمرداد روز،جشن اَمردادگان" },
    { isHoliday: false, month: 4, day: 7, name: "روز بزرگداشت شیخ شهاب الدین سهروردی" },
    { isHoliday: false, month: 4, day: 9, name: "جشن چله تابستان" },
    { isHoliday: false, month: 4, day: 13, name: "سالروز صدور فرمان مشروطیت" },
    { isHoliday: false, month: 4, day: 16, name: "روز خبرنگار" },
    { isHoliday: false, month: 4, day: 27, name: "سالروز فاجعه آتش زدن سینما رکس آبادان" },
    { isHoliday: false, month: 5, day: 0, name: "روز بزرگداشت ابوعلی سینا و روز پزشک" },
    { isHoliday: false, month: 5, day: 1, name: "آغاز هفته دولت" },
    { isHoliday: false, month: 5, day: 3, name: "زادروز کوروش بزرگ" },
    { isHoliday: false, month: 5, day: 3, name: "شهریور روز،جشن شهریورگان" },
    { isHoliday: false, month: 5, day: 4, name: "روز بزرگداشت محمدبن زکریای رازی و روز داروساز" },
    { isHoliday: false, month: 5, day: 7, name: "روز ملی مبارزه با تروریسم" },
    { isHoliday: false, month: 5, day: 10, name: "روز ملی صنعت چاپ" },
    { isHoliday: false, month: 5, day: 11, name: "سالروز شهادت رئیسعلی دلواری" },
    { isHoliday: false, month: 5, day: 12, name: "روز بزرگداشت ابوریحان بیرونی" },
    { isHoliday: false, month: 5, day: 20, name: "روز سینما" },
    { isHoliday: false, month: 5, day: 26, name: "روز شعر و ادب پارسی و روز بزرگداشت استاد شهریار" },
    { isHoliday: false, month: 5, day: 30, name: "آغاز هفته دفاع مقدس" },
    { isHoliday: false, month: 6, day: 0, name: "آغاز حمله مغول به ایران در پاییز 598 خورشیدی" },
    { isHoliday: false, month: 6, day: 3, name: "روز گرامیداشت سربازان وطن" },
    { isHoliday: false, month: 6, day: 6, name: "روز آتش نشانی و ایمنی" },
    { isHoliday: false, month: 6, day: 6, name: "روز بزرگداشت شمس تبریزی" },
    { isHoliday: false, month: 6, day: 7, name: "روزبزرگداشت مولوی" },
    { isHoliday: false, month: 6, day: 9, name: "مهر روز،جشن مهرگان" },
    { isHoliday: false, month: 6, day: 13, name: "روز دامپزشکی" },
    { isHoliday: false, month: 6, day: 15, name: "روز ملی کودک" },
    { isHoliday: false, month: 6, day: 19, name: "روز بزرگداشت حافظ" },
    { isHoliday: false, month: 6, day: 20, name: "روز پیروزی کاوه و فریدون بر ضحاک" },
    { isHoliday: false, month: 6, day: 25, name: "روز تربیت بدنی و ورزش" },
    { isHoliday: false, month: 6, day: 27, name: "زادروز ستارخان" },
    { isHoliday: false, month: 6, day: 28, name: "روز ملی کوهنورد" },
    { isHoliday: false, month: 7, day: 0, name: "روز آمار و برنامه ریزی" },
    { isHoliday: false, month: 7, day: 0, name: "روز بزرگداشت ابوالفضل بیهقی" },
    { isHoliday: false, month: 7, day: 6, name: "سالروز ورود کوروش بزرگ به بابل در سال 539 پیش از میلاد" },
    { isHoliday: false, month: 7, day: 7, name: "روز ملی محیط بان" },
    { isHoliday: false, month: 7, day: 9, name: "آبان روز، جشن آبانگان" },
    { isHoliday: false, month: 7, day: 13, name: "روز ملّی مازندران" },
    { isHoliday: false, month: 7, day: 14, name: "جشن میانه پاییز" },
    { isHoliday: false, month: 7, day: 17, name: "روز ملی کیفیت" },
    { isHoliday: false, month: 7, day: 23, name: "روز کتاب و کتابخوانی" },
    { isHoliday: false, month: 8, day: 0, name: "آذر جشن" },
    { isHoliday: false, month: 8, day: 6, name: "روز نیروی دریایی ارتش" },
    { isHoliday: false, month: 8, day: 8, name: "جشن آذرگان ،آذر روز" },
    { isHoliday: false, month: 8, day: 8, name: "صدور اسناد مالکیت بر جزایر سه‌گانه ایرانی" },
    { isHoliday: false, month: 8, day: 12, name: "روز صنعت بیمه" },
    { isHoliday: false, month: 8, day: 14, name: "روز حسابدار" },
    { isHoliday: false, month: 8, day: 20, name: "سالروز نجات آذربایجان" },
    { isHoliday: false, month: 8, day: 24, name: "روز پژوهش و فناوری" },
    { isHoliday: false, month: 8, day: 29, name: "جشن شب یلدا، شب چلّه" },
    { isHoliday: false, month: 9, day: 0, name: "روز میلاد خورشید؛ جشن خرم روز، نخستین جشن دیگان" },
    { isHoliday: false, month: 9, day: 4, name: "زمین لرزه ی بم" },
    { isHoliday: false, month: 9, day: 4, name: "سالروز شهادت اَشو زرتشت" },
    { isHoliday: false, month: 9, day: 7, name: "دی به آذر روز، دومین جشن دیگان" },
    { isHoliday: false, month: 9, day: 11, name: "روز حافظ" },
    { isHoliday: false, month: 9, day: 14, name: "دی به مهر روز، سومین جشن دیگان" },
    { isHoliday: false, month: 9, day: 17, name: "شلیک به پرواز 752 هواپیمایی اوکراین" },
    { isHoliday: false, month: 9, day: 19, name: "قتل امیرکبیر" },
    { isHoliday: false, month: 9, day: 22, name: "دی به دین روز، چهارمین جشن دیگان" },
    { isHoliday: false, month: 9, day: 29, name: "آتش‌سوزی و فروریختن ساختمان پلاسکو" },
    { isHoliday: false, month: 10, day: 0, name: "زادروز فردوسی" },
    { isHoliday: false, month: 10, day: 1, name: "بهمن روز، جشن بهمنگان" },
    { isHoliday: false, month: 10, day: 4, name: "جشن نوسره" },
    { isHoliday: false, month: 10, day: 5, name: "بزرگداشت صفی‌الدین اُرمَوی و روز موسیقی ایرانی" },
    { isHoliday: false, month: 10, day: 9, name: "جشن سده، گرامیداشتِ کشف آتش به دستِ هوشنگ شاه" },
    { isHoliday: false, month: 10, day: 11, name: "بازگشت آیت الله خمینی (ره) به ایران" },
    { isHoliday: false, month: 10, day: 14, name: "جشن میانه زمستان" },
    { isHoliday: false, month: 10, day: 18, name: "روز نیروی هوایی" },
    { isHoliday: true, month: 10, day: 21, name: "پیروزی انقلاب اسلامی" },
    { isHoliday: false, month: 10, day: 28, name: "جشن سپندارمذگان و روز عشق" },
    { isHoliday: false, month: 10, day: 28, name: "فاجعه انفجار قطار نیشابور" },
    { isHoliday: false, month: 11, day: 4, name: "روز بزرگداشت خواجه نصیر الدین طوسی و روز مهندس" },
    { isHoliday: false, month: 11, day: 6, name: "سالروز استقلال کانون وکلای دادگستری و روز وکیل مدافع" },
    { isHoliday: false, month: 11, day: 14, name: "روز درختکاری" },
    { isHoliday: false, month: 11, day: 24, name: "پایان سرایش شاهنامه" },
    { isHoliday: false, month: 11, day: 24, name: "روز بزرگداشت اختر چرخ ادب، پروین اعتصامی" },
    { isHoliday: true, month: 11, day: 28, name: "روز ملی شدن صنعت نفت ایران" },
];

export const dayTimeHours = ['0am', '1am', '2am', '3am', '4am', '5am', '6am', '7am', '8am', '9am', '10am', '11am', '12am',
    '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm', '8pm', '9pm', '10pm', '11pm', '12pm']