
import * as d from './components';

export const DIRECTIVES = [
  d.EuiAutoComplete,
  d.EuiBadge,
  d.EuiBreadcrumb,
  d.EuiButton,
  d.EuiCalendar,
  d.EuiCalendarHeader,
  d.EuiCalendarNavigator,
  d.EuiCard,
  d.EuiCheckbox,
  d.EuiChips,
  d.EuiDatepicker,
  d.EuiDayView,
  d.EuiDecadeCard,
  d.EuiDialogue,
  d.EuiDropdown,
  d.EuiFeed,
  d.EuiIcon,
  d.EuiInput,
  d.EuiKnob,
  d.EuiMonthCard,
  d.EuiMonthView,
  d.EuiPaginator,
  d.EuiProgressbar,
  d.EuiSideNav,
  d.EuiSlider,
  d.EuiSnackbar,
  d.EuiStat,
  d.EuiStepper,
  d.EuiTab,
  d.EuiToggle,
  d.EuiTree,
  d.EuiWeekView,
  d.EuiYear,
  d.EuiYearCard
];
