import { Routes } from '@angular/router';
import { ButtonComponent } from './button.component';
import { InputComponent } from './input.component.ts';
import { IconComponent } from './icon.component';
import { AutoCompleteComponent } from './autocomplete.component';
import { BadgeComponent } from './badge.component';
import { DropdownComponent } from './dropdown.component';
import { ChipsComponent } from './chips.component';
import { CardComponent } from './card.component';
import { CheckboxComponent } from './checkbox.component';
import { PaginatorComponent } from './paginator.component.';
import { DialogueComponent } from './dialogue.component';
import { ProgressbarComponent } from './progressbar.component';
import { SliderComponent } from './slider.component';

export const routes: Routes = [
    { path: "button", component: ButtonComponent },
    { path: "input", component: InputComponent },
    { path: "icon", component: IconComponent },
    { path: "autocomplete", component: AutoCompleteComponent },
    { path: "badge", component: BadgeComponent },
    { path: "dropdown", component: DropdownComponent },
    { path: "chips", component: ChipsComponent },
    { path: "card", component: CardComponent },
    { path: "checkbox", component: CheckboxComponent },
    { path: "paginator", component: PaginatorComponent },
    { path: "dialogue", component: DialogueComponent },
    { path: "progressbar", component: ProgressbarComponent },
    { path: "slider", component: SliderComponent },
];
