'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EnsembleButton as EnsembleButtonElement, defineCustomElement as defineEnsembleButton } from "ensemble-ui/dist/components/ensemble-button.js";
import React from 'react';

export type EnsembleButtonEvents = NonNullable<unknown>;

export const EnsembleButton: StencilReactComponent<EnsembleButtonElement, EnsembleButtonEvents> = /*@__PURE__*/ createComponent<EnsembleButtonElement, EnsembleButtonEvents>({
    tagName: 'ensemble-button',
    elementClass: EnsembleButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EnsembleButtonEvents,
    defineCustomElement: defineEnsembleButton
});
