'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSparkles as EuiIconSparklesElement, defineCustomElement as defineEuiIconSparkles } from "ensemble-ui/dist/components/eui-icon-sparkles.js";
import React from 'react';

export type EuiIconSparklesEvents = NonNullable<unknown>;

export const EuiIconSparkles: StencilReactComponent<EuiIconSparklesElement, EuiIconSparklesEvents> = /*@__PURE__*/ createComponent<EuiIconSparklesElement, EuiIconSparklesEvents>({
    tagName: 'eui-icon-sparkles',
    elementClass: EuiIconSparklesElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSparklesEvents,
    defineCustomElement: defineEuiIconSparkles
});
