'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowsUpDown as EuiIconArrowsUpDownElement, defineCustomElement as defineEuiIconArrowsUpDown } from "ensemble-ui/dist/components/eui-icon-arrows-up-down.js";
import React from 'react';

export type EuiIconArrowsUpDownEvents = NonNullable<unknown>;

export const EuiIconArrowsUpDown: StencilReactComponent<EuiIconArrowsUpDownElement, EuiIconArrowsUpDownEvents> = /*@__PURE__*/ createComponent<EuiIconArrowsUpDownElement, EuiIconArrowsUpDownEvents>({
    tagName: 'eui-icon-arrows-up-down',
    elementClass: EuiIconArrowsUpDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowsUpDownEvents,
    defineCustomElement: defineEuiIconArrowsUpDown
});
