'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBriefcase as EuiIconBriefcaseElement, defineCustomElement as defineEuiIconBriefcase } from "ensemble-ui/dist/components/eui-icon-briefcase.js";
import React from 'react';

export type EuiIconBriefcaseEvents = NonNullable<unknown>;

export const EuiIconBriefcase: StencilReactComponent<EuiIconBriefcaseElement, EuiIconBriefcaseEvents> = /*@__PURE__*/ createComponent<EuiIconBriefcaseElement, EuiIconBriefcaseEvents>({
    tagName: 'eui-icon-briefcase',
    elementClass: EuiIconBriefcaseElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBriefcaseEvents,
    defineCustomElement: defineEuiIconBriefcase
});
