'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBattery0 as EuiIconBattery0Element, defineCustomElement as defineEuiIconBattery0 } from "ensemble-ui/dist/components/eui-icon-battery-0.js";
import React from 'react';

export type EuiIconBattery0Events = NonNullable<unknown>;

export const EuiIconBattery0: StencilReactComponent<EuiIconBattery0Element, EuiIconBattery0Events> = /*@__PURE__*/ createComponent<EuiIconBattery0Element, EuiIconBattery0Events>({
    tagName: 'eui-icon-battery-0',
    elementClass: EuiIconBattery0Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBattery0Events,
    defineCustomElement: defineEuiIconBattery0
});
