'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconExclamationTriangle as EuiIconExclamationTriangleElement, defineCustomElement as defineEuiIconExclamationTriangle } from "ensemble-ui/dist/components/eui-icon-exclamation-triangle.js";
import React from 'react';

export type EuiIconExclamationTriangleEvents = NonNullable<unknown>;

export const EuiIconExclamationTriangle: StencilReactComponent<EuiIconExclamationTriangleElement, EuiIconExclamationTriangleEvents> = /*@__PURE__*/ createComponent<EuiIconExclamationTriangleElement, EuiIconExclamationTriangleEvents>({
    tagName: 'eui-icon-exclamation-triangle',
    elementClass: EuiIconExclamationTriangleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconExclamationTriangleEvents,
    defineCustomElement: defineEuiIconExclamationTriangle
});
