'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconHandRaised as EuiIconHandRaisedElement, defineCustomElement as defineEuiIconHandRaised } from "ensemble-ui/dist/components/eui-icon-hand-raised.js";
import React from 'react';

export type EuiIconHandRaisedEvents = NonNullable<unknown>;

export const EuiIconHandRaised: StencilReactComponent<EuiIconHandRaisedElement, EuiIconHandRaisedEvents> = /*@__PURE__*/ createComponent<EuiIconHandRaisedElement, EuiIconHandRaisedEvents>({
    tagName: 'eui-icon-hand-raised',
    elementClass: EuiIconHandRaisedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconHandRaisedEvents,
    defineCustomElement: defineEuiIconHandRaised
});
