'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFaceFrown as EuiIconFaceFrownElement, defineCustomElement as defineEuiIconFaceFrown } from "ensemble-ui/dist/components/eui-icon-face-frown.js";
import React from 'react';

export type EuiIconFaceFrownEvents = NonNullable<unknown>;

export const EuiIconFaceFrown: StencilReactComponent<EuiIconFaceFrownElement, EuiIconFaceFrownEvents> = /*@__PURE__*/ createComponent<EuiIconFaceFrownElement, EuiIconFaceFrownEvents>({
    tagName: 'eui-icon-face-frown',
    elementClass: EuiIconFaceFrownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFaceFrownEvents,
    defineCustomElement: defineEuiIconFaceFrown
});
