'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconShieldExclamation as EuiIconShieldExclamationElement, defineCustomElement as defineEuiIconShieldExclamation } from "ensemble-ui/dist/components/eui-icon-shield-exclamation.js";
import React from 'react';

export type EuiIconShieldExclamationEvents = NonNullable<unknown>;

export const EuiIconShieldExclamation: StencilReactComponent<EuiIconShieldExclamationElement, EuiIconShieldExclamationEvents> = /*@__PURE__*/ createComponent<EuiIconShieldExclamationElement, EuiIconShieldExclamationEvents>({
    tagName: 'eui-icon-shield-exclamation',
    elementClass: EuiIconShieldExclamationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconShieldExclamationEvents,
    defineCustomElement: defineEuiIconShieldExclamation
});
