'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBars4 as EuiIconBars4Element, defineCustomElement as defineEuiIconBars4 } from "ensemble-ui/dist/components/eui-icon-bars-4.js";
import React from 'react';

export type EuiIconBars4Events = NonNullable<unknown>;

export const EuiIconBars4: StencilReactComponent<EuiIconBars4Element, EuiIconBars4Events> = /*@__PURE__*/ createComponent<EuiIconBars4Element, EuiIconBars4Events>({
    tagName: 'eui-icon-bars-4',
    elementClass: EuiIconBars4Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBars4Events,
    defineCustomElement: defineEuiIconBars4
});
