'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconHomeModern as EuiIconHomeModernElement, defineCustomElement as defineEuiIconHomeModern } from "ensemble-ui/dist/components/eui-icon-home-modern.js";
import React from 'react';

export type EuiIconHomeModernEvents = NonNullable<unknown>;

export const EuiIconHomeModern: StencilReactComponent<EuiIconHomeModernElement, EuiIconHomeModernEvents> = /*@__PURE__*/ createComponent<EuiIconHomeModernElement, EuiIconHomeModernEvents>({
    tagName: 'eui-icon-home-modern',
    elementClass: EuiIconHomeModernElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconHomeModernEvents,
    defineCustomElement: defineEuiIconHomeModern
});
