'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUpCircle as EuiIconArrowUpCircleElement, defineCustomElement as defineEuiIconArrowUpCircle } from "ensemble-ui/dist/components/eui-icon-arrow-up-circle.js";
import React from 'react';

export type EuiIconArrowUpCircleEvents = NonNullable<unknown>;

export const EuiIconArrowUpCircle: StencilReactComponent<EuiIconArrowUpCircleElement, EuiIconArrowUpCircleEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUpCircleElement, EuiIconArrowUpCircleEvents>({
    tagName: 'eui-icon-arrow-up-circle',
    elementClass: EuiIconArrowUpCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUpCircleEvents,
    defineCustomElement: defineEuiIconArrowUpCircle
});
