'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPhoneArrowUpRight as EuiIconPhoneArrowUpRightElement, defineCustomElement as defineEuiIconPhoneArrowUpRight } from "ensemble-ui/dist/components/eui-icon-phone-arrow-up-right.js";
import React from 'react';

export type EuiIconPhoneArrowUpRightEvents = NonNullable<unknown>;

export const EuiIconPhoneArrowUpRight: StencilReactComponent<EuiIconPhoneArrowUpRightElement, EuiIconPhoneArrowUpRightEvents> = /*@__PURE__*/ createComponent<EuiIconPhoneArrowUpRightElement, EuiIconPhoneArrowUpRightEvents>({
    tagName: 'eui-icon-phone-arrow-up-right',
    elementClass: EuiIconPhoneArrowUpRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPhoneArrowUpRightEvents,
    defineCustomElement: defineEuiIconPhoneArrowUpRight
});
