'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconScale as EuiIconScaleElement, defineCustomElement as defineEuiIconScale } from "ensemble-ui/dist/components/eui-icon-scale.js";
import React from 'react';

export type EuiIconScaleEvents = NonNullable<unknown>;

export const EuiIconScale: StencilReactComponent<EuiIconScaleElement, EuiIconScaleEvents> = /*@__PURE__*/ createComponent<EuiIconScaleElement, EuiIconScaleEvents>({
    tagName: 'eui-icon-scale',
    elementClass: EuiIconScaleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconScaleEvents,
    defineCustomElement: defineEuiIconScale
});
