'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconQuestionMarkCircle as EuiIconQuestionMarkCircleElement, defineCustomElement as defineEuiIconQuestionMarkCircle } from "ensemble-ui/dist/components/eui-icon-question-mark-circle.js";
import React from 'react';

export type EuiIconQuestionMarkCircleEvents = NonNullable<unknown>;

export const EuiIconQuestionMarkCircle: StencilReactComponent<EuiIconQuestionMarkCircleElement, EuiIconQuestionMarkCircleEvents> = /*@__PURE__*/ createComponent<EuiIconQuestionMarkCircleElement, EuiIconQuestionMarkCircleEvents>({
    tagName: 'eui-icon-question-mark-circle',
    elementClass: EuiIconQuestionMarkCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconQuestionMarkCircleEvents,
    defineCustomElement: defineEuiIconQuestionMarkCircle
});
