'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconUserMinus as EuiIconUserMinusElement, defineCustomElement as defineEuiIconUserMinus } from "ensemble-ui/dist/components/eui-icon-user-minus.js";
import React from 'react';

export type EuiIconUserMinusEvents = NonNullable<unknown>;

export const EuiIconUserMinus: StencilReactComponent<EuiIconUserMinusElement, EuiIconUserMinusEvents> = /*@__PURE__*/ createComponent<EuiIconUserMinusElement, EuiIconUserMinusEvents>({
    tagName: 'eui-icon-user-minus',
    elementClass: EuiIconUserMinusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconUserMinusEvents,
    defineCustomElement: defineEuiIconUserMinus
});
