'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBars3BottomRight as EuiIconBars3BottomRightElement, defineCustomElement as defineEuiIconBars3BottomRight } from "ensemble-ui/dist/components/eui-icon-bars-3-bottom-right.js";
import React from 'react';

export type EuiIconBars3BottomRightEvents = NonNullable<unknown>;

export const EuiIconBars3BottomRight: StencilReactComponent<EuiIconBars3BottomRightElement, EuiIconBars3BottomRightEvents> = /*@__PURE__*/ createComponent<EuiIconBars3BottomRightElement, EuiIconBars3BottomRightEvents>({
    tagName: 'eui-icon-bars-3-bottom-right',
    elementClass: EuiIconBars3BottomRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBars3BottomRightEvents,
    defineCustomElement: defineEuiIconBars3BottomRight
});
