'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFolderOpen as EuiIconFolderOpenElement, defineCustomElement as defineEuiIconFolderOpen } from "ensemble-ui/dist/components/eui-icon-folder-open.js";
import React from 'react';

export type EuiIconFolderOpenEvents = NonNullable<unknown>;

export const EuiIconFolderOpen: StencilReactComponent<EuiIconFolderOpenElement, EuiIconFolderOpenEvents> = /*@__PURE__*/ createComponent<EuiIconFolderOpenElement, EuiIconFolderOpenEvents>({
    tagName: 'eui-icon-folder-open',
    elementClass: EuiIconFolderOpenElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFolderOpenEvents,
    defineCustomElement: defineEuiIconFolderOpen
});
