'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowLeftEndOnRectangle as EuiIconArrowLeftEndOnRectangleElement, defineCustomElement as defineEuiIconArrowLeftEndOnRectangle } from "ensemble-ui/dist/components/eui-icon-arrow-left-end-on-rectangle.js";
import React from 'react';

export type EuiIconArrowLeftEndOnRectangleEvents = NonNullable<unknown>;

export const EuiIconArrowLeftEndOnRectangle: StencilReactComponent<EuiIconArrowLeftEndOnRectangleElement, EuiIconArrowLeftEndOnRectangleEvents> = /*@__PURE__*/ createComponent<EuiIconArrowLeftEndOnRectangleElement, EuiIconArrowLeftEndOnRectangleEvents>({
    tagName: 'eui-icon-arrow-left-end-on-rectangle',
    elementClass: EuiIconArrowLeftEndOnRectangleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowLeftEndOnRectangleEvents,
    defineCustomElement: defineEuiIconArrowLeftEndOnRectangle
});
