'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconTrophy as EuiIconTrophyElement, defineCustomElement as defineEuiIconTrophy } from "ensemble-ui/dist/components/eui-icon-trophy.js";
import React from 'react';

export type EuiIconTrophyEvents = NonNullable<unknown>;

export const EuiIconTrophy: StencilReactComponent<EuiIconTrophyElement, EuiIconTrophyEvents> = /*@__PURE__*/ createComponent<EuiIconTrophyElement, EuiIconTrophyEvents>({
    tagName: 'eui-icon-trophy',
    elementClass: EuiIconTrophyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconTrophyEvents,
    defineCustomElement: defineEuiIconTrophy
});
