'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCurrencyPound as EuiIconCurrencyPoundElement, defineCustomElement as defineEuiIconCurrencyPound } from "ensemble-ui/dist/components/eui-icon-currency-pound.js";
import React from 'react';

export type EuiIconCurrencyPoundEvents = NonNullable<unknown>;

export const EuiIconCurrencyPound: StencilReactComponent<EuiIconCurrencyPoundElement, EuiIconCurrencyPoundEvents> = /*@__PURE__*/ createComponent<EuiIconCurrencyPoundElement, EuiIconCurrencyPoundEvents>({
    tagName: 'eui-icon-currency-pound',
    elementClass: EuiIconCurrencyPoundElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCurrencyPoundEvents,
    defineCustomElement: defineEuiIconCurrencyPound
});
