'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type EuiMonthViewCustomEvent } from "ensemble-ui";
import { EuiMonthView as EuiMonthViewElement, defineCustomElement as defineEuiMonthView } from "ensemble-ui/dist/components/eui-month-view.js";
import React from 'react';

export type EuiMonthViewEvents = { onDayClick: EventName<EuiMonthViewCustomEvent<Date>> };

export const EuiMonthView: StencilReactComponent<EuiMonthViewElement, EuiMonthViewEvents> = /*@__PURE__*/ createComponent<EuiMonthViewElement, EuiMonthViewEvents>({
    tagName: 'eui-month-view',
    elementClass: EuiMonthViewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDayClick: 'dayClick' } as EuiMonthViewEvents,
    defineCustomElement: defineEuiMonthView
});
