'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChatBubbleBottomCenterText as EuiIconChatBubbleBottomCenterTextElement, defineCustomElement as defineEuiIconChatBubbleBottomCenterText } from "ensemble-ui/dist/components/eui-icon-chat-bubble-bottom-center-text.js";
import React from 'react';

export type EuiIconChatBubbleBottomCenterTextEvents = NonNullable<unknown>;

export const EuiIconChatBubbleBottomCenterText: StencilReactComponent<EuiIconChatBubbleBottomCenterTextElement, EuiIconChatBubbleBottomCenterTextEvents> = /*@__PURE__*/ createComponent<EuiIconChatBubbleBottomCenterTextElement, EuiIconChatBubbleBottomCenterTextEvents>({
    tagName: 'eui-icon-chat-bubble-bottom-center-text',
    elementClass: EuiIconChatBubbleBottomCenterTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChatBubbleBottomCenterTextEvents,
    defineCustomElement: defineEuiIconChatBubbleBottomCenterText
});
