'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconHandThumbUp as EuiIconHandThumbUpElement, defineCustomElement as defineEuiIconHandThumbUp } from "ensemble-ui/dist/components/eui-icon-hand-thumb-up.js";
import React from 'react';

export type EuiIconHandThumbUpEvents = NonNullable<unknown>;

export const EuiIconHandThumbUp: StencilReactComponent<EuiIconHandThumbUpElement, EuiIconHandThumbUpEvents> = /*@__PURE__*/ createComponent<EuiIconHandThumbUpElement, EuiIconHandThumbUpEvents>({
    tagName: 'eui-icon-hand-thumb-up',
    elementClass: EuiIconHandThumbUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconHandThumbUpEvents,
    defineCustomElement: defineEuiIconHandThumbUp
});
