'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUturnUp as EuiIconArrowUturnUpElement, defineCustomElement as defineEuiIconArrowUturnUp } from "ensemble-ui/dist/components/eui-icon-arrow-uturn-up.js";
import React from 'react';

export type EuiIconArrowUturnUpEvents = NonNullable<unknown>;

export const EuiIconArrowUturnUp: StencilReactComponent<EuiIconArrowUturnUpElement, EuiIconArrowUturnUpEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUturnUpElement, EuiIconArrowUturnUpEvents>({
    tagName: 'eui-icon-arrow-uturn-up',
    elementClass: EuiIconArrowUturnUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUturnUpEvents,
    defineCustomElement: defineEuiIconArrowUturnUp
});
