'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBattery100 as EuiIconBattery100Element, defineCustomElement as defineEuiIconBattery100 } from "ensemble-ui/dist/components/eui-icon-battery-100.js";
import React from 'react';

export type EuiIconBattery100Events = NonNullable<unknown>;

export const EuiIconBattery100: StencilReactComponent<EuiIconBattery100Element, EuiIconBattery100Events> = /*@__PURE__*/ createComponent<EuiIconBattery100Element, EuiIconBattery100Events>({
    tagName: 'eui-icon-battery-100',
    elementClass: EuiIconBattery100Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBattery100Events,
    defineCustomElement: defineEuiIconBattery100
});
