'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChevronDoubleRight as EuiIconChevronDoubleRightElement, defineCustomElement as defineEuiIconChevronDoubleRight } from "ensemble-ui/dist/components/eui-icon-chevron-double-right.js";
import React from 'react';

export type EuiIconChevronDoubleRightEvents = NonNullable<unknown>;

export const EuiIconChevronDoubleRight: StencilReactComponent<EuiIconChevronDoubleRightElement, EuiIconChevronDoubleRightEvents> = /*@__PURE__*/ createComponent<EuiIconChevronDoubleRightElement, EuiIconChevronDoubleRightEvents>({
    tagName: 'eui-icon-chevron-double-right',
    elementClass: EuiIconChevronDoubleRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChevronDoubleRightEvents,
    defineCustomElement: defineEuiIconChevronDoubleRight
});
