'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconEllipsisVertical as EuiIconEllipsisVerticalElement, defineCustomElement as defineEuiIconEllipsisVertical } from "ensemble-ui/dist/components/eui-icon-ellipsis-vertical.js";
import React from 'react';

export type EuiIconEllipsisVerticalEvents = NonNullable<unknown>;

export const EuiIconEllipsisVertical: StencilReactComponent<EuiIconEllipsisVerticalElement, EuiIconEllipsisVerticalEvents> = /*@__PURE__*/ createComponent<EuiIconEllipsisVerticalElement, EuiIconEllipsisVerticalEvents>({
    tagName: 'eui-icon-ellipsis-vertical',
    elementClass: EuiIconEllipsisVerticalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEllipsisVerticalEvents,
    defineCustomElement: defineEuiIconEllipsisVertical
});
