'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArchiveBoxArrowDown as EuiIconArchiveBoxArrowDownElement, defineCustomElement as defineEuiIconArchiveBoxArrowDown } from "ensemble-ui/dist/components/eui-icon-archive-box-arrow-down.js";
import React from 'react';

export type EuiIconArchiveBoxArrowDownEvents = NonNullable<unknown>;

export const EuiIconArchiveBoxArrowDown: StencilReactComponent<EuiIconArchiveBoxArrowDownElement, EuiIconArchiveBoxArrowDownEvents> = /*@__PURE__*/ createComponent<EuiIconArchiveBoxArrowDownElement, EuiIconArchiveBoxArrowDownEvents>({
    tagName: 'eui-icon-archive-box-arrow-down',
    elementClass: EuiIconArchiveBoxArrowDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArchiveBoxArrowDownEvents,
    defineCustomElement: defineEuiIconArchiveBoxArrowDown
});
