'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconLinkSlash as EuiIconLinkSlashElement, defineCustomElement as defineEuiIconLinkSlash } from "ensemble-ui/dist/components/eui-icon-link-slash.js";
import React from 'react';

export type EuiIconLinkSlashEvents = NonNullable<unknown>;

export const EuiIconLinkSlash: StencilReactComponent<EuiIconLinkSlashElement, EuiIconLinkSlashEvents> = /*@__PURE__*/ createComponent<EuiIconLinkSlashElement, EuiIconLinkSlashEvents>({
    tagName: 'eui-icon-link-slash',
    elementClass: EuiIconLinkSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconLinkSlashEvents,
    defineCustomElement: defineEuiIconLinkSlash
});
