'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMapPin as EuiIconMapPinElement, defineCustomElement as defineEuiIconMapPin } from "ensemble-ui/dist/components/eui-icon-map-pin.js";
import React from 'react';

export type EuiIconMapPinEvents = NonNullable<unknown>;

export const EuiIconMapPin: StencilReactComponent<EuiIconMapPinElement, EuiIconMapPinEvents> = /*@__PURE__*/ createComponent<EuiIconMapPinElement, EuiIconMapPinEvents>({
    tagName: 'eui-icon-map-pin',
    elementClass: EuiIconMapPinElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMapPinEvents,
    defineCustomElement: defineEuiIconMapPin
});
