'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconViewColumns as EuiIconViewColumnsElement, defineCustomElement as defineEuiIconViewColumns } from "ensemble-ui/dist/components/eui-icon-view-columns.js";
import React from 'react';

export type EuiIconViewColumnsEvents = NonNullable<unknown>;

export const EuiIconViewColumns: StencilReactComponent<EuiIconViewColumnsElement, EuiIconViewColumnsEvents> = /*@__PURE__*/ createComponent<EuiIconViewColumnsElement, EuiIconViewColumnsEvents>({
    tagName: 'eui-icon-view-columns',
    elementClass: EuiIconViewColumnsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconViewColumnsEvents,
    defineCustomElement: defineEuiIconViewColumns
});
