'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMagnifyingGlassCircle as EuiIconMagnifyingGlassCircleElement, defineCustomElement as defineEuiIconMagnifyingGlassCircle } from "ensemble-ui/dist/components/eui-icon-magnifying-glass-circle.js";
import React from 'react';

export type EuiIconMagnifyingGlassCircleEvents = NonNullable<unknown>;

export const EuiIconMagnifyingGlassCircle: StencilReactComponent<EuiIconMagnifyingGlassCircleElement, EuiIconMagnifyingGlassCircleEvents> = /*@__PURE__*/ createComponent<EuiIconMagnifyingGlassCircleElement, EuiIconMagnifyingGlassCircleEvents>({
    tagName: 'eui-icon-magnifying-glass-circle',
    elementClass: EuiIconMagnifyingGlassCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMagnifyingGlassCircleEvents,
    defineCustomElement: defineEuiIconMagnifyingGlassCircle
});
