'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiTextarea as EuiTextareaElement, defineCustomElement as defineEuiTextarea } from "ensemble-ui/dist/components/eui-textarea.js";
import React from 'react';

export type EuiTextareaEvents = {
    onClear: EventName<CustomEvent<any>>,
    onChange: EventName<CustomEvent<any>>,
    onKeyUp: EventName<CustomEvent<any>>,
    onKeyDown: EventName<CustomEvent<any>>,
    onKeyPress: EventName<CustomEvent<any>>
};

export const EuiTextarea: StencilReactComponent<EuiTextareaElement, EuiTextareaEvents> = /*@__PURE__*/ createComponent<EuiTextareaElement, EuiTextareaEvents>({
    tagName: 'eui-textarea',
    elementClass: EuiTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onClear: 'clear',
        onChange: 'change',
        onKeyUp: 'keyUp',
        onKeyDown: 'keyDown',
        onKeyPress: 'keyPress'
    } as EuiTextareaEvents,
    defineCustomElement: defineEuiTextarea
});
