'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBuildingOffice as EuiIconBuildingOfficeElement, defineCustomElement as defineEuiIconBuildingOffice } from "ensemble-ui/dist/components/eui-icon-building-office.js";
import React from 'react';

export type EuiIconBuildingOfficeEvents = NonNullable<unknown>;

export const EuiIconBuildingOffice: StencilReactComponent<EuiIconBuildingOfficeElement, EuiIconBuildingOfficeEvents> = /*@__PURE__*/ createComponent<EuiIconBuildingOfficeElement, EuiIconBuildingOfficeEvents>({
    tagName: 'eui-icon-building-office',
    elementClass: EuiIconBuildingOfficeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBuildingOfficeEvents,
    defineCustomElement: defineEuiIconBuildingOffice
});
