'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTurnUpRight as EuiIconArrowTurnUpRightElement, defineCustomElement as defineEuiIconArrowTurnUpRight } from "ensemble-ui/dist/components/eui-icon-arrow-turn-up-right.js";
import React from 'react';

export type EuiIconArrowTurnUpRightEvents = NonNullable<unknown>;

export const EuiIconArrowTurnUpRight: StencilReactComponent<EuiIconArrowTurnUpRightElement, EuiIconArrowTurnUpRightEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTurnUpRightElement, EuiIconArrowTurnUpRightEvents>({
    tagName: 'eui-icon-arrow-turn-up-right',
    elementClass: EuiIconArrowTurnUpRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTurnUpRightEvents,
    defineCustomElement: defineEuiIconArrowTurnUpRight
});
