'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconGlobeAlt as EuiIconGlobeAltElement, defineCustomElement as defineEuiIconGlobeAlt } from "ensemble-ui/dist/components/eui-icon-globe-alt.js";
import React from 'react';

export type EuiIconGlobeAltEvents = NonNullable<unknown>;

export const EuiIconGlobeAlt: StencilReactComponent<EuiIconGlobeAltElement, EuiIconGlobeAltEvents> = /*@__PURE__*/ createComponent<EuiIconGlobeAltElement, EuiIconGlobeAltEvents>({
    tagName: 'eui-icon-globe-alt',
    elementClass: EuiIconGlobeAltElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconGlobeAltEvents,
    defineCustomElement: defineEuiIconGlobeAlt
});
