'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconUserPlus as EuiIconUserPlusElement, defineCustomElement as defineEuiIconUserPlus } from "ensemble-ui/dist/components/eui-icon-user-plus.js";
import React from 'react';

export type EuiIconUserPlusEvents = NonNullable<unknown>;

export const EuiIconUserPlus: StencilReactComponent<EuiIconUserPlusElement, EuiIconUserPlusEvents> = /*@__PURE__*/ createComponent<EuiIconUserPlusElement, EuiIconUserPlusEvents>({
    tagName: 'eui-icon-user-plus',
    elementClass: EuiIconUserPlusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconUserPlusEvents,
    defineCustomElement: defineEuiIconUserPlus
});
