'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowRightCircle as EuiIconArrowRightCircleElement, defineCustomElement as defineEuiIconArrowRightCircle } from "ensemble-ui/dist/components/eui-icon-arrow-right-circle.js";
import React from 'react';

export type EuiIconArrowRightCircleEvents = NonNullable<unknown>;

export const EuiIconArrowRightCircle: StencilReactComponent<EuiIconArrowRightCircleElement, EuiIconArrowRightCircleEvents> = /*@__PURE__*/ createComponent<EuiIconArrowRightCircleElement, EuiIconArrowRightCircleEvents>({
    tagName: 'eui-icon-arrow-right-circle',
    elementClass: EuiIconArrowRightCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowRightCircleEvents,
    defineCustomElement: defineEuiIconArrowRightCircle
});
