'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCommandLine as EuiIconCommandLineElement, defineCustomElement as defineEuiIconCommandLine } from "ensemble-ui/dist/components/eui-icon-command-line.js";
import React from 'react';

export type EuiIconCommandLineEvents = NonNullable<unknown>;

export const EuiIconCommandLine: StencilReactComponent<EuiIconCommandLineElement, EuiIconCommandLineEvents> = /*@__PURE__*/ createComponent<EuiIconCommandLineElement, EuiIconCommandLineEvents>({
    tagName: 'eui-icon-command-line',
    elementClass: EuiIconCommandLineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCommandLineEvents,
    defineCustomElement: defineEuiIconCommandLine
});
