'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCreditCard as EuiIconCreditCardElement, defineCustomElement as defineEuiIconCreditCard } from "ensemble-ui/dist/components/eui-icon-credit-card.js";
import React from 'react';

export type EuiIconCreditCardEvents = NonNullable<unknown>;

export const EuiIconCreditCard: StencilReactComponent<EuiIconCreditCardElement, EuiIconCreditCardEvents> = /*@__PURE__*/ createComponent<EuiIconCreditCardElement, EuiIconCreditCardEvents>({
    tagName: 'eui-icon-credit-card',
    elementClass: EuiIconCreditCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCreditCardEvents,
    defineCustomElement: defineEuiIconCreditCard
});
