'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconHeart as EuiIconHeartElement, defineCustomElement as defineEuiIconHeart } from "ensemble-ui/dist/components/eui-icon-heart.js";
import React from 'react';

export type EuiIconHeartEvents = NonNullable<unknown>;

export const EuiIconHeart: StencilReactComponent<EuiIconHeartElement, EuiIconHeartEvents> = /*@__PURE__*/ createComponent<EuiIconHeartElement, EuiIconHeartEvents>({
    tagName: 'eui-icon-heart',
    elementClass: EuiIconHeartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconHeartEvents,
    defineCustomElement: defineEuiIconHeart
});
