'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconTableCells as EuiIconTableCellsElement, defineCustomElement as defineEuiIconTableCells } from "ensemble-ui/dist/components/eui-icon-table-cells.js";
import React from 'react';

export type EuiIconTableCellsEvents = NonNullable<unknown>;

export const EuiIconTableCells: StencilReactComponent<EuiIconTableCellsElement, EuiIconTableCellsEvents> = /*@__PURE__*/ createComponent<EuiIconTableCellsElement, EuiIconTableCellsEvents>({
    tagName: 'eui-icon-table-cells',
    elementClass: EuiIconTableCellsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconTableCellsEvents,
    defineCustomElement: defineEuiIconTableCells
});
