'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentPlus as EuiIconDocumentPlusElement, defineCustomElement as defineEuiIconDocumentPlus } from "ensemble-ui/dist/components/eui-icon-document-plus.js";
import React from 'react';

export type EuiIconDocumentPlusEvents = NonNullable<unknown>;

export const EuiIconDocumentPlus: StencilReactComponent<EuiIconDocumentPlusElement, EuiIconDocumentPlusEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentPlusElement, EuiIconDocumentPlusEvents>({
    tagName: 'eui-icon-document-plus',
    elementClass: EuiIconDocumentPlusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentPlusEvents,
    defineCustomElement: defineEuiIconDocumentPlus
});
