'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPhoneArrowDownLeft as EuiIconPhoneArrowDownLeftElement, defineCustomElement as defineEuiIconPhoneArrowDownLeft } from "ensemble-ui/dist/components/eui-icon-phone-arrow-down-left.js";
import React from 'react';

export type EuiIconPhoneArrowDownLeftEvents = NonNullable<unknown>;

export const EuiIconPhoneArrowDownLeft: StencilReactComponent<EuiIconPhoneArrowDownLeftElement, EuiIconPhoneArrowDownLeftEvents> = /*@__PURE__*/ createComponent<EuiIconPhoneArrowDownLeftElement, EuiIconPhoneArrowDownLeftEvents>({
    tagName: 'eui-icon-phone-arrow-down-left',
    elementClass: EuiIconPhoneArrowDownLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPhoneArrowDownLeftEvents,
    defineCustomElement: defineEuiIconPhoneArrowDownLeft
});
