'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBarsArrowUp as EuiIconBarsArrowUpElement, defineCustomElement as defineEuiIconBarsArrowUp } from "ensemble-ui/dist/components/eui-icon-bars-arrow-up.js";
import React from 'react';

export type EuiIconBarsArrowUpEvents = NonNullable<unknown>;

export const EuiIconBarsArrowUp: StencilReactComponent<EuiIconBarsArrowUpElement, EuiIconBarsArrowUpEvents> = /*@__PURE__*/ createComponent<EuiIconBarsArrowUpElement, EuiIconBarsArrowUpEvents>({
    tagName: 'eui-icon-bars-arrow-up',
    elementClass: EuiIconBarsArrowUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBarsArrowUpEvents,
    defineCustomElement: defineEuiIconBarsArrowUp
});
