'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBattery50 as EuiIconBattery50Element, defineCustomElement as defineEuiIconBattery50 } from "ensemble-ui/dist/components/eui-icon-battery-50.js";
import React from 'react';

export type EuiIconBattery50Events = NonNullable<unknown>;

export const EuiIconBattery50: StencilReactComponent<EuiIconBattery50Element, EuiIconBattery50Events> = /*@__PURE__*/ createComponent<EuiIconBattery50Element, EuiIconBattery50Events>({
    tagName: 'eui-icon-battery-50',
    elementClass: EuiIconBattery50Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBattery50Events,
    defineCustomElement: defineEuiIconBattery50
});
