'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChevronUpDown as EuiIconChevronUpDownElement, defineCustomElement as defineEuiIconChevronUpDown } from "ensemble-ui/dist/components/eui-icon-chevron-up-down.js";
import React from 'react';

export type EuiIconChevronUpDownEvents = NonNullable<unknown>;

export const EuiIconChevronUpDown: StencilReactComponent<EuiIconChevronUpDownElement, EuiIconChevronUpDownEvents> = /*@__PURE__*/ createComponent<EuiIconChevronUpDownElement, EuiIconChevronUpDownEvents>({
    tagName: 'eui-icon-chevron-up-down',
    elementClass: EuiIconChevronUpDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChevronUpDownEvents,
    defineCustomElement: defineEuiIconChevronUpDown
});
