'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMoon as EuiIconMoonElement, defineCustomElement as defineEuiIconMoon } from "ensemble-ui/dist/components/eui-icon-moon.js";
import React from 'react';

export type EuiIconMoonEvents = NonNullable<unknown>;

export const EuiIconMoon: StencilReactComponent<EuiIconMoonElement, EuiIconMoonEvents> = /*@__PURE__*/ createComponent<EuiIconMoonElement, EuiIconMoonEvents>({
    tagName: 'eui-icon-moon',
    elementClass: EuiIconMoonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMoonEvents,
    defineCustomElement: defineEuiIconMoon
});
