'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPhone as EuiIconPhoneElement, defineCustomElement as defineEuiIconPhone } from "ensemble-ui/dist/components/eui-icon-phone.js";
import React from 'react';

export type EuiIconPhoneEvents = NonNullable<unknown>;

export const EuiIconPhone: StencilReactComponent<EuiIconPhoneElement, EuiIconPhoneEvents> = /*@__PURE__*/ createComponent<EuiIconPhoneElement, EuiIconPhoneEvents>({
    tagName: 'eui-icon-phone',
    elementClass: EuiIconPhoneElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPhoneEvents,
    defineCustomElement: defineEuiIconPhone
});
