'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiAutoComplete as EuiAutoCompleteElement, defineCustomElement as defineEuiAutoComplete } from "ensemble-ui/dist/components/eui-auto-complete.js";
import React from 'react';

export type EuiAutoCompleteEvents = NonNullable<unknown>;

export const EuiAutoComplete: StencilReactComponent<EuiAutoCompleteElement, EuiAutoCompleteEvents> = /*@__PURE__*/ createComponent<EuiAutoCompleteElement, EuiAutoCompleteEvents>({
    tagName: 'eui-auto-complete',
    elementClass: EuiAutoCompleteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiAutoCompleteEvents,
    defineCustomElement: defineEuiAutoComplete
});
