'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDevicePhoneMobile as EuiIconDevicePhoneMobileElement, defineCustomElement as defineEuiIconDevicePhoneMobile } from "ensemble-ui/dist/components/eui-icon-device-phone-mobile.js";
import React from 'react';

export type EuiIconDevicePhoneMobileEvents = NonNullable<unknown>;

export const EuiIconDevicePhoneMobile: StencilReactComponent<EuiIconDevicePhoneMobileElement, EuiIconDevicePhoneMobileEvents> = /*@__PURE__*/ createComponent<EuiIconDevicePhoneMobileElement, EuiIconDevicePhoneMobileEvents>({
    tagName: 'eui-icon-device-phone-mobile',
    elementClass: EuiIconDevicePhoneMobileElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDevicePhoneMobileEvents,
    defineCustomElement: defineEuiIconDevicePhoneMobile
});
