'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMinusCircle as EuiIconMinusCircleElement, defineCustomElement as defineEuiIconMinusCircle } from "ensemble-ui/dist/components/eui-icon-minus-circle.js";
import React from 'react';

export type EuiIconMinusCircleEvents = NonNullable<unknown>;

export const EuiIconMinusCircle: StencilReactComponent<EuiIconMinusCircleElement, EuiIconMinusCircleEvents> = /*@__PURE__*/ createComponent<EuiIconMinusCircleElement, EuiIconMinusCircleEvents>({
    tagName: 'eui-icon-minus-circle',
    elementClass: EuiIconMinusCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMinusCircleEvents,
    defineCustomElement: defineEuiIconMinusCircle
});
