'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconUserGroup as EuiIconUserGroupElement, defineCustomElement as defineEuiIconUserGroup } from "ensemble-ui/dist/components/eui-icon-user-group.js";
import React from 'react';

export type EuiIconUserGroupEvents = NonNullable<unknown>;

export const EuiIconUserGroup: StencilReactComponent<EuiIconUserGroupElement, EuiIconUserGroupEvents> = /*@__PURE__*/ createComponent<EuiIconUserGroupElement, EuiIconUserGroupEvents>({
    tagName: 'eui-icon-user-group',
    elementClass: EuiIconUserGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconUserGroupEvents,
    defineCustomElement: defineEuiIconUserGroup
});
