'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconEllipsisHorizontal as EuiIconEllipsisHorizontalElement, defineCustomElement as defineEuiIconEllipsisHorizontal } from "ensemble-ui/dist/components/eui-icon-ellipsis-horizontal.js";
import React from 'react';

export type EuiIconEllipsisHorizontalEvents = NonNullable<unknown>;

export const EuiIconEllipsisHorizontal: StencilReactComponent<EuiIconEllipsisHorizontalElement, EuiIconEllipsisHorizontalEvents> = /*@__PURE__*/ createComponent<EuiIconEllipsisHorizontalElement, EuiIconEllipsisHorizontalEvents>({
    tagName: 'eui-icon-ellipsis-horizontal',
    elementClass: EuiIconEllipsisHorizontalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEllipsisHorizontalEvents,
    defineCustomElement: defineEuiIconEllipsisHorizontal
});
