'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconUsers as EuiIconUsersElement, defineCustomElement as defineEuiIconUsers } from "ensemble-ui/dist/components/eui-icon-users.js";
import React from 'react';

export type EuiIconUsersEvents = NonNullable<unknown>;

export const EuiIconUsers: StencilReactComponent<EuiIconUsersElement, EuiIconUsersEvents> = /*@__PURE__*/ createComponent<EuiIconUsersElement, EuiIconUsersEvents>({
    tagName: 'eui-icon-users',
    elementClass: EuiIconUsersElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconUsersEvents,
    defineCustomElement: defineEuiIconUsers
});
