'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCalendarDateRange as EuiIconCalendarDateRangeElement, defineCustomElement as defineEuiIconCalendarDateRange } from "ensemble-ui/dist/components/eui-icon-calendar-date-range.js";
import React from 'react';

export type EuiIconCalendarDateRangeEvents = NonNullable<unknown>;

export const EuiIconCalendarDateRange: StencilReactComponent<EuiIconCalendarDateRangeElement, EuiIconCalendarDateRangeEvents> = /*@__PURE__*/ createComponent<EuiIconCalendarDateRangeElement, EuiIconCalendarDateRangeEvents>({
    tagName: 'eui-icon-calendar-date-range',
    elementClass: EuiIconCalendarDateRangeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCalendarDateRangeEvents,
    defineCustomElement: defineEuiIconCalendarDateRange
});
