'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCalculator as EuiIconCalculatorElement, defineCustomElement as defineEuiIconCalculator } from "ensemble-ui/dist/components/eui-icon-calculator.js";
import React from 'react';

export type EuiIconCalculatorEvents = NonNullable<unknown>;

export const EuiIconCalculator: StencilReactComponent<EuiIconCalculatorElement, EuiIconCalculatorEvents> = /*@__PURE__*/ createComponent<EuiIconCalculatorElement, EuiIconCalculatorEvents>({
    tagName: 'eui-icon-calculator',
    elementClass: EuiIconCalculatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCalculatorEvents,
    defineCustomElement: defineEuiIconCalculator
});
