'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconWrench as EuiIconWrenchElement, defineCustomElement as defineEuiIconWrench } from "ensemble-ui/dist/components/eui-icon-wrench.js";
import React from 'react';

export type EuiIconWrenchEvents = NonNullable<unknown>;

export const EuiIconWrench: StencilReactComponent<EuiIconWrenchElement, EuiIconWrenchEvents> = /*@__PURE__*/ createComponent<EuiIconWrenchElement, EuiIconWrenchEvents>({
    tagName: 'eui-icon-wrench',
    elementClass: EuiIconWrenchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconWrenchEvents,
    defineCustomElement: defineEuiIconWrench
});
