'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMinus as EuiIconMinusElement, defineCustomElement as defineEuiIconMinus } from "ensemble-ui/dist/components/eui-icon-minus.js";
import React from 'react';

export type EuiIconMinusEvents = NonNullable<unknown>;

export const EuiIconMinus: StencilReactComponent<EuiIconMinusElement, EuiIconMinusEvents> = /*@__PURE__*/ createComponent<EuiIconMinusElement, EuiIconMinusEvents>({
    tagName: 'eui-icon-minus',
    elementClass: EuiIconMinusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMinusEvents,
    defineCustomElement: defineEuiIconMinus
});
