'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBookmark as EuiIconBookmarkElement, defineCustomElement as defineEuiIconBookmark } from "ensemble-ui/dist/components/eui-icon-bookmark.js";
import React from 'react';

export type EuiIconBookmarkEvents = NonNullable<unknown>;

export const EuiIconBookmark: StencilReactComponent<EuiIconBookmarkElement, EuiIconBookmarkEvents> = /*@__PURE__*/ createComponent<EuiIconBookmarkElement, EuiIconBookmarkEvents>({
    tagName: 'eui-icon-bookmark',
    elementClass: EuiIconBookmarkElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBookmarkEvents,
    defineCustomElement: defineEuiIconBookmark
});
