'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBuildingOffice2 as EuiIconBuildingOffice2Element, defineCustomElement as defineEuiIconBuildingOffice2 } from "ensemble-ui/dist/components/eui-icon-building-office-2.js";
import React from 'react';

export type EuiIconBuildingOffice2Events = NonNullable<unknown>;

export const EuiIconBuildingOffice2: StencilReactComponent<EuiIconBuildingOffice2Element, EuiIconBuildingOffice2Events> = /*@__PURE__*/ createComponent<EuiIconBuildingOffice2Element, EuiIconBuildingOffice2Events>({
    tagName: 'eui-icon-building-office-2',
    elementClass: EuiIconBuildingOffice2Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBuildingOffice2Events,
    defineCustomElement: defineEuiIconBuildingOffice2
});
