'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiRadio as EuiRadioElement, defineCustomElement as defineEuiRadio } from "ensemble-ui/dist/components/eui-radio.js";
import React from 'react';

export type EuiRadioEvents = { onSelected: EventName<CustomEvent<string>> };

export const EuiRadio: StencilReactComponent<EuiRadioElement, EuiRadioEvents> = /*@__PURE__*/ createComponent<EuiRadioElement, EuiRadioEvents>({
    tagName: 'eui-radio',
    elementClass: EuiRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelected: 'selected' } as EuiRadioEvents,
    defineCustomElement: defineEuiRadio
});
