'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCurrencyRupee as EuiIconCurrencyRupeeElement, defineCustomElement as defineEuiIconCurrencyRupee } from "ensemble-ui/dist/components/eui-icon-currency-rupee.js";
import React from 'react';

export type EuiIconCurrencyRupeeEvents = NonNullable<unknown>;

export const EuiIconCurrencyRupee: StencilReactComponent<EuiIconCurrencyRupeeElement, EuiIconCurrencyRupeeEvents> = /*@__PURE__*/ createComponent<EuiIconCurrencyRupeeElement, EuiIconCurrencyRupeeEvents>({
    tagName: 'eui-icon-currency-rupee',
    elementClass: EuiIconCurrencyRupeeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCurrencyRupeeEvents,
    defineCustomElement: defineEuiIconCurrencyRupee
});
