'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBuildingStorefront as EuiIconBuildingStorefrontElement, defineCustomElement as defineEuiIconBuildingStorefront } from "ensemble-ui/dist/components/eui-icon-building-storefront.js";
import React from 'react';

export type EuiIconBuildingStorefrontEvents = NonNullable<unknown>;

export const EuiIconBuildingStorefront: StencilReactComponent<EuiIconBuildingStorefrontElement, EuiIconBuildingStorefrontEvents> = /*@__PURE__*/ createComponent<EuiIconBuildingStorefrontElement, EuiIconBuildingStorefrontEvents>({
    tagName: 'eui-icon-building-storefront',
    elementClass: EuiIconBuildingStorefrontElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBuildingStorefrontEvents,
    defineCustomElement: defineEuiIconBuildingStorefront
});
