'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFlag as EuiIconFlagElement, defineCustomElement as defineEuiIconFlag } from "ensemble-ui/dist/components/eui-icon-flag.js";
import React from 'react';

export type EuiIconFlagEvents = NonNullable<unknown>;

export const EuiIconFlag: StencilReactComponent<EuiIconFlagElement, EuiIconFlagEvents> = /*@__PURE__*/ createComponent<EuiIconFlagElement, EuiIconFlagEvents>({
    tagName: 'eui-icon-flag',
    elementClass: EuiIconFlagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFlagEvents,
    defineCustomElement: defineEuiIconFlag
});
