'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChatBubbleOvalLeftEllipsis as EuiIconChatBubbleOvalLeftEllipsisElement, defineCustomElement as defineEuiIconChatBubbleOvalLeftEllipsis } from "ensemble-ui/dist/components/eui-icon-chat-bubble-oval-left-ellipsis.js";
import React from 'react';

export type EuiIconChatBubbleOvalLeftEllipsisEvents = NonNullable<unknown>;

export const EuiIconChatBubbleOvalLeftEllipsis: StencilReactComponent<EuiIconChatBubbleOvalLeftEllipsisElement, EuiIconChatBubbleOvalLeftEllipsisEvents> = /*@__PURE__*/ createComponent<EuiIconChatBubbleOvalLeftEllipsisElement, EuiIconChatBubbleOvalLeftEllipsisEvents>({
    tagName: 'eui-icon-chat-bubble-oval-left-ellipsis',
    elementClass: EuiIconChatBubbleOvalLeftEllipsisElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChatBubbleOvalLeftEllipsisEvents,
    defineCustomElement: defineEuiIconChatBubbleOvalLeftEllipsis
});
