'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "ensemble-ui/dist/components";
import { EuiKnob as EuiKnobElement, defineCustomElement as defineEuiKnob } from "ensemble-ui/dist/components/eui-knob.js";

export type EuiKnobEvents = NonNullable<unknown>;

export const EuiKnob: StencilReactComponent<EuiKnobElement, EuiKnobEvents, Components.EuiKnob> = /*@__PURE__*/ createComponent<EuiKnobElement, EuiKnobEvents, Components.EuiKnob>({
    tagName: 'eui-knob',
    elementClass: EuiKnobElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiKnobEvents,
    defineCustomElement: defineEuiKnob
});
