'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiToggleCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiToggle as EuiToggleElement, defineCustomElement as defineEuiToggle } from "ensemble-ui/dist/components/eui-toggle.js";

export type EuiToggleEvents = { onValueChanged: EventName<EuiToggleCustomEvent<number>> };

export const EuiToggle: StencilReactComponent<EuiToggleElement, EuiToggleEvents, Components.EuiToggle> = /*@__PURE__*/ createComponent<EuiToggleElement, EuiToggleEvents, Components.EuiToggle>({
    tagName: 'eui-toggle',
    elementClass: EuiToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChanged: 'valueChanged' } as EuiToggleEvents,
    defineCustomElement: defineEuiToggle
});
