'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowRight as EuiIconArrowRightElement, defineCustomElement as defineEuiIconArrowRight } from "ensemble-ui/dist/components/eui-icon-arrow-right.js";
import React from 'react';

export type EuiIconArrowRightEvents = NonNullable<unknown>;

export const EuiIconArrowRight: StencilReactComponent<EuiIconArrowRightElement, EuiIconArrowRightEvents> = /*@__PURE__*/ createComponent<EuiIconArrowRightElement, EuiIconArrowRightEvents>({
    tagName: 'eui-icon-arrow-right',
    elementClass: EuiIconArrowRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowRightEvents,
    defineCustomElement: defineEuiIconArrowRight
});
