'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUpLeft as EuiIconArrowUpLeftElement, defineCustomElement as defineEuiIconArrowUpLeft } from "ensemble-ui/dist/components/eui-icon-arrow-up-left.js";
import React from 'react';

export type EuiIconArrowUpLeftEvents = NonNullable<unknown>;

export const EuiIconArrowUpLeft: StencilReactComponent<EuiIconArrowUpLeftElement, EuiIconArrowUpLeftEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUpLeftElement, EuiIconArrowUpLeftEvents>({
    tagName: 'eui-icon-arrow-up-left',
    elementClass: EuiIconArrowUpLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUpLeftEvents,
    defineCustomElement: defineEuiIconArrowUpLeft
});
