'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCurrencyYen as EuiIconCurrencyYenElement, defineCustomElement as defineEuiIconCurrencyYen } from "ensemble-ui/dist/components/eui-icon-currency-yen.js";
import React from 'react';

export type EuiIconCurrencyYenEvents = NonNullable<unknown>;

export const EuiIconCurrencyYen: StencilReactComponent<EuiIconCurrencyYenElement, EuiIconCurrencyYenEvents> = /*@__PURE__*/ createComponent<EuiIconCurrencyYenElement, EuiIconCurrencyYenEvents>({
    tagName: 'eui-icon-currency-yen',
    elementClass: EuiIconCurrencyYenElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCurrencyYenEvents,
    defineCustomElement: defineEuiIconCurrencyYen
});
