'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconWindow as EuiIconWindowElement, defineCustomElement as defineEuiIconWindow } from "ensemble-ui/dist/components/eui-icon-window.js";
import React from 'react';

export type EuiIconWindowEvents = NonNullable<unknown>;

export const EuiIconWindow: StencilReactComponent<EuiIconWindowElement, EuiIconWindowEvents> = /*@__PURE__*/ createComponent<EuiIconWindowElement, EuiIconWindowEvents>({
    tagName: 'eui-icon-window',
    elementClass: EuiIconWindowElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconWindowEvents,
    defineCustomElement: defineEuiIconWindow
});
