'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "ensemble-ui/dist/components";
import { EuiIcon as EuiIconElement, defineCustomElement as defineEuiIcon } from "ensemble-ui/dist/components/eui-icon.js";

export type EuiIconEvents = NonNullable<unknown>;

export const EuiIcon: StencilReactComponent<EuiIconElement, EuiIconEvents, Components.EuiIcon> = /*@__PURE__*/ createComponent<EuiIconElement, EuiIconEvents, Components.EuiIcon>({
    tagName: 'eui-icon',
    elementClass: EuiIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEvents,
    defineCustomElement: defineEuiIcon
});
