'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconShoppingCart as EuiIconShoppingCartElement, defineCustomElement as defineEuiIconShoppingCart } from "ensemble-ui/dist/components/eui-icon-shopping-cart.js";
import React from 'react';

export type EuiIconShoppingCartEvents = NonNullable<unknown>;

export const EuiIconShoppingCart: StencilReactComponent<EuiIconShoppingCartElement, EuiIconShoppingCartEvents> = /*@__PURE__*/ createComponent<EuiIconShoppingCartElement, EuiIconShoppingCartEvents>({
    tagName: 'eui-icon-shopping-cart',
    elementClass: EuiIconShoppingCartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconShoppingCartEvents,
    defineCustomElement: defineEuiIconShoppingCart
});
