'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconLockOpen as EuiIconLockOpenElement, defineCustomElement as defineEuiIconLockOpen } from "ensemble-ui/dist/components/eui-icon-lock-open.js";
import React from 'react';

export type EuiIconLockOpenEvents = NonNullable<unknown>;

export const EuiIconLockOpen: StencilReactComponent<EuiIconLockOpenElement, EuiIconLockOpenEvents> = /*@__PURE__*/ createComponent<EuiIconLockOpenElement, EuiIconLockOpenEvents>({
    tagName: 'eui-icon-lock-open',
    elementClass: EuiIconLockOpenElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconLockOpenEvents,
    defineCustomElement: defineEuiIconLockOpen
});
