'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSquare2Stack as EuiIconSquare2StackElement, defineCustomElement as defineEuiIconSquare2Stack } from "ensemble-ui/dist/components/eui-icon-square-2-stack.js";
import React from 'react';

export type EuiIconSquare2StackEvents = NonNullable<unknown>;

export const EuiIconSquare2Stack: StencilReactComponent<EuiIconSquare2StackElement, EuiIconSquare2StackEvents> = /*@__PURE__*/ createComponent<EuiIconSquare2StackElement, EuiIconSquare2StackEvents>({
    tagName: 'eui-icon-square-2-stack',
    elementClass: EuiIconSquare2StackElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSquare2StackEvents,
    defineCustomElement: defineEuiIconSquare2Stack
});
