'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFolderArrowDown as EuiIconFolderArrowDownElement, defineCustomElement as defineEuiIconFolderArrowDown } from "ensemble-ui/dist/components/eui-icon-folder-arrow-down.js";
import React from 'react';

export type EuiIconFolderArrowDownEvents = NonNullable<unknown>;

export const EuiIconFolderArrowDown: StencilReactComponent<EuiIconFolderArrowDownElement, EuiIconFolderArrowDownEvents> = /*@__PURE__*/ createComponent<EuiIconFolderArrowDownElement, EuiIconFolderArrowDownEvents>({
    tagName: 'eui-icon-folder-arrow-down',
    elementClass: EuiIconFolderArrowDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFolderArrowDownEvents,
    defineCustomElement: defineEuiIconFolderArrowDown
});
