'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconVideoCamera as EuiIconVideoCameraElement, defineCustomElement as defineEuiIconVideoCamera } from "ensemble-ui/dist/components/eui-icon-video-camera.js";
import React from 'react';

export type EuiIconVideoCameraEvents = NonNullable<unknown>;

export const EuiIconVideoCamera: StencilReactComponent<EuiIconVideoCameraElement, EuiIconVideoCameraEvents> = /*@__PURE__*/ createComponent<EuiIconVideoCameraElement, EuiIconVideoCameraEvents>({
    tagName: 'eui-icon-video-camera',
    elementClass: EuiIconVideoCameraElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconVideoCameraEvents,
    defineCustomElement: defineEuiIconVideoCamera
});
