'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconServer as EuiIconServerElement, defineCustomElement as defineEuiIconServer } from "ensemble-ui/dist/components/eui-icon-server.js";
import React from 'react';

export type EuiIconServerEvents = NonNullable<unknown>;

export const EuiIconServer: StencilReactComponent<EuiIconServerElement, EuiIconServerEvents> = /*@__PURE__*/ createComponent<EuiIconServerElement, EuiIconServerEvents>({
    tagName: 'eui-icon-server',
    elementClass: EuiIconServerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconServerEvents,
    defineCustomElement: defineEuiIconServer
});
