'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPaperAirplane as EuiIconPaperAirplaneElement, defineCustomElement as defineEuiIconPaperAirplane } from "ensemble-ui/dist/components/eui-icon-paper-airplane.js";
import React from 'react';

export type EuiIconPaperAirplaneEvents = NonNullable<unknown>;

export const EuiIconPaperAirplane: StencilReactComponent<EuiIconPaperAirplaneElement, EuiIconPaperAirplaneEvents> = /*@__PURE__*/ createComponent<EuiIconPaperAirplaneElement, EuiIconPaperAirplaneEvents>({
    tagName: 'eui-icon-paper-airplane',
    elementClass: EuiIconPaperAirplaneElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPaperAirplaneEvents,
    defineCustomElement: defineEuiIconPaperAirplane
});
