'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiToggle as EuiToggleElement, defineCustomElement as defineEuiToggle } from "ensemble-ui/dist/components/eui-toggle.js";
import React from 'react';

export type EuiToggleEvents = { onValueChanged: EventName<CustomEvent<number>> };

export const EuiToggle: StencilReactComponent<EuiToggleElement, EuiToggleEvents> = /*@__PURE__*/ createComponent<EuiToggleElement, EuiToggleEvents>({
    tagName: 'eui-toggle',
    elementClass: EuiToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChanged: 'valueChanged' } as EuiToggleEvents,
    defineCustomElement: defineEuiToggle
});
