'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBookmarkSlash as EuiIconBookmarkSlashElement, defineCustomElement as defineEuiIconBookmarkSlash } from "ensemble-ui/dist/components/eui-icon-bookmark-slash.js";
import React from 'react';

export type EuiIconBookmarkSlashEvents = NonNullable<unknown>;

export const EuiIconBookmarkSlash: StencilReactComponent<EuiIconBookmarkSlashElement, EuiIconBookmarkSlashEvents> = /*@__PURE__*/ createComponent<EuiIconBookmarkSlashElement, EuiIconBookmarkSlashEvents>({
    tagName: 'eui-icon-bookmark-slash',
    elementClass: EuiIconBookmarkSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBookmarkSlashEvents,
    defineCustomElement: defineEuiIconBookmarkSlash
});
