'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconGlobeAsiaAustralia as EuiIconGlobeAsiaAustraliaElement, defineCustomElement as defineEuiIconGlobeAsiaAustralia } from "ensemble-ui/dist/components/eui-icon-globe-asia-australia.js";
import React from 'react';

export type EuiIconGlobeAsiaAustraliaEvents = NonNullable<unknown>;

export const EuiIconGlobeAsiaAustralia: StencilReactComponent<EuiIconGlobeAsiaAustraliaElement, EuiIconGlobeAsiaAustraliaEvents> = /*@__PURE__*/ createComponent<EuiIconGlobeAsiaAustraliaElement, EuiIconGlobeAsiaAustraliaEvents>({
    tagName: 'eui-icon-globe-asia-australia',
    elementClass: EuiIconGlobeAsiaAustraliaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconGlobeAsiaAustraliaEvents,
    defineCustomElement: defineEuiIconGlobeAsiaAustralia
});
