'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconClipboardDocumentCheck as EuiIconClipboardDocumentCheckElement, defineCustomElement as defineEuiIconClipboardDocumentCheck } from "ensemble-ui/dist/components/eui-icon-clipboard-document-check.js";
import React from 'react';

export type EuiIconClipboardDocumentCheckEvents = NonNullable<unknown>;

export const EuiIconClipboardDocumentCheck: StencilReactComponent<EuiIconClipboardDocumentCheckElement, EuiIconClipboardDocumentCheckEvents> = /*@__PURE__*/ createComponent<EuiIconClipboardDocumentCheckElement, EuiIconClipboardDocumentCheckEvents>({
    tagName: 'eui-icon-clipboard-document-check',
    elementClass: EuiIconClipboardDocumentCheckElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconClipboardDocumentCheckEvents,
    defineCustomElement: defineEuiIconClipboardDocumentCheck
});
