'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUturnDown as EuiIconArrowUturnDownElement, defineCustomElement as defineEuiIconArrowUturnDown } from "ensemble-ui/dist/components/eui-icon-arrow-uturn-down.js";
import React from 'react';

export type EuiIconArrowUturnDownEvents = NonNullable<unknown>;

export const EuiIconArrowUturnDown: StencilReactComponent<EuiIconArrowUturnDownElement, EuiIconArrowUturnDownEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUturnDownElement, EuiIconArrowUturnDownEvents>({
    tagName: 'eui-icon-arrow-uturn-down',
    elementClass: EuiIconArrowUturnDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUturnDownEvents,
    defineCustomElement: defineEuiIconArrowUturnDown
});
