'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiRadioGroupCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiRadioGroup as EuiRadioGroupElement, defineCustomElement as defineEuiRadioGroup } from "ensemble-ui/dist/components/eui-radio-group.js";

export type EuiRadioGroupEvents = { onChanged: EventName<EuiRadioGroupCustomEvent<string>> };

export const EuiRadioGroup: StencilReactComponent<EuiRadioGroupElement, EuiRadioGroupEvents, Components.EuiRadioGroup> = /*@__PURE__*/ createComponent<EuiRadioGroupElement, EuiRadioGroupEvents, Components.EuiRadioGroup>({
    tagName: 'eui-radio-group',
    elementClass: EuiRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as EuiRadioGroupEvents,
    defineCustomElement: defineEuiRadioGroup
});
