'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconListBullet as EuiIconListBulletElement, defineCustomElement as defineEuiIconListBullet } from "ensemble-ui/dist/components/eui-icon-list-bullet.js";
import React from 'react';

export type EuiIconListBulletEvents = NonNullable<unknown>;

export const EuiIconListBullet: StencilReactComponent<EuiIconListBulletElement, EuiIconListBulletEvents> = /*@__PURE__*/ createComponent<EuiIconListBulletElement, EuiIconListBulletEvents>({
    tagName: 'eui-icon-list-bullet',
    elementClass: EuiIconListBulletElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconListBulletEvents,
    defineCustomElement: defineEuiIconListBullet
});
