'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBars3BottomLeft as EuiIconBars3BottomLeftElement, defineCustomElement as defineEuiIconBars3BottomLeft } from "ensemble-ui/dist/components/eui-icon-bars-3-bottom-left.js";
import React from 'react';

export type EuiIconBars3BottomLeftEvents = NonNullable<unknown>;

export const EuiIconBars3BottomLeft: StencilReactComponent<EuiIconBars3BottomLeftElement, EuiIconBars3BottomLeftEvents> = /*@__PURE__*/ createComponent<EuiIconBars3BottomLeftElement, EuiIconBars3BottomLeftEvents>({
    tagName: 'eui-icon-bars-3-bottom-left',
    elementClass: EuiIconBars3BottomLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBars3BottomLeftEvents,
    defineCustomElement: defineEuiIconBars3BottomLeft
});
