'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBellAlert as EuiIconBellAlertElement, defineCustomElement as defineEuiIconBellAlert } from "ensemble-ui/dist/components/eui-icon-bell-alert.js";
import React from 'react';

export type EuiIconBellAlertEvents = NonNullable<unknown>;

export const EuiIconBellAlert: StencilReactComponent<EuiIconBellAlertElement, EuiIconBellAlertEvents> = /*@__PURE__*/ createComponent<EuiIconBellAlertElement, EuiIconBellAlertEvents>({
    tagName: 'eui-icon-bell-alert',
    elementClass: EuiIconBellAlertElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBellAlertEvents,
    defineCustomElement: defineEuiIconBellAlert
});
