'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconClipboardDocumentList as EuiIconClipboardDocumentListElement, defineCustomElement as defineEuiIconClipboardDocumentList } from "ensemble-ui/dist/components/eui-icon-clipboard-document-list.js";
import React from 'react';

export type EuiIconClipboardDocumentListEvents = NonNullable<unknown>;

export const EuiIconClipboardDocumentList: StencilReactComponent<EuiIconClipboardDocumentListElement, EuiIconClipboardDocumentListEvents> = /*@__PURE__*/ createComponent<EuiIconClipboardDocumentListElement, EuiIconClipboardDocumentListEvents>({
    tagName: 'eui-icon-clipboard-document-list',
    elementClass: EuiIconClipboardDocumentListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconClipboardDocumentListEvents,
    defineCustomElement: defineEuiIconClipboardDocumentList
});
