'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowsRightLeft as EuiIconArrowsRightLeftElement, defineCustomElement as defineEuiIconArrowsRightLeft } from "ensemble-ui/dist/components/eui-icon-arrows-right-left.js";
import React from 'react';

export type EuiIconArrowsRightLeftEvents = NonNullable<unknown>;

export const EuiIconArrowsRightLeft: StencilReactComponent<EuiIconArrowsRightLeftElement, EuiIconArrowsRightLeftEvents> = /*@__PURE__*/ createComponent<EuiIconArrowsRightLeftElement, EuiIconArrowsRightLeftEvents>({
    tagName: 'eui-icon-arrows-right-left',
    elementClass: EuiIconArrowsRightLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowsRightLeftEvents,
    defineCustomElement: defineEuiIconArrowsRightLeft
});
