'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTurnLeftDown as EuiIconArrowTurnLeftDownElement, defineCustomElement as defineEuiIconArrowTurnLeftDown } from "ensemble-ui/dist/components/eui-icon-arrow-turn-left-down.js";
import React from 'react';

export type EuiIconArrowTurnLeftDownEvents = NonNullable<unknown>;

export const EuiIconArrowTurnLeftDown: StencilReactComponent<EuiIconArrowTurnLeftDownElement, EuiIconArrowTurnLeftDownEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTurnLeftDownElement, EuiIconArrowTurnLeftDownEvents>({
    tagName: 'eui-icon-arrow-turn-left-down',
    elementClass: EuiIconArrowTurnLeftDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTurnLeftDownEvents,
    defineCustomElement: defineEuiIconArrowTurnLeftDown
});
