'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPlay as EuiIconPlayElement, defineCustomElement as defineEuiIconPlay } from "ensemble-ui/dist/components/eui-icon-play.js";
import React from 'react';

export type EuiIconPlayEvents = NonNullable<unknown>;

export const EuiIconPlay: StencilReactComponent<EuiIconPlayElement, EuiIconPlayEvents> = /*@__PURE__*/ createComponent<EuiIconPlayElement, EuiIconPlayEvents>({
    tagName: 'eui-icon-play',
    elementClass: EuiIconPlayElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPlayEvents,
    defineCustomElement: defineEuiIconPlay
});
