'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentDuplicate as EuiIconDocumentDuplicateElement, defineCustomElement as defineEuiIconDocumentDuplicate } from "ensemble-ui/dist/components/eui-icon-document-duplicate.js";
import React from 'react';

export type EuiIconDocumentDuplicateEvents = NonNullable<unknown>;

export const EuiIconDocumentDuplicate: StencilReactComponent<EuiIconDocumentDuplicateElement, EuiIconDocumentDuplicateEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentDuplicateElement, EuiIconDocumentDuplicateEvents>({
    tagName: 'eui-icon-document-duplicate',
    elementClass: EuiIconDocumentDuplicateElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentDuplicateEvents,
    defineCustomElement: defineEuiIconDocumentDuplicate
});
