'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentCheck as EuiIconDocumentCheckElement, defineCustomElement as defineEuiIconDocumentCheck } from "ensemble-ui/dist/components/eui-icon-document-check.js";
import React from 'react';

export type EuiIconDocumentCheckEvents = NonNullable<unknown>;

export const EuiIconDocumentCheck: StencilReactComponent<EuiIconDocumentCheckElement, EuiIconDocumentCheckEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentCheckElement, EuiIconDocumentCheckEvents>({
    tagName: 'eui-icon-document-check',
    elementClass: EuiIconDocumentCheckElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentCheckEvents,
    defineCustomElement: defineEuiIconDocumentCheck
});
