'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPlayCircle as EuiIconPlayCircleElement, defineCustomElement as defineEuiIconPlayCircle } from "ensemble-ui/dist/components/eui-icon-play-circle.js";
import React from 'react';

export type EuiIconPlayCircleEvents = NonNullable<unknown>;

export const EuiIconPlayCircle: StencilReactComponent<EuiIconPlayCircleElement, EuiIconPlayCircleEvents> = /*@__PURE__*/ createComponent<EuiIconPlayCircleElement, EuiIconPlayCircleEvents>({
    tagName: 'eui-icon-play-circle',
    elementClass: EuiIconPlayCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPlayCircleEvents,
    defineCustomElement: defineEuiIconPlayCircle
});
