'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconEyeDropper as EuiIconEyeDropperElement, defineCustomElement as defineEuiIconEyeDropper } from "ensemble-ui/dist/components/eui-icon-eye-dropper.js";
import React from 'react';

export type EuiIconEyeDropperEvents = NonNullable<unknown>;

export const EuiIconEyeDropper: StencilReactComponent<EuiIconEyeDropperElement, EuiIconEyeDropperEvents> = /*@__PURE__*/ createComponent<EuiIconEyeDropperElement, EuiIconEyeDropperEvents>({
    tagName: 'eui-icon-eye-dropper',
    elementClass: EuiIconEyeDropperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEyeDropperEvents,
    defineCustomElement: defineEuiIconEyeDropper
});
