'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCamera as EuiIconCameraElement, defineCustomElement as defineEuiIconCamera } from "ensemble-ui/dist/components/eui-icon-camera.js";
import React from 'react';

export type EuiIconCameraEvents = NonNullable<unknown>;

export const EuiIconCamera: StencilReactComponent<EuiIconCameraElement, EuiIconCameraEvents> = /*@__PURE__*/ createComponent<EuiIconCameraElement, EuiIconCameraEvents>({
    tagName: 'eui-icon-camera',
    elementClass: EuiIconCameraElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCameraEvents,
    defineCustomElement: defineEuiIconCamera
});
