'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiDialogue as EuiDialogueElement, defineCustomElement as defineEuiDialogue } from "ensemble-ui/dist/components/eui-dialogue.js";
import React from 'react';

export type EuiDialogueEvents = NonNullable<unknown>;

export const EuiDialogue: StencilReactComponent<EuiDialogueElement, EuiDialogueEvents> = /*@__PURE__*/ createComponent<EuiDialogueElement, EuiDialogueEvents>({
    tagName: 'eui-dialogue',
    elementClass: EuiDialogueElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiDialogueEvents,
    defineCustomElement: defineEuiDialogue
});
