'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconEnvelope as EuiIconEnvelopeElement, defineCustomElement as defineEuiIconEnvelope } from "ensemble-ui/dist/components/eui-icon-envelope.js";
import React from 'react';

export type EuiIconEnvelopeEvents = NonNullable<unknown>;

export const EuiIconEnvelope: StencilReactComponent<EuiIconEnvelopeElement, EuiIconEnvelopeEvents> = /*@__PURE__*/ createComponent<EuiIconEnvelopeElement, EuiIconEnvelopeEvents>({
    tagName: 'eui-icon-envelope',
    elementClass: EuiIconEnvelopeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEnvelopeEvents,
    defineCustomElement: defineEuiIconEnvelope
});
