'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentChartBar as EuiIconDocumentChartBarElement, defineCustomElement as defineEuiIconDocumentChartBar } from "ensemble-ui/dist/components/eui-icon-document-chart-bar.js";
import React from 'react';

export type EuiIconDocumentChartBarEvents = NonNullable<unknown>;

export const EuiIconDocumentChartBar: StencilReactComponent<EuiIconDocumentChartBarElement, EuiIconDocumentChartBarEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentChartBarElement, EuiIconDocumentChartBarEvents>({
    tagName: 'eui-icon-document-chart-bar',
    elementClass: EuiIconDocumentChartBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentChartBarEvents,
    defineCustomElement: defineEuiIconDocumentChartBar
});
