'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconHandThumbDown as EuiIconHandThumbDownElement, defineCustomElement as defineEuiIconHandThumbDown } from "ensemble-ui/dist/components/eui-icon-hand-thumb-down.js";
import React from 'react';

export type EuiIconHandThumbDownEvents = NonNullable<unknown>;

export const EuiIconHandThumbDown: StencilReactComponent<EuiIconHandThumbDownElement, EuiIconHandThumbDownEvents> = /*@__PURE__*/ createComponent<EuiIconHandThumbDownElement, EuiIconHandThumbDownEvents>({
    tagName: 'eui-icon-hand-thumb-down',
    elementClass: EuiIconHandThumbDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconHandThumbDownEvents,
    defineCustomElement: defineEuiIconHandThumbDown
});
