'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconEllipsisHorizontalCircle as EuiIconEllipsisHorizontalCircleElement, defineCustomElement as defineEuiIconEllipsisHorizontalCircle } from "ensemble-ui/dist/components/eui-icon-ellipsis-horizontal-circle.js";
import React from 'react';

export type EuiIconEllipsisHorizontalCircleEvents = NonNullable<unknown>;

export const EuiIconEllipsisHorizontalCircle: StencilReactComponent<EuiIconEllipsisHorizontalCircleElement, EuiIconEllipsisHorizontalCircleEvents> = /*@__PURE__*/ createComponent<EuiIconEllipsisHorizontalCircleElement, EuiIconEllipsisHorizontalCircleEvents>({
    tagName: 'eui-icon-ellipsis-horizontal-circle',
    elementClass: EuiIconEllipsisHorizontalCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEllipsisHorizontalCircleEvents,
    defineCustomElement: defineEuiIconEllipsisHorizontalCircle
});
