'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconGif as EuiIconGifElement, defineCustomElement as defineEuiIconGif } from "ensemble-ui/dist/components/eui-icon-gif.js";
import React from 'react';

export type EuiIconGifEvents = NonNullable<unknown>;

export const EuiIconGif: StencilReactComponent<EuiIconGifElement, EuiIconGifEvents> = /*@__PURE__*/ createComponent<EuiIconGifElement, EuiIconGifEvents>({
    tagName: 'eui-icon-gif',
    elementClass: EuiIconGifElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconGifEvents,
    defineCustomElement: defineEuiIconGif
});
