'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type EuiCalendarCustomEvent } from "ensemble-ui";
import { EuiCalendar as EuiCalendarElement, defineCustomElement as defineEuiCalendar } from "ensemble-ui/dist/components/eui-calendar.js";
import React from 'react';

export type EuiCalendarEvents = { onDayClick: EventName<EuiCalendarCustomEvent<Date>> };

export const EuiCalendar: StencilReactComponent<EuiCalendarElement, EuiCalendarEvents> = /*@__PURE__*/ createComponent<EuiCalendarElement, EuiCalendarEvents>({
    tagName: 'eui-calendar',
    elementClass: EuiCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDayClick: 'dayClick' } as EuiCalendarEvents,
    defineCustomElement: defineEuiCalendar
});
