'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCog8Tooth as EuiIconCog8ToothElement, defineCustomElement as defineEuiIconCog8Tooth } from "ensemble-ui/dist/components/eui-icon-cog-8-tooth.js";
import React from 'react';

export type EuiIconCog8ToothEvents = NonNullable<unknown>;

export const EuiIconCog8Tooth: StencilReactComponent<EuiIconCog8ToothElement, EuiIconCog8ToothEvents> = /*@__PURE__*/ createComponent<EuiIconCog8ToothElement, EuiIconCog8ToothEvents>({
    tagName: 'eui-icon-cog-8-tooth',
    elementClass: EuiIconCog8ToothElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCog8ToothEvents,
    defineCustomElement: defineEuiIconCog8Tooth
});
