'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowDownCircle as EuiIconArrowDownCircleElement, defineCustomElement as defineEuiIconArrowDownCircle } from "ensemble-ui/dist/components/eui-icon-arrow-down-circle.js";
import React from 'react';

export type EuiIconArrowDownCircleEvents = NonNullable<unknown>;

export const EuiIconArrowDownCircle: StencilReactComponent<EuiIconArrowDownCircleElement, EuiIconArrowDownCircleEvents> = /*@__PURE__*/ createComponent<EuiIconArrowDownCircleElement, EuiIconArrowDownCircleEvents>({
    tagName: 'eui-icon-arrow-down-circle',
    elementClass: EuiIconArrowDownCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowDownCircleEvents,
    defineCustomElement: defineEuiIconArrowDownCircle
});
