'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCloudArrowDown as EuiIconCloudArrowDownElement, defineCustomElement as defineEuiIconCloudArrowDown } from "ensemble-ui/dist/components/eui-icon-cloud-arrow-down.js";
import React from 'react';

export type EuiIconCloudArrowDownEvents = NonNullable<unknown>;

export const EuiIconCloudArrowDown: StencilReactComponent<EuiIconCloudArrowDownElement, EuiIconCloudArrowDownEvents> = /*@__PURE__*/ createComponent<EuiIconCloudArrowDownElement, EuiIconCloudArrowDownEvents>({
    tagName: 'eui-icon-cloud-arrow-down',
    elementClass: EuiIconCloudArrowDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCloudArrowDownEvents,
    defineCustomElement: defineEuiIconCloudArrowDown
});
