'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconTv as EuiIconTvElement, defineCustomElement as defineEuiIconTv } from "ensemble-ui/dist/components/eui-icon-tv.js";
import React from 'react';

export type EuiIconTvEvents = NonNullable<unknown>;

export const EuiIconTv: StencilReactComponent<EuiIconTvElement, EuiIconTvEvents> = /*@__PURE__*/ createComponent<EuiIconTvElement, EuiIconTvEvents>({
    tagName: 'eui-icon-tv',
    elementClass: EuiIconTvElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconTvEvents,
    defineCustomElement: defineEuiIconTv
});
