'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconReceiptRefund as EuiIconReceiptRefundElement, defineCustomElement as defineEuiIconReceiptRefund } from "ensemble-ui/dist/components/eui-icon-receipt-refund.js";
import React from 'react';

export type EuiIconReceiptRefundEvents = NonNullable<unknown>;

export const EuiIconReceiptRefund: StencilReactComponent<EuiIconReceiptRefundElement, EuiIconReceiptRefundEvents> = /*@__PURE__*/ createComponent<EuiIconReceiptRefundElement, EuiIconReceiptRefundEvents>({
    tagName: 'eui-icon-receipt-refund',
    elementClass: EuiIconReceiptRefundElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconReceiptRefundEvents,
    defineCustomElement: defineEuiIconReceiptRefund
});
