'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBookmarkSquare as EuiIconBookmarkSquareElement, defineCustomElement as defineEuiIconBookmarkSquare } from "ensemble-ui/dist/components/eui-icon-bookmark-square.js";
import React from 'react';

export type EuiIconBookmarkSquareEvents = NonNullable<unknown>;

export const EuiIconBookmarkSquare: StencilReactComponent<EuiIconBookmarkSquareElement, EuiIconBookmarkSquareEvents> = /*@__PURE__*/ createComponent<EuiIconBookmarkSquareElement, EuiIconBookmarkSquareEvents>({
    tagName: 'eui-icon-bookmark-square',
    elementClass: EuiIconBookmarkSquareElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBookmarkSquareEvents,
    defineCustomElement: defineEuiIconBookmarkSquare
});
