'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSpeakerXMark as EuiIconSpeakerXMarkElement, defineCustomElement as defineEuiIconSpeakerXMark } from "ensemble-ui/dist/components/eui-icon-speaker-x-mark.js";
import React from 'react';

export type EuiIconSpeakerXMarkEvents = NonNullable<unknown>;

export const EuiIconSpeakerXMark: StencilReactComponent<EuiIconSpeakerXMarkElement, EuiIconSpeakerXMarkEvents> = /*@__PURE__*/ createComponent<EuiIconSpeakerXMarkElement, EuiIconSpeakerXMarkEvents>({
    tagName: 'eui-icon-speaker-x-mark',
    elementClass: EuiIconSpeakerXMarkElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSpeakerXMarkEvents,
    defineCustomElement: defineEuiIconSpeakerXMark
});
