'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPercentBadge as EuiIconPercentBadgeElement, defineCustomElement as defineEuiIconPercentBadge } from "ensemble-ui/dist/components/eui-icon-percent-badge.js";
import React from 'react';

export type EuiIconPercentBadgeEvents = NonNullable<unknown>;

export const EuiIconPercentBadge: StencilReactComponent<EuiIconPercentBadgeElement, EuiIconPercentBadgeEvents> = /*@__PURE__*/ createComponent<EuiIconPercentBadgeElement, EuiIconPercentBadgeEvents>({
    tagName: 'eui-icon-percent-badge',
    elementClass: EuiIconPercentBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPercentBadgeEvents,
    defineCustomElement: defineEuiIconPercentBadge
});
