'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconClock as EuiIconClockElement, defineCustomElement as defineEuiIconClock } from "ensemble-ui/dist/components/eui-icon-clock.js";
import React from 'react';

export type EuiIconClockEvents = NonNullable<unknown>;

export const EuiIconClock: StencilReactComponent<EuiIconClockElement, EuiIconClockEvents> = /*@__PURE__*/ createComponent<EuiIconClockElement, EuiIconClockEvents>({
    tagName: 'eui-icon-clock',
    elementClass: EuiIconClockElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconClockEvents,
    defineCustomElement: defineEuiIconClock
});
