'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowLongDown as EuiIconArrowLongDownElement, defineCustomElement as defineEuiIconArrowLongDown } from "ensemble-ui/dist/components/eui-icon-arrow-long-down.js";
import React from 'react';

export type EuiIconArrowLongDownEvents = NonNullable<unknown>;

export const EuiIconArrowLongDown: StencilReactComponent<EuiIconArrowLongDownElement, EuiIconArrowLongDownEvents> = /*@__PURE__*/ createComponent<EuiIconArrowLongDownElement, EuiIconArrowLongDownEvents>({
    tagName: 'eui-icon-arrow-long-down',
    elementClass: EuiIconArrowLongDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowLongDownEvents,
    defineCustomElement: defineEuiIconArrowLongDown
});
