'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconXMark as EuiIconXMarkElement, defineCustomElement as defineEuiIconXMark } from "ensemble-ui/dist/components/eui-icon-x-mark.js";
import React from 'react';

export type EuiIconXMarkEvents = NonNullable<unknown>;

export const EuiIconXMark: StencilReactComponent<EuiIconXMarkElement, EuiIconXMarkEvents> = /*@__PURE__*/ createComponent<EuiIconXMarkElement, EuiIconXMarkEvents>({
    tagName: 'eui-icon-x-mark',
    elementClass: EuiIconXMarkElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconXMarkEvents,
    defineCustomElement: defineEuiIconXMark
});
