'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconShare as EuiIconShareElement, defineCustomElement as defineEuiIconShare } from "ensemble-ui/dist/components/eui-icon-share.js";
import React from 'react';

export type EuiIconShareEvents = NonNullable<unknown>;

export const EuiIconShare: StencilReactComponent<EuiIconShareElement, EuiIconShareEvents> = /*@__PURE__*/ createComponent<EuiIconShareElement, EuiIconShareEvents>({
    tagName: 'eui-icon-share',
    elementClass: EuiIconShareElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconShareEvents,
    defineCustomElement: defineEuiIconShare
});
