'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowsPointingOut as EuiIconArrowsPointingOutElement, defineCustomElement as defineEuiIconArrowsPointingOut } from "ensemble-ui/dist/components/eui-icon-arrows-pointing-out.js";
import React from 'react';

export type EuiIconArrowsPointingOutEvents = NonNullable<unknown>;

export const EuiIconArrowsPointingOut: StencilReactComponent<EuiIconArrowsPointingOutElement, EuiIconArrowsPointingOutEvents> = /*@__PURE__*/ createComponent<EuiIconArrowsPointingOutElement, EuiIconArrowsPointingOutEvents>({
    tagName: 'eui-icon-arrows-pointing-out',
    elementClass: EuiIconArrowsPointingOutElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowsPointingOutEvents,
    defineCustomElement: defineEuiIconArrowsPointingOut
});
