'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconRectangleStack as EuiIconRectangleStackElement, defineCustomElement as defineEuiIconRectangleStack } from "ensemble-ui/dist/components/eui-icon-rectangle-stack.js";
import React from 'react';

export type EuiIconRectangleStackEvents = NonNullable<unknown>;

export const EuiIconRectangleStack: StencilReactComponent<EuiIconRectangleStackElement, EuiIconRectangleStackEvents> = /*@__PURE__*/ createComponent<EuiIconRectangleStackElement, EuiIconRectangleStackEvents>({
    tagName: 'eui-icon-rectangle-stack',
    elementClass: EuiIconRectangleStackElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconRectangleStackEvents,
    defineCustomElement: defineEuiIconRectangleStack
});
