'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBell as EuiIconBellElement, defineCustomElement as defineEuiIconBell } from "ensemble-ui/dist/components/eui-icon-bell.js";
import React from 'react';

export type EuiIconBellEvents = NonNullable<unknown>;

export const EuiIconBell: StencilReactComponent<EuiIconBellElement, EuiIconBellEvents> = /*@__PURE__*/ createComponent<EuiIconBellElement, EuiIconBellEvents>({
    tagName: 'eui-icon-bell',
    elementClass: EuiIconBellElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBellEvents,
    defineCustomElement: defineEuiIconBell
});
