'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSpeakerWave as EuiIconSpeakerWaveElement, defineCustomElement as defineEuiIconSpeakerWave } from "ensemble-ui/dist/components/eui-icon-speaker-wave.js";
import React from 'react';

export type EuiIconSpeakerWaveEvents = NonNullable<unknown>;

export const EuiIconSpeakerWave: StencilReactComponent<EuiIconSpeakerWaveElement, EuiIconSpeakerWaveEvents> = /*@__PURE__*/ createComponent<EuiIconSpeakerWaveElement, EuiIconSpeakerWaveEvents>({
    tagName: 'eui-icon-speaker-wave',
    elementClass: EuiIconSpeakerWaveElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSpeakerWaveEvents,
    defineCustomElement: defineEuiIconSpeakerWave
});
