'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type EuiYearCardCustomEvent } from "ensemble-ui";
import { EuiYearCard as EuiYearCardElement, defineCustomElement as defineEuiYearCard } from "ensemble-ui/dist/components/eui-year-card.js";
import React from 'react';

export type EuiYearCardEvents = { onDayClick: EventName<EuiYearCardCustomEvent<Date>> };

export const EuiYearCard: StencilReactComponent<EuiYearCardElement, EuiYearCardEvents> = /*@__PURE__*/ createComponent<EuiYearCardElement, EuiYearCardEvents>({
    tagName: 'eui-year-card',
    elementClass: EuiYearCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDayClick: 'dayClick' } as EuiYearCardEvents,
    defineCustomElement: defineEuiYearCard
});
