'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMagnifyingGlassPlus as EuiIconMagnifyingGlassPlusElement, defineCustomElement as defineEuiIconMagnifyingGlassPlus } from "ensemble-ui/dist/components/eui-icon-magnifying-glass-plus.js";
import React from 'react';

export type EuiIconMagnifyingGlassPlusEvents = NonNullable<unknown>;

export const EuiIconMagnifyingGlassPlus: StencilReactComponent<EuiIconMagnifyingGlassPlusElement, EuiIconMagnifyingGlassPlusEvents> = /*@__PURE__*/ createComponent<EuiIconMagnifyingGlassPlusElement, EuiIconMagnifyingGlassPlusEvents>({
    tagName: 'eui-icon-magnifying-glass-plus',
    elementClass: EuiIconMagnifyingGlassPlusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMagnifyingGlassPlusEvents,
    defineCustomElement: defineEuiIconMagnifyingGlassPlus
});
