'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBars3CenterLeft as EuiIconBars3CenterLeftElement, defineCustomElement as defineEuiIconBars3CenterLeft } from "ensemble-ui/dist/components/eui-icon-bars-3-center-left.js";
import React from 'react';

export type EuiIconBars3CenterLeftEvents = NonNullable<unknown>;

export const EuiIconBars3CenterLeft: StencilReactComponent<EuiIconBars3CenterLeftElement, EuiIconBars3CenterLeftEvents> = /*@__PURE__*/ createComponent<EuiIconBars3CenterLeftElement, EuiIconBars3CenterLeftEvents>({
    tagName: 'eui-icon-bars-3-center-left',
    elementClass: EuiIconBars3CenterLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBars3CenterLeftEvents,
    defineCustomElement: defineEuiIconBars3CenterLeft
});
