'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowRightHeavy as EuiIconArrowRightHeavyElement, defineCustomElement as defineEuiIconArrowRightHeavy } from "ensemble-ui/dist/components/eui-icon-arrow-right-heavy.js";
import React from 'react';

export type EuiIconArrowRightHeavyEvents = NonNullable<unknown>;

export const EuiIconArrowRightHeavy: StencilReactComponent<EuiIconArrowRightHeavyElement, EuiIconArrowRightHeavyEvents> = /*@__PURE__*/ createComponent<EuiIconArrowRightHeavyElement, EuiIconArrowRightHeavyEvents>({
    tagName: 'eui-icon-arrow-right-heavy',
    elementClass: EuiIconArrowRightHeavyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowRightHeavyEvents,
    defineCustomElement: defineEuiIconArrowRightHeavy
});
