'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiAutoCompleteCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiAutoComplete as EuiAutoCompleteElement, defineCustomElement as defineEuiAutoComplete } from "ensemble-ui/dist/components/eui-auto-complete.js";

export type EuiAutoCompleteEvents = { onItemSelected: EventName<EuiAutoCompleteCustomEvent<any>> };

export const EuiAutoComplete: StencilReactComponent<EuiAutoCompleteElement, EuiAutoCompleteEvents, Components.EuiAutoComplete> = /*@__PURE__*/ createComponent<EuiAutoCompleteElement, EuiAutoCompleteEvents, Components.EuiAutoComplete>({
    tagName: 'eui-auto-complete',
    elementClass: EuiAutoCompleteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onItemSelected: 'itemSelected' } as EuiAutoCompleteEvents,
    defineCustomElement: defineEuiAutoComplete
});
