'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTrendingDown as EuiIconArrowTrendingDownElement, defineCustomElement as defineEuiIconArrowTrendingDown } from "ensemble-ui/dist/components/eui-icon-arrow-trending-down.js";
import React from 'react';

export type EuiIconArrowTrendingDownEvents = NonNullable<unknown>;

export const EuiIconArrowTrendingDown: StencilReactComponent<EuiIconArrowTrendingDownElement, EuiIconArrowTrendingDownEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTrendingDownElement, EuiIconArrowTrendingDownEvents>({
    tagName: 'eui-icon-arrow-trending-down',
    elementClass: EuiIconArrowTrendingDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTrendingDownEvents,
    defineCustomElement: defineEuiIconArrowTrendingDown
});
