'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCog6Tooth as EuiIconCog6ToothElement, defineCustomElement as defineEuiIconCog6Tooth } from "ensemble-ui/dist/components/eui-icon-cog-6-tooth.js";
import React from 'react';

export type EuiIconCog6ToothEvents = NonNullable<unknown>;

export const EuiIconCog6Tooth: StencilReactComponent<EuiIconCog6ToothElement, EuiIconCog6ToothEvents> = /*@__PURE__*/ createComponent<EuiIconCog6ToothElement, EuiIconCog6ToothEvents>({
    tagName: 'eui-icon-cog-6-tooth',
    elementClass: EuiIconCog6ToothElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCog6ToothEvents,
    defineCustomElement: defineEuiIconCog6Tooth
});
