'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPencil as EuiIconPencilElement, defineCustomElement as defineEuiIconPencil } from "ensemble-ui/dist/components/eui-icon-pencil.js";
import React from 'react';

export type EuiIconPencilEvents = NonNullable<unknown>;

export const EuiIconPencil: StencilReactComponent<EuiIconPencilElement, EuiIconPencilEvents> = /*@__PURE__*/ createComponent<EuiIconPencilElement, EuiIconPencilEvents>({
    tagName: 'eui-icon-pencil',
    elementClass: EuiIconPencilElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPencilEvents,
    defineCustomElement: defineEuiIconPencil
});
