'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChartBarSquare as EuiIconChartBarSquareElement, defineCustomElement as defineEuiIconChartBarSquare } from "ensemble-ui/dist/components/eui-icon-chart-bar-square.js";
import React from 'react';

export type EuiIconChartBarSquareEvents = NonNullable<unknown>;

export const EuiIconChartBarSquare: StencilReactComponent<EuiIconChartBarSquareElement, EuiIconChartBarSquareEvents> = /*@__PURE__*/ createComponent<EuiIconChartBarSquareElement, EuiIconChartBarSquareEvents>({
    tagName: 'eui-icon-chart-bar-square',
    elementClass: EuiIconChartBarSquareElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChartBarSquareEvents,
    defineCustomElement: defineEuiIconChartBarSquare
});
