'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconNewspaper as EuiIconNewspaperElement, defineCustomElement as defineEuiIconNewspaper } from "ensemble-ui/dist/components/eui-icon-newspaper.js";
import React from 'react';

export type EuiIconNewspaperEvents = NonNullable<unknown>;

export const EuiIconNewspaper: StencilReactComponent<EuiIconNewspaperElement, EuiIconNewspaperEvents> = /*@__PURE__*/ createComponent<EuiIconNewspaperElement, EuiIconNewspaperEvents>({
    tagName: 'eui-icon-newspaper',
    elementClass: EuiIconNewspaperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconNewspaperEvents,
    defineCustomElement: defineEuiIconNewspaper
});
