'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconVariable as EuiIconVariableElement, defineCustomElement as defineEuiIconVariable } from "ensemble-ui/dist/components/eui-icon-variable.js";
import React from 'react';

export type EuiIconVariableEvents = NonNullable<unknown>;

export const EuiIconVariable: StencilReactComponent<EuiIconVariableElement, EuiIconVariableEvents> = /*@__PURE__*/ createComponent<EuiIconVariableElement, EuiIconVariableEvents>({
    tagName: 'eui-icon-variable',
    elementClass: EuiIconVariableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconVariableEvents,
    defineCustomElement: defineEuiIconVariable
});
