'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBugAnt as EuiIconBugAntElement, defineCustomElement as defineEuiIconBugAnt } from "ensemble-ui/dist/components/eui-icon-bug-ant.js";
import React from 'react';

export type EuiIconBugAntEvents = NonNullable<unknown>;

export const EuiIconBugAnt: StencilReactComponent<EuiIconBugAntElement, EuiIconBugAntEvents> = /*@__PURE__*/ createComponent<EuiIconBugAntElement, EuiIconBugAntEvents>({
    tagName: 'eui-icon-bug-ant',
    elementClass: EuiIconBugAntElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBugAntEvents,
    defineCustomElement: defineEuiIconBugAnt
});
