'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconRss as EuiIconRssElement, defineCustomElement as defineEuiIconRss } from "ensemble-ui/dist/components/eui-icon-rss.js";
import React from 'react';

export type EuiIconRssEvents = NonNullable<unknown>;

export const EuiIconRss: StencilReactComponent<EuiIconRssElement, EuiIconRssEvents> = /*@__PURE__*/ createComponent<EuiIconRssElement, EuiIconRssEvents>({
    tagName: 'eui-icon-rss',
    elementClass: EuiIconRssElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconRssEvents,
    defineCustomElement: defineEuiIconRss
});
