'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconIdentification as EuiIconIdentificationElement, defineCustomElement as defineEuiIconIdentification } from "ensemble-ui/dist/components/eui-icon-identification.js";
import React from 'react';

export type EuiIconIdentificationEvents = NonNullable<unknown>;

export const EuiIconIdentification: StencilReactComponent<EuiIconIdentificationElement, EuiIconIdentificationEvents> = /*@__PURE__*/ createComponent<EuiIconIdentificationElement, EuiIconIdentificationEvents>({
    tagName: 'eui-icon-identification',
    elementClass: EuiIconIdentificationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconIdentificationEvents,
    defineCustomElement: defineEuiIconIdentification
});
