'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentMagnifyingGlass as EuiIconDocumentMagnifyingGlassElement, defineCustomElement as defineEuiIconDocumentMagnifyingGlass } from "ensemble-ui/dist/components/eui-icon-document-magnifying-glass.js";
import React from 'react';

export type EuiIconDocumentMagnifyingGlassEvents = NonNullable<unknown>;

export const EuiIconDocumentMagnifyingGlass: StencilReactComponent<EuiIconDocumentMagnifyingGlassElement, EuiIconDocumentMagnifyingGlassEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentMagnifyingGlassElement, EuiIconDocumentMagnifyingGlassEvents>({
    tagName: 'eui-icon-document-magnifying-glass',
    elementClass: EuiIconDocumentMagnifyingGlassElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentMagnifyingGlassEvents,
    defineCustomElement: defineEuiIconDocumentMagnifyingGlass
});
