'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiColorPicker as EuiColorPickerElement, defineCustomElement as defineEuiColorPicker } from "ensemble-ui/dist/components/eui-color-picker.js";
import React from 'react';

export type EuiColorPickerEvents = { onChanged: EventName<CustomEvent<string>> };

export const EuiColorPicker: StencilReactComponent<EuiColorPickerElement, EuiColorPickerEvents> = /*@__PURE__*/ createComponent<EuiColorPickerElement, EuiColorPickerEvents>({
    tagName: 'eui-color-picker',
    elementClass: EuiColorPickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as EuiColorPickerEvents,
    defineCustomElement: defineEuiColorPicker
});
