'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChevronUp as EuiIconChevronUpElement, defineCustomElement as defineEuiIconChevronUp } from "ensemble-ui/dist/components/eui-icon-chevron-up.js";
import React from 'react';

export type EuiIconChevronUpEvents = NonNullable<unknown>;

export const EuiIconChevronUp: StencilReactComponent<EuiIconChevronUpElement, EuiIconChevronUpEvents> = /*@__PURE__*/ createComponent<EuiIconChevronUpElement, EuiIconChevronUpEvents>({
    tagName: 'eui-icon-chevron-up',
    elementClass: EuiIconChevronUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChevronUpEvents,
    defineCustomElement: defineEuiIconChevronUp
});
