'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTurnDownRight as EuiIconArrowTurnDownRightElement, defineCustomElement as defineEuiIconArrowTurnDownRight } from "ensemble-ui/dist/components/eui-icon-arrow-turn-down-right.js";
import React from 'react';

export type EuiIconArrowTurnDownRightEvents = NonNullable<unknown>;

export const EuiIconArrowTurnDownRight: StencilReactComponent<EuiIconArrowTurnDownRightElement, EuiIconArrowTurnDownRightEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTurnDownRightElement, EuiIconArrowTurnDownRightEvents>({
    tagName: 'eui-icon-arrow-turn-down-right',
    elementClass: EuiIconArrowTurnDownRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTurnDownRightEvents,
    defineCustomElement: defineEuiIconArrowTurnDownRight
});
