'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiSnackbarCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiSnackbar as EuiSnackbarElement, defineCustomElement as defineEuiSnackbar } from "ensemble-ui/dist/components/eui-snackbar.js";

export type EuiSnackbarEvents = { onDismissing: EventName<EuiSnackbarCustomEvent<void>> };

export const EuiSnackbar: StencilReactComponent<EuiSnackbarElement, EuiSnackbarEvents, Components.EuiSnackbar> = /*@__PURE__*/ createComponent<EuiSnackbarElement, EuiSnackbarEvents, Components.EuiSnackbar>({
    tagName: 'eui-snackbar',
    elementClass: EuiSnackbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDismissing: 'dismissing' } as EuiSnackbarEvents,
    defineCustomElement: defineEuiSnackbar
});
