'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPuzzlePiece as EuiIconPuzzlePieceElement, defineCustomElement as defineEuiIconPuzzlePiece } from "ensemble-ui/dist/components/eui-icon-puzzle-piece.js";
import React from 'react';

export type EuiIconPuzzlePieceEvents = NonNullable<unknown>;

export const EuiIconPuzzlePiece: StencilReactComponent<EuiIconPuzzlePieceElement, EuiIconPuzzlePieceEvents> = /*@__PURE__*/ createComponent<EuiIconPuzzlePieceElement, EuiIconPuzzlePieceEvents>({
    tagName: 'eui-icon-puzzle-piece',
    elementClass: EuiIconPuzzlePieceElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPuzzlePieceEvents,
    defineCustomElement: defineEuiIconPuzzlePiece
});
