'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "ensemble-ui/dist/components";
import { EuiCalendar as EuiCalendarElement, defineCustomElement as defineEuiCalendar } from "ensemble-ui/dist/components/eui-calendar.js";

export type EuiCalendarEvents = NonNullable<unknown>;

export const EuiCalendar: StencilReactComponent<EuiCalendarElement, EuiCalendarEvents, Components.EuiCalendar> = /*@__PURE__*/ createComponent<EuiCalendarElement, EuiCalendarEvents, Components.EuiCalendar>({
    tagName: 'eui-calendar',
    elementClass: EuiCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiCalendarEvents,
    defineCustomElement: defineEuiCalendar
});
