'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocument as EuiIconDocumentElement, defineCustomElement as defineEuiIconDocument } from "ensemble-ui/dist/components/eui-icon-document.js";
import React from 'react';

export type EuiIconDocumentEvents = NonNullable<unknown>;

export const EuiIconDocument: StencilReactComponent<EuiIconDocumentElement, EuiIconDocumentEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentElement, EuiIconDocumentEvents>({
    tagName: 'eui-icon-document',
    elementClass: EuiIconDocumentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentEvents,
    defineCustomElement: defineEuiIconDocument
});
