'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCalendarDays as EuiIconCalendarDaysElement, defineCustomElement as defineEuiIconCalendarDays } from "ensemble-ui/dist/components/eui-icon-calendar-days.js";
import React from 'react';

export type EuiIconCalendarDaysEvents = NonNullable<unknown>;

export const EuiIconCalendarDays: StencilReactComponent<EuiIconCalendarDaysElement, EuiIconCalendarDaysEvents> = /*@__PURE__*/ createComponent<EuiIconCalendarDaysElement, EuiIconCalendarDaysEvents>({
    tagName: 'eui-icon-calendar-days',
    elementClass: EuiIconCalendarDaysElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCalendarDaysEvents,
    defineCustomElement: defineEuiIconCalendarDays
});
