'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMusicalNote as EuiIconMusicalNoteElement, defineCustomElement as defineEuiIconMusicalNote } from "ensemble-ui/dist/components/eui-icon-musical-note.js";
import React from 'react';

export type EuiIconMusicalNoteEvents = NonNullable<unknown>;

export const EuiIconMusicalNote: StencilReactComponent<EuiIconMusicalNoteElement, EuiIconMusicalNoteEvents> = /*@__PURE__*/ createComponent<EuiIconMusicalNoteElement, EuiIconMusicalNoteEvents>({
    tagName: 'eui-icon-musical-note',
    elementClass: EuiIconMusicalNoteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMusicalNoteEvents,
    defineCustomElement: defineEuiIconMusicalNote
});
