'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconReceiptPercent as EuiIconReceiptPercentElement, defineCustomElement as defineEuiIconReceiptPercent } from "ensemble-ui/dist/components/eui-icon-receipt-percent.js";
import React from 'react';

export type EuiIconReceiptPercentEvents = NonNullable<unknown>;

export const EuiIconReceiptPercent: StencilReactComponent<EuiIconReceiptPercentElement, EuiIconReceiptPercentEvents> = /*@__PURE__*/ createComponent<EuiIconReceiptPercentElement, EuiIconReceiptPercentEvents>({
    tagName: 'eui-icon-receipt-percent',
    elementClass: EuiIconReceiptPercentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconReceiptPercentEvents,
    defineCustomElement: defineEuiIconReceiptPercent
});
