'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFilm as EuiIconFilmElement, defineCustomElement as defineEuiIconFilm } from "ensemble-ui/dist/components/eui-icon-film.js";
import React from 'react';

export type EuiIconFilmEvents = NonNullable<unknown>;

export const EuiIconFilm: StencilReactComponent<EuiIconFilmElement, EuiIconFilmEvents> = /*@__PURE__*/ createComponent<EuiIconFilmElement, EuiIconFilmEvents>({
    tagName: 'eui-icon-film',
    elementClass: EuiIconFilmElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFilmEvents,
    defineCustomElement: defineEuiIconFilm
});
