'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconNumberedList as EuiIconNumberedListElement, defineCustomElement as defineEuiIconNumberedList } from "ensemble-ui/dist/components/eui-icon-numbered-list.js";
import React from 'react';

export type EuiIconNumberedListEvents = NonNullable<unknown>;

export const EuiIconNumberedList: StencilReactComponent<EuiIconNumberedListElement, EuiIconNumberedListEvents> = /*@__PURE__*/ createComponent<EuiIconNumberedListElement, EuiIconNumberedListEvents>({
    tagName: 'eui-icon-numbered-list',
    elementClass: EuiIconNumberedListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconNumberedListEvents,
    defineCustomElement: defineEuiIconNumberedList
});
