'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiCard as EuiCardElement, defineCustomElement as defineEuiCard } from "ensemble-ui/dist/components/eui-card.js";
import React from 'react';

export type EuiCardEvents = NonNullable<unknown>;

export const EuiCard: StencilReactComponent<EuiCardElement, EuiCardEvents> = /*@__PURE__*/ createComponent<EuiCardElement, EuiCardEvents>({
    tagName: 'eui-card',
    elementClass: EuiCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiCardEvents,
    defineCustomElement: defineEuiCard
});
