'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMap as EuiIconMapElement, defineCustomElement as defineEuiIconMap } from "ensemble-ui/dist/components/eui-icon-map.js";
import React from 'react';

export type EuiIconMapEvents = NonNullable<unknown>;

export const EuiIconMap: StencilReactComponent<EuiIconMapElement, EuiIconMapEvents> = /*@__PURE__*/ createComponent<EuiIconMapElement, EuiIconMapEvents>({
    tagName: 'eui-icon-map',
    elementClass: EuiIconMapElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMapEvents,
    defineCustomElement: defineEuiIconMap
});
