'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowLeftCircle as EuiIconArrowLeftCircleElement, defineCustomElement as defineEuiIconArrowLeftCircle } from "ensemble-ui/dist/components/eui-icon-arrow-left-circle.js";
import React from 'react';

export type EuiIconArrowLeftCircleEvents = NonNullable<unknown>;

export const EuiIconArrowLeftCircle: StencilReactComponent<EuiIconArrowLeftCircleElement, EuiIconArrowLeftCircleEvents> = /*@__PURE__*/ createComponent<EuiIconArrowLeftCircleElement, EuiIconArrowLeftCircleEvents>({
    tagName: 'eui-icon-arrow-left-circle',
    elementClass: EuiIconArrowLeftCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowLeftCircleEvents,
    defineCustomElement: defineEuiIconArrowLeftCircle
});
