'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMerge as EuiIconMergeElement, defineCustomElement as defineEuiIconMerge } from "ensemble-ui/dist/components/eui-icon-merge.js";
import React from 'react';

export type EuiIconMergeEvents = NonNullable<unknown>;

export const EuiIconMerge: StencilReactComponent<EuiIconMergeElement, EuiIconMergeEvents> = /*@__PURE__*/ createComponent<EuiIconMergeElement, EuiIconMergeEvents>({
    tagName: 'eui-icon-merge',
    elementClass: EuiIconMergeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMergeEvents,
    defineCustomElement: defineEuiIconMerge
});
