'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSquare2StackOutline as EuiIconSquare2StackOutlineElement, defineCustomElement as defineEuiIconSquare2StackOutline } from "ensemble-ui/dist/components/eui-icon-square-2-stack-outline.js";
import React from 'react';

export type EuiIconSquare2StackOutlineEvents = NonNullable<unknown>;

export const EuiIconSquare2StackOutline: StencilReactComponent<EuiIconSquare2StackOutlineElement, EuiIconSquare2StackOutlineEvents> = /*@__PURE__*/ createComponent<EuiIconSquare2StackOutlineElement, EuiIconSquare2StackOutlineEvents>({
    tagName: 'eui-icon-square-2-stack-outline',
    elementClass: EuiIconSquare2StackOutlineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSquare2StackOutlineEvents,
    defineCustomElement: defineEuiIconSquare2StackOutline
});
