'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChevronDoubleUp as EuiIconChevronDoubleUpElement, defineCustomElement as defineEuiIconChevronDoubleUp } from "ensemble-ui/dist/components/eui-icon-chevron-double-up.js";
import React from 'react';

export type EuiIconChevronDoubleUpEvents = NonNullable<unknown>;

export const EuiIconChevronDoubleUp: StencilReactComponent<EuiIconChevronDoubleUpElement, EuiIconChevronDoubleUpEvents> = /*@__PURE__*/ createComponent<EuiIconChevronDoubleUpElement, EuiIconChevronDoubleUpEvents>({
    tagName: 'eui-icon-chevron-double-up',
    elementClass: EuiIconChevronDoubleUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChevronDoubleUpEvents,
    defineCustomElement: defineEuiIconChevronDoubleUp
});
