'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiDropdownCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiDropdown as EuiDropdownElement, defineCustomElement as defineEuiDropdown } from "ensemble-ui/dist/components/eui-dropdown.js";

export type EuiDropdownEvents = { onItemSelected: EventName<EuiDropdownCustomEvent<any>> };

export const EuiDropdown: StencilReactComponent<EuiDropdownElement, EuiDropdownEvents, Components.EuiDropdown> = /*@__PURE__*/ createComponent<EuiDropdownElement, EuiDropdownEvents, Components.EuiDropdown>({
    tagName: 'eui-dropdown',
    elementClass: EuiDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onItemSelected: 'itemSelected' } as EuiDropdownEvents,
    defineCustomElement: defineEuiDropdown
});
