'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSignalSlash as EuiIconSignalSlashElement, defineCustomElement as defineEuiIconSignalSlash } from "ensemble-ui/dist/components/eui-icon-signal-slash.js";
import React from 'react';

export type EuiIconSignalSlashEvents = NonNullable<unknown>;

export const EuiIconSignalSlash: StencilReactComponent<EuiIconSignalSlashElement, EuiIconSignalSlashEvents> = /*@__PURE__*/ createComponent<EuiIconSignalSlashElement, EuiIconSignalSlashEvents>({
    tagName: 'eui-icon-signal-slash',
    elementClass: EuiIconSignalSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSignalSlashEvents,
    defineCustomElement: defineEuiIconSignalSlash
});
