'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSwatch as EuiIconSwatchElement, defineCustomElement as defineEuiIconSwatch } from "ensemble-ui/dist/components/eui-icon-swatch.js";
import React from 'react';

export type EuiIconSwatchEvents = NonNullable<unknown>;

export const EuiIconSwatch: StencilReactComponent<EuiIconSwatchElement, EuiIconSwatchEvents> = /*@__PURE__*/ createComponent<EuiIconSwatchElement, EuiIconSwatchEvents>({
    tagName: 'eui-icon-swatch',
    elementClass: EuiIconSwatchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSwatchEvents,
    defineCustomElement: defineEuiIconSwatch
});
