'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChatBubbleLeftRight as EuiIconChatBubbleLeftRightElement, defineCustomElement as defineEuiIconChatBubbleLeftRight } from "ensemble-ui/dist/components/eui-icon-chat-bubble-left-right.js";
import React from 'react';

export type EuiIconChatBubbleLeftRightEvents = NonNullable<unknown>;

export const EuiIconChatBubbleLeftRight: StencilReactComponent<EuiIconChatBubbleLeftRightElement, EuiIconChatBubbleLeftRightEvents> = /*@__PURE__*/ createComponent<EuiIconChatBubbleLeftRightElement, EuiIconChatBubbleLeftRightEvents>({
    tagName: 'eui-icon-chat-bubble-left-right',
    elementClass: EuiIconChatBubbleLeftRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChatBubbleLeftRightEvents,
    defineCustomElement: defineEuiIconChatBubbleLeftRight
});
