'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconHashtag as EuiIconHashtagElement, defineCustomElement as defineEuiIconHashtag } from "ensemble-ui/dist/components/eui-icon-hashtag.js";
import React from 'react';

export type EuiIconHashtagEvents = NonNullable<unknown>;

export const EuiIconHashtag: StencilReactComponent<EuiIconHashtagElement, EuiIconHashtagEvents> = /*@__PURE__*/ createComponent<EuiIconHashtagElement, EuiIconHashtagEvents>({
    tagName: 'eui-icon-hashtag',
    elementClass: EuiIconHashtagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconHashtagEvents,
    defineCustomElement: defineEuiIconHashtag
});
