'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTopRightOnSquare as EuiIconArrowTopRightOnSquareElement, defineCustomElement as defineEuiIconArrowTopRightOnSquare } from "ensemble-ui/dist/components/eui-icon-arrow-top-right-on-square.js";
import React from 'react';

export type EuiIconArrowTopRightOnSquareEvents = NonNullable<unknown>;

export const EuiIconArrowTopRightOnSquare: StencilReactComponent<EuiIconArrowTopRightOnSquareElement, EuiIconArrowTopRightOnSquareEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTopRightOnSquareElement, EuiIconArrowTopRightOnSquareEvents>({
    tagName: 'eui-icon-arrow-top-right-on-square',
    elementClass: EuiIconArrowTopRightOnSquareElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTopRightOnSquareEvents,
    defineCustomElement: defineEuiIconArrowTopRightOnSquare
});
