'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconH2 as EuiIconH2Element, defineCustomElement as defineEuiIconH2 } from "ensemble-ui/dist/components/eui-icon-h2.js";
import React from 'react';

export type EuiIconH2Events = NonNullable<unknown>;

export const EuiIconH2: StencilReactComponent<EuiIconH2Element, EuiIconH2Events> = /*@__PURE__*/ createComponent<EuiIconH2Element, EuiIconH2Events>({
    tagName: 'eui-icon-h2',
    elementClass: EuiIconH2Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconH2Events,
    defineCustomElement: defineEuiIconH2
});
