'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconAdjustmentsVertical as EuiIconAdjustmentsVerticalElement, defineCustomElement as defineEuiIconAdjustmentsVertical } from "ensemble-ui/dist/components/eui-icon-adjustments-vertical.js";
import React from 'react';

export type EuiIconAdjustmentsVerticalEvents = NonNullable<unknown>;

export const EuiIconAdjustmentsVertical: StencilReactComponent<EuiIconAdjustmentsVerticalElement, EuiIconAdjustmentsVerticalEvents> = /*@__PURE__*/ createComponent<EuiIconAdjustmentsVerticalElement, EuiIconAdjustmentsVerticalEvents>({
    tagName: 'eui-icon-adjustments-vertical',
    elementClass: EuiIconAdjustmentsVerticalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconAdjustmentsVerticalEvents,
    defineCustomElement: defineEuiIconAdjustmentsVertical
});
