'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowDownLeft as EuiIconArrowDownLeftElement, defineCustomElement as defineEuiIconArrowDownLeft } from "ensemble-ui/dist/components/eui-icon-arrow-down-left.js";
import React from 'react';

export type EuiIconArrowDownLeftEvents = NonNullable<unknown>;

export const EuiIconArrowDownLeft: StencilReactComponent<EuiIconArrowDownLeftElement, EuiIconArrowDownLeftEvents> = /*@__PURE__*/ createComponent<EuiIconArrowDownLeftElement, EuiIconArrowDownLeftEvents>({
    tagName: 'eui-icon-arrow-down-left',
    elementClass: EuiIconArrowDownLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowDownLeftEvents,
    defineCustomElement: defineEuiIconArrowDownLeft
});
