'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCube as EuiIconCubeElement, defineCustomElement as defineEuiIconCube } from "ensemble-ui/dist/components/eui-icon-cube.js";
import React from 'react';

export type EuiIconCubeEvents = NonNullable<unknown>;

export const EuiIconCube: StencilReactComponent<EuiIconCubeElement, EuiIconCubeEvents> = /*@__PURE__*/ createComponent<EuiIconCubeElement, EuiIconCubeEvents>({
    tagName: 'eui-icon-cube',
    elementClass: EuiIconCubeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCubeEvents,
    defineCustomElement: defineEuiIconCube
});
