'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconMagnifyingGlass as EuiIconMagnifyingGlassElement, defineCustomElement as defineEuiIconMagnifyingGlass } from "ensemble-ui/dist/components/eui-icon-magnifying-glass.js";
import React from 'react';

export type EuiIconMagnifyingGlassEvents = NonNullable<unknown>;

export const EuiIconMagnifyingGlass: StencilReactComponent<EuiIconMagnifyingGlassElement, EuiIconMagnifyingGlassEvents> = /*@__PURE__*/ createComponent<EuiIconMagnifyingGlassElement, EuiIconMagnifyingGlassEvents>({
    tagName: 'eui-icon-magnifying-glass',
    elementClass: EuiIconMagnifyingGlassElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconMagnifyingGlassEvents,
    defineCustomElement: defineEuiIconMagnifyingGlass
});
