'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSlash as EuiIconSlashElement, defineCustomElement as defineEuiIconSlash } from "ensemble-ui/dist/components/eui-icon-slash.js";
import React from 'react';

export type EuiIconSlashEvents = NonNullable<unknown>;

export const EuiIconSlash: StencilReactComponent<EuiIconSlashElement, EuiIconSlashEvents> = /*@__PURE__*/ createComponent<EuiIconSlashElement, EuiIconSlashEvents>({
    tagName: 'eui-icon-slash',
    elementClass: EuiIconSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSlashEvents,
    defineCustomElement: defineEuiIconSlash
});
