'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUpTray as EuiIconArrowUpTrayElement, defineCustomElement as defineEuiIconArrowUpTray } from "ensemble-ui/dist/components/eui-icon-arrow-up-tray.js";
import React from 'react';

export type EuiIconArrowUpTrayEvents = NonNullable<unknown>;

export const EuiIconArrowUpTray: StencilReactComponent<EuiIconArrowUpTrayElement, EuiIconArrowUpTrayEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUpTrayElement, EuiIconArrowUpTrayEvents>({
    tagName: 'eui-icon-arrow-up-tray',
    elementClass: EuiIconArrowUpTrayElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUpTrayEvents,
    defineCustomElement: defineEuiIconArrowUpTray
});
