'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconShoppingBag as EuiIconShoppingBagElement, defineCustomElement as defineEuiIconShoppingBag } from "ensemble-ui/dist/components/eui-icon-shopping-bag.js";
import React from 'react';

export type EuiIconShoppingBagEvents = NonNullable<unknown>;

export const EuiIconShoppingBag: StencilReactComponent<EuiIconShoppingBagElement, EuiIconShoppingBagEvents> = /*@__PURE__*/ createComponent<EuiIconShoppingBagElement, EuiIconShoppingBagEvents>({
    tagName: 'eui-icon-shopping-bag',
    elementClass: EuiIconShoppingBagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconShoppingBagEvents,
    defineCustomElement: defineEuiIconShoppingBag
});
