'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUpRight as EuiIconArrowUpRightElement, defineCustomElement as defineEuiIconArrowUpRight } from "ensemble-ui/dist/components/eui-icon-arrow-up-right.js";
import React from 'react';

export type EuiIconArrowUpRightEvents = NonNullable<unknown>;

export const EuiIconArrowUpRight: StencilReactComponent<EuiIconArrowUpRightElement, EuiIconArrowUpRightEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUpRightElement, EuiIconArrowUpRightEvents>({
    tagName: 'eui-icon-arrow-up-right',
    elementClass: EuiIconArrowUpRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUpRightEvents,
    defineCustomElement: defineEuiIconArrowUpRight
});
