'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUpHeavy as EuiIconArrowUpHeavyElement, defineCustomElement as defineEuiIconArrowUpHeavy } from "ensemble-ui/dist/components/eui-icon-arrow-up-heavy.js";
import React from 'react';

export type EuiIconArrowUpHeavyEvents = NonNullable<unknown>;

export const EuiIconArrowUpHeavy: StencilReactComponent<EuiIconArrowUpHeavyElement, EuiIconArrowUpHeavyEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUpHeavyElement, EuiIconArrowUpHeavyEvents>({
    tagName: 'eui-icon-arrow-up-heavy',
    elementClass: EuiIconArrowUpHeavyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUpHeavyEvents,
    defineCustomElement: defineEuiIconArrowUpHeavy
});
