'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFingerPrint as EuiIconFingerPrintElement, defineCustomElement as defineEuiIconFingerPrint } from "ensemble-ui/dist/components/eui-icon-finger-print.js";
import React from 'react';

export type EuiIconFingerPrintEvents = NonNullable<unknown>;

export const EuiIconFingerPrint: StencilReactComponent<EuiIconFingerPrintElement, EuiIconFingerPrintEvents> = /*@__PURE__*/ createComponent<EuiIconFingerPrintElement, EuiIconFingerPrintEvents>({
    tagName: 'eui-icon-finger-print',
    elementClass: EuiIconFingerPrintElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFingerPrintEvents,
    defineCustomElement: defineEuiIconFingerPrint
});
