'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "ensemble-ui/dist/components";
import { EuiButton as EuiButtonElement, defineCustomElement as defineEuiButton } from "ensemble-ui/dist/components/eui-button.js";

export type EuiButtonEvents = NonNullable<unknown>;

export const EuiButton: StencilReactComponent<EuiButtonElement, EuiButtonEvents, Components.EuiButton> = /*@__PURE__*/ createComponent<EuiButtonElement, EuiButtonEvents, Components.EuiButton>({
    tagName: 'eui-button',
    elementClass: EuiButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiButtonEvents,
    defineCustomElement: defineEuiButton
});
