'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUpOnSquareStack as EuiIconArrowUpOnSquareStackElement, defineCustomElement as defineEuiIconArrowUpOnSquareStack } from "ensemble-ui/dist/components/eui-icon-arrow-up-on-square-stack.js";
import React from 'react';

export type EuiIconArrowUpOnSquareStackEvents = NonNullable<unknown>;

export const EuiIconArrowUpOnSquareStack: StencilReactComponent<EuiIconArrowUpOnSquareStackElement, EuiIconArrowUpOnSquareStackEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUpOnSquareStackElement, EuiIconArrowUpOnSquareStackEvents>({
    tagName: 'eui-icon-arrow-up-on-square-stack',
    elementClass: EuiIconArrowUpOnSquareStackElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUpOnSquareStackEvents,
    defineCustomElement: defineEuiIconArrowUpOnSquareStack
});
