'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentArrowUp as EuiIconDocumentArrowUpElement, defineCustomElement as defineEuiIconDocumentArrowUp } from "ensemble-ui/dist/components/eui-icon-document-arrow-up.js";
import React from 'react';

export type EuiIconDocumentArrowUpEvents = NonNullable<unknown>;

export const EuiIconDocumentArrowUp: StencilReactComponent<EuiIconDocumentArrowUpElement, EuiIconDocumentArrowUpEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentArrowUpElement, EuiIconDocumentArrowUpEvents>({
    tagName: 'eui-icon-document-arrow-up',
    elementClass: EuiIconDocumentArrowUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentArrowUpEvents,
    defineCustomElement: defineEuiIconDocumentArrowUp
});
