'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBars2 as EuiIconBars2Element, defineCustomElement as defineEuiIconBars2 } from "ensemble-ui/dist/components/eui-icon-bars-2.js";
import React from 'react';

export type EuiIconBars2Events = NonNullable<unknown>;

export const EuiIconBars2: StencilReactComponent<EuiIconBars2Element, EuiIconBars2Events> = /*@__PURE__*/ createComponent<EuiIconBars2Element, EuiIconBars2Events>({
    tagName: 'eui-icon-bars-2',
    elementClass: EuiIconBars2Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBars2Events,
    defineCustomElement: defineEuiIconBars2
});
