'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconHome as EuiIconHomeElement, defineCustomElement as defineEuiIconHome } from "ensemble-ui/dist/components/eui-icon-home.js";
import React from 'react';

export type EuiIconHomeEvents = NonNullable<unknown>;

export const EuiIconHome: StencilReactComponent<EuiIconHomeElement, EuiIconHomeEvents> = /*@__PURE__*/ createComponent<EuiIconHomeElement, EuiIconHomeEvents>({
    tagName: 'eui-icon-home',
    elementClass: EuiIconHomeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconHomeEvents,
    defineCustomElement: defineEuiIconHome
});
