'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiStat as EuiStatElement, defineCustomElement as defineEuiStat } from "ensemble-ui/dist/components/eui-stat.js";
import React from 'react';

export type EuiStatEvents = NonNullable<unknown>;

export const EuiStat: StencilReactComponent<EuiStatElement, EuiStatEvents> = /*@__PURE__*/ createComponent<EuiStatElement, EuiStatEvents>({
    tagName: 'eui-stat',
    elementClass: EuiStatElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiStatEvents,
    defineCustomElement: defineEuiStat
});
