'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type EuiDecadeCardCustomEvent } from "ensemble-ui";
import { EuiDecadeCard as EuiDecadeCardElement, defineCustomElement as defineEuiDecadeCard } from "ensemble-ui/dist/components/eui-decade-card.js";
import React from 'react';

export type EuiDecadeCardEvents = { onYearClick: EventName<EuiDecadeCardCustomEvent<Date>> };

export const EuiDecadeCard: StencilReactComponent<EuiDecadeCardElement, EuiDecadeCardEvents> = /*@__PURE__*/ createComponent<EuiDecadeCardElement, EuiDecadeCardEvents>({
    tagName: 'eui-decade-card',
    elementClass: EuiDecadeCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onYearClick: 'yearClick' } as EuiDecadeCardEvents,
    defineCustomElement: defineEuiDecadeCard
});
