'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconLanguage as EuiIconLanguageElement, defineCustomElement as defineEuiIconLanguage } from "ensemble-ui/dist/components/eui-icon-language.js";
import React from 'react';

export type EuiIconLanguageEvents = NonNullable<unknown>;

export const EuiIconLanguage: StencilReactComponent<EuiIconLanguageElement, EuiIconLanguageEvents> = /*@__PURE__*/ createComponent<EuiIconLanguageElement, EuiIconLanguageEvents>({
    tagName: 'eui-icon-language',
    elementClass: EuiIconLanguageElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconLanguageEvents,
    defineCustomElement: defineEuiIconLanguage
});
