'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSquaresPlus as EuiIconSquaresPlusElement, defineCustomElement as defineEuiIconSquaresPlus } from "ensemble-ui/dist/components/eui-icon-squares-plus.js";
import React from 'react';

export type EuiIconSquaresPlusEvents = NonNullable<unknown>;

export const EuiIconSquaresPlus: StencilReactComponent<EuiIconSquaresPlusElement, EuiIconSquaresPlusEvents> = /*@__PURE__*/ createComponent<EuiIconSquaresPlusElement, EuiIconSquaresPlusEvents>({
    tagName: 'eui-icon-squares-plus',
    elementClass: EuiIconSquaresPlusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSquaresPlusEvents,
    defineCustomElement: defineEuiIconSquaresPlus
});
