'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBackspace as EuiIconBackspaceElement, defineCustomElement as defineEuiIconBackspace } from "ensemble-ui/dist/components/eui-icon-backspace.js";
import React from 'react';

export type EuiIconBackspaceEvents = NonNullable<unknown>;

export const EuiIconBackspace: StencilReactComponent<EuiIconBackspaceElement, EuiIconBackspaceEvents> = /*@__PURE__*/ createComponent<EuiIconBackspaceElement, EuiIconBackspaceEvents>({
    tagName: 'eui-icon-backspace',
    elementClass: EuiIconBackspaceElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBackspaceEvents,
    defineCustomElement: defineEuiIconBackspace
});
