'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconInboxStack as EuiIconInboxStackElement, defineCustomElement as defineEuiIconInboxStack } from "ensemble-ui/dist/components/eui-icon-inbox-stack.js";
import React from 'react';

export type EuiIconInboxStackEvents = NonNullable<unknown>;

export const EuiIconInboxStack: StencilReactComponent<EuiIconInboxStackElement, EuiIconInboxStackEvents> = /*@__PURE__*/ createComponent<EuiIconInboxStackElement, EuiIconInboxStackEvents>({
    tagName: 'eui-icon-inbox-stack',
    elementClass: EuiIconInboxStackElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconInboxStackEvents,
    defineCustomElement: defineEuiIconInboxStack
});
