'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCheck as EuiIconCheckElement, defineCustomElement as defineEuiIconCheck } from "ensemble-ui/dist/components/eui-icon-check.js";
import React from 'react';

export type EuiIconCheckEvents = NonNullable<unknown>;

export const EuiIconCheck: StencilReactComponent<EuiIconCheckElement, EuiIconCheckEvents> = /*@__PURE__*/ createComponent<EuiIconCheckElement, EuiIconCheckEvents>({
    tagName: 'eui-icon-check',
    elementClass: EuiIconCheckElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCheckEvents,
    defineCustomElement: defineEuiIconCheck
});
