'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowDownOnSquareStack as EuiIconArrowDownOnSquareStackElement, defineCustomElement as defineEuiIconArrowDownOnSquareStack } from "ensemble-ui/dist/components/eui-icon-arrow-down-on-square-stack.js";
import React from 'react';

export type EuiIconArrowDownOnSquareStackEvents = NonNullable<unknown>;

export const EuiIconArrowDownOnSquareStack: StencilReactComponent<EuiIconArrowDownOnSquareStackElement, EuiIconArrowDownOnSquareStackEvents> = /*@__PURE__*/ createComponent<EuiIconArrowDownOnSquareStackElement, EuiIconArrowDownOnSquareStackEvents>({
    tagName: 'eui-icon-arrow-down-on-square-stack',
    elementClass: EuiIconArrowDownOnSquareStackElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowDownOnSquareStackEvents,
    defineCustomElement: defineEuiIconArrowDownOnSquareStack
});
