'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDeviceTablet as EuiIconDeviceTabletElement, defineCustomElement as defineEuiIconDeviceTablet } from "ensemble-ui/dist/components/eui-icon-device-tablet.js";
import React from 'react';

export type EuiIconDeviceTabletEvents = NonNullable<unknown>;

export const EuiIconDeviceTablet: StencilReactComponent<EuiIconDeviceTabletElement, EuiIconDeviceTabletEvents> = /*@__PURE__*/ createComponent<EuiIconDeviceTabletElement, EuiIconDeviceTabletEvents>({
    tagName: 'eui-icon-device-tablet',
    elementClass: EuiIconDeviceTabletElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDeviceTabletEvents,
    defineCustomElement: defineEuiIconDeviceTablet
});
