'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconInboxArrowDown as EuiIconInboxArrowDownElement, defineCustomElement as defineEuiIconInboxArrowDown } from "ensemble-ui/dist/components/eui-icon-inbox-arrow-down.js";
import React from 'react';

export type EuiIconInboxArrowDownEvents = NonNullable<unknown>;

export const EuiIconInboxArrowDown: StencilReactComponent<EuiIconInboxArrowDownElement, EuiIconInboxArrowDownEvents> = /*@__PURE__*/ createComponent<EuiIconInboxArrowDownElement, EuiIconInboxArrowDownEvents>({
    tagName: 'eui-icon-inbox-arrow-down',
    elementClass: EuiIconInboxArrowDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconInboxArrowDownEvents,
    defineCustomElement: defineEuiIconInboxArrowDown
});
