'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCurrencyDollar as EuiIconCurrencyDollarElement, defineCustomElement as defineEuiIconCurrencyDollar } from "ensemble-ui/dist/components/eui-icon-currency-dollar.js";
import React from 'react';

export type EuiIconCurrencyDollarEvents = NonNullable<unknown>;

export const EuiIconCurrencyDollar: StencilReactComponent<EuiIconCurrencyDollarElement, EuiIconCurrencyDollarEvents> = /*@__PURE__*/ createComponent<EuiIconCurrencyDollarElement, EuiIconCurrencyDollarEvents>({
    tagName: 'eui-icon-currency-dollar',
    elementClass: EuiIconCurrencyDollarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCurrencyDollarEvents,
    defineCustomElement: defineEuiIconCurrencyDollar
});
