'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCloud as EuiIconCloudElement, defineCustomElement as defineEuiIconCloud } from "ensemble-ui/dist/components/eui-icon-cloud.js";
import React from 'react';

export type EuiIconCloudEvents = NonNullable<unknown>;

export const EuiIconCloud: StencilReactComponent<EuiIconCloudElement, EuiIconCloudEvents> = /*@__PURE__*/ createComponent<EuiIconCloudElement, EuiIconCloudEvents>({
    tagName: 'eui-icon-cloud',
    elementClass: EuiIconCloudElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCloudEvents,
    defineCustomElement: defineEuiIconCloud
});
