'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconTag as EuiIconTagElement, defineCustomElement as defineEuiIconTag } from "ensemble-ui/dist/components/eui-icon-tag.js";
import React from 'react';

export type EuiIconTagEvents = NonNullable<unknown>;

export const EuiIconTag: StencilReactComponent<EuiIconTagElement, EuiIconTagEvents> = /*@__PURE__*/ createComponent<EuiIconTagElement, EuiIconTagEvents>({
    tagName: 'eui-icon-tag',
    elementClass: EuiIconTagElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconTagEvents,
    defineCustomElement: defineEuiIconTag
});
