'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconRadio as EuiIconRadioElement, defineCustomElement as defineEuiIconRadio } from "ensemble-ui/dist/components/eui-icon-radio.js";
import React from 'react';

export type EuiIconRadioEvents = NonNullable<unknown>;

export const EuiIconRadio: StencilReactComponent<EuiIconRadioElement, EuiIconRadioEvents> = /*@__PURE__*/ createComponent<EuiIconRadioElement, EuiIconRadioEvents>({
    tagName: 'eui-icon-radio',
    elementClass: EuiIconRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconRadioEvents,
    defineCustomElement: defineEuiIconRadio
});
