'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUturnLeft as EuiIconArrowUturnLeftElement, defineCustomElement as defineEuiIconArrowUturnLeft } from "ensemble-ui/dist/components/eui-icon-arrow-uturn-left.js";
import React from 'react';

export type EuiIconArrowUturnLeftEvents = NonNullable<unknown>;

export const EuiIconArrowUturnLeft: StencilReactComponent<EuiIconArrowUturnLeftElement, EuiIconArrowUturnLeftEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUturnLeftElement, EuiIconArrowUturnLeftEvents>({
    tagName: 'eui-icon-arrow-uturn-left',
    elementClass: EuiIconArrowUturnLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUturnLeftEvents,
    defineCustomElement: defineEuiIconArrowUturnLeft
});
