'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconRectangleGroup as EuiIconRectangleGroupElement, defineCustomElement as defineEuiIconRectangleGroup } from "ensemble-ui/dist/components/eui-icon-rectangle-group.js";
import React from 'react';

export type EuiIconRectangleGroupEvents = NonNullable<unknown>;

export const EuiIconRectangleGroup: StencilReactComponent<EuiIconRectangleGroupElement, EuiIconRectangleGroupEvents> = /*@__PURE__*/ createComponent<EuiIconRectangleGroupElement, EuiIconRectangleGroupEvents>({
    tagName: 'eui-icon-rectangle-group',
    elementClass: EuiIconRectangleGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconRectangleGroupEvents,
    defineCustomElement: defineEuiIconRectangleGroup
});
