'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPlayPause as EuiIconPlayPauseElement, defineCustomElement as defineEuiIconPlayPause } from "ensemble-ui/dist/components/eui-icon-play-pause.js";
import React from 'react';

export type EuiIconPlayPauseEvents = NonNullable<unknown>;

export const EuiIconPlayPause: StencilReactComponent<EuiIconPlayPauseElement, EuiIconPlayPauseEvents> = /*@__PURE__*/ createComponent<EuiIconPlayPauseElement, EuiIconPlayPauseEvents>({
    tagName: 'eui-icon-play-pause',
    elementClass: EuiIconPlayPauseElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPlayPauseEvents,
    defineCustomElement: defineEuiIconPlayPause
});
