'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconStop as EuiIconStopElement, defineCustomElement as defineEuiIconStop } from "ensemble-ui/dist/components/eui-icon-stop.js";
import React from 'react';

export type EuiIconStopEvents = NonNullable<unknown>;

export const EuiIconStop: StencilReactComponent<EuiIconStopElement, EuiIconStopEvents> = /*@__PURE__*/ createComponent<EuiIconStopElement, EuiIconStopEvents>({
    tagName: 'eui-icon-stop',
    elementClass: EuiIconStopElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconStopEvents,
    defineCustomElement: defineEuiIconStop
});
