'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCpuChip as EuiIconCpuChipElement, defineCustomElement as defineEuiIconCpuChip } from "ensemble-ui/dist/components/eui-icon-cpu-chip.js";
import React from 'react';

export type EuiIconCpuChipEvents = NonNullable<unknown>;

export const EuiIconCpuChip: StencilReactComponent<EuiIconCpuChipElement, EuiIconCpuChipEvents> = /*@__PURE__*/ createComponent<EuiIconCpuChipElement, EuiIconCpuChipEvents>({
    tagName: 'eui-icon-cpu-chip',
    elementClass: EuiIconCpuChipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCpuChipEvents,
    defineCustomElement: defineEuiIconCpuChip
});
