'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChatBubbleOvalLeft as EuiIconChatBubbleOvalLeftElement, defineCustomElement as defineEuiIconChatBubbleOvalLeft } from "ensemble-ui/dist/components/eui-icon-chat-bubble-oval-left.js";
import React from 'react';

export type EuiIconChatBubbleOvalLeftEvents = NonNullable<unknown>;

export const EuiIconChatBubbleOvalLeft: StencilReactComponent<EuiIconChatBubbleOvalLeftElement, EuiIconChatBubbleOvalLeftEvents> = /*@__PURE__*/ createComponent<EuiIconChatBubbleOvalLeftElement, EuiIconChatBubbleOvalLeftEvents>({
    tagName: 'eui-icon-chat-bubble-oval-left',
    elementClass: EuiIconChatBubbleOvalLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChatBubbleOvalLeftEvents,
    defineCustomElement: defineEuiIconChatBubbleOvalLeft
});
