'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconInformationCircle as EuiIconInformationCircleElement, defineCustomElement as defineEuiIconInformationCircle } from "ensemble-ui/dist/components/eui-icon-information-circle.js";
import React from 'react';

export type EuiIconInformationCircleEvents = NonNullable<unknown>;

export const EuiIconInformationCircle: StencilReactComponent<EuiIconInformationCircleElement, EuiIconInformationCircleEvents> = /*@__PURE__*/ createComponent<EuiIconInformationCircleElement, EuiIconInformationCircleEvents>({
    tagName: 'eui-icon-information-circle',
    elementClass: EuiIconInformationCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconInformationCircleEvents,
    defineCustomElement: defineEuiIconInformationCircle
});
