'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSquares2x2 as EuiIconSquares2x2Element, defineCustomElement as defineEuiIconSquares2x2 } from "ensemble-ui/dist/components/eui-icon-squares-2x2.js";
import React from 'react';

export type EuiIconSquares2x2Events = NonNullable<unknown>;

export const EuiIconSquares2x2: StencilReactComponent<EuiIconSquares2x2Element, EuiIconSquares2x2Events> = /*@__PURE__*/ createComponent<EuiIconSquares2x2Element, EuiIconSquares2x2Events>({
    tagName: 'eui-icon-squares-2x2',
    elementClass: EuiIconSquares2x2Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSquares2x2Events,
    defineCustomElement: defineEuiIconSquares2x2
});
