'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconClipboardDocument as EuiIconClipboardDocumentElement, defineCustomElement as defineEuiIconClipboardDocument } from "ensemble-ui/dist/components/eui-icon-clipboard-document.js";
import React from 'react';

export type EuiIconClipboardDocumentEvents = NonNullable<unknown>;

export const EuiIconClipboardDocument: StencilReactComponent<EuiIconClipboardDocumentElement, EuiIconClipboardDocumentEvents> = /*@__PURE__*/ createComponent<EuiIconClipboardDocumentElement, EuiIconClipboardDocumentEvents>({
    tagName: 'eui-icon-clipboard-document',
    elementClass: EuiIconClipboardDocumentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconClipboardDocumentEvents,
    defineCustomElement: defineEuiIconClipboardDocument
});
