'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTurnUpLeft as EuiIconArrowTurnUpLeftElement, defineCustomElement as defineEuiIconArrowTurnUpLeft } from "ensemble-ui/dist/components/eui-icon-arrow-turn-up-left.js";
import React from 'react';

export type EuiIconArrowTurnUpLeftEvents = NonNullable<unknown>;

export const EuiIconArrowTurnUpLeft: StencilReactComponent<EuiIconArrowTurnUpLeftElement, EuiIconArrowTurnUpLeftEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTurnUpLeftElement, EuiIconArrowTurnUpLeftEvents>({
    tagName: 'eui-icon-arrow-turn-up-left',
    elementClass: EuiIconArrowTurnUpLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTurnUpLeftEvents,
    defineCustomElement: defineEuiIconArrowTurnUpLeft
});
