'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowDownTray as EuiIconArrowDownTrayElement, defineCustomElement as defineEuiIconArrowDownTray } from "ensemble-ui/dist/components/eui-icon-arrow-down-tray.js";
import React from 'react';

export type EuiIconArrowDownTrayEvents = NonNullable<unknown>;

export const EuiIconArrowDownTray: StencilReactComponent<EuiIconArrowDownTrayElement, EuiIconArrowDownTrayEvents> = /*@__PURE__*/ createComponent<EuiIconArrowDownTrayElement, EuiIconArrowDownTrayEvents>({
    tagName: 'eui-icon-arrow-down-tray',
    elementClass: EuiIconArrowDownTrayElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowDownTrayEvents,
    defineCustomElement: defineEuiIconArrowDownTray
});
