'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChevronDoubleDown as EuiIconChevronDoubleDownElement, defineCustomElement as defineEuiIconChevronDoubleDown } from "ensemble-ui/dist/components/eui-icon-chevron-double-down.js";
import React from 'react';

export type EuiIconChevronDoubleDownEvents = NonNullable<unknown>;

export const EuiIconChevronDoubleDown: StencilReactComponent<EuiIconChevronDoubleDownElement, EuiIconChevronDoubleDownEvents> = /*@__PURE__*/ createComponent<EuiIconChevronDoubleDownElement, EuiIconChevronDoubleDownEvents>({
    tagName: 'eui-icon-chevron-double-down',
    elementClass: EuiIconChevronDoubleDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChevronDoubleDownEvents,
    defineCustomElement: defineEuiIconChevronDoubleDown
});
