'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconLifebuoy as EuiIconLifebuoyElement, defineCustomElement as defineEuiIconLifebuoy } from "ensemble-ui/dist/components/eui-icon-lifebuoy.js";
import React from 'react';

export type EuiIconLifebuoyEvents = NonNullable<unknown>;

export const EuiIconLifebuoy: StencilReactComponent<EuiIconLifebuoyElement, EuiIconLifebuoyEvents> = /*@__PURE__*/ createComponent<EuiIconLifebuoyElement, EuiIconLifebuoyEvents>({
    tagName: 'eui-icon-lifebuoy',
    elementClass: EuiIconLifebuoyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconLifebuoyEvents,
    defineCustomElement: defineEuiIconLifebuoy
});
