'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBold as EuiIconBoldElement, defineCustomElement as defineEuiIconBold } from "ensemble-ui/dist/components/eui-icon-bold.js";
import React from 'react';

export type EuiIconBoldEvents = NonNullable<unknown>;

export const EuiIconBold: StencilReactComponent<EuiIconBoldElement, EuiIconBoldEvents> = /*@__PURE__*/ createComponent<EuiIconBoldElement, EuiIconBoldEvents>({
    tagName: 'eui-icon-bold',
    elementClass: EuiIconBoldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBoldEvents,
    defineCustomElement: defineEuiIconBold
});
