'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowsPointingIn as EuiIconArrowsPointingInElement, defineCustomElement as defineEuiIconArrowsPointingIn } from "ensemble-ui/dist/components/eui-icon-arrows-pointing-in.js";
import React from 'react';

export type EuiIconArrowsPointingInEvents = NonNullable<unknown>;

export const EuiIconArrowsPointingIn: StencilReactComponent<EuiIconArrowsPointingInElement, EuiIconArrowsPointingInEvents> = /*@__PURE__*/ createComponent<EuiIconArrowsPointingInElement, EuiIconArrowsPointingInEvents>({
    tagName: 'eui-icon-arrows-pointing-in',
    elementClass: EuiIconArrowsPointingInElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowsPointingInEvents,
    defineCustomElement: defineEuiIconArrowsPointingIn
});
