'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentText as EuiIconDocumentTextElement, defineCustomElement as defineEuiIconDocumentText } from "ensemble-ui/dist/components/eui-icon-document-text.js";
import React from 'react';

export type EuiIconDocumentTextEvents = NonNullable<unknown>;

export const EuiIconDocumentText: StencilReactComponent<EuiIconDocumentTextElement, EuiIconDocumentTextEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentTextElement, EuiIconDocumentTextEvents>({
    tagName: 'eui-icon-document-text',
    elementClass: EuiIconDocumentTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentTextEvents,
    defineCustomElement: defineEuiIconDocumentText
});
