'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconXCircle as EuiIconXCircleElement, defineCustomElement as defineEuiIconXCircle } from "ensemble-ui/dist/components/eui-icon-x-circle.js";
import React from 'react';

export type EuiIconXCircleEvents = NonNullable<unknown>;

export const EuiIconXCircle: StencilReactComponent<EuiIconXCircleElement, EuiIconXCircleEvents> = /*@__PURE__*/ createComponent<EuiIconXCircleElement, EuiIconXCircleEvents>({
    tagName: 'eui-icon-x-circle',
    elementClass: EuiIconXCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconXCircleEvents,
    defineCustomElement: defineEuiIconXCircle
});
