'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUturnRight as EuiIconArrowUturnRightElement, defineCustomElement as defineEuiIconArrowUturnRight } from "ensemble-ui/dist/components/eui-icon-arrow-uturn-right.js";
import React from 'react';

export type EuiIconArrowUturnRightEvents = NonNullable<unknown>;

export const EuiIconArrowUturnRight: StencilReactComponent<EuiIconArrowUturnRightElement, EuiIconArrowUturnRightEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUturnRightElement, EuiIconArrowUturnRightEvents>({
    tagName: 'eui-icon-arrow-uturn-right',
    elementClass: EuiIconArrowUturnRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUturnRightEvents,
    defineCustomElement: defineEuiIconArrowUturnRight
});
