'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconThirdSpinner as EuiIconThirdSpinnerElement, defineCustomElement as defineEuiIconThirdSpinner } from "ensemble-ui/dist/components/eui-icon-third-spinner.js";
import React from 'react';

export type EuiIconThirdSpinnerEvents = NonNullable<unknown>;

export const EuiIconThirdSpinner: StencilReactComponent<EuiIconThirdSpinnerElement, EuiIconThirdSpinnerEvents> = /*@__PURE__*/ createComponent<EuiIconThirdSpinnerElement, EuiIconThirdSpinnerEvents>({
    tagName: 'eui-icon-third-spinner',
    elementClass: EuiIconThirdSpinnerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconThirdSpinnerEvents,
    defineCustomElement: defineEuiIconThirdSpinner
});
