'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPresentationChartBar as EuiIconPresentationChartBarElement, defineCustomElement as defineEuiIconPresentationChartBar } from "ensemble-ui/dist/components/eui-icon-presentation-chart-bar.js";
import React from 'react';

export type EuiIconPresentationChartBarEvents = NonNullable<unknown>;

export const EuiIconPresentationChartBar: StencilReactComponent<EuiIconPresentationChartBarElement, EuiIconPresentationChartBarEvents> = /*@__PURE__*/ createComponent<EuiIconPresentationChartBarElement, EuiIconPresentationChartBarEvents>({
    tagName: 'eui-icon-presentation-chart-bar',
    elementClass: EuiIconPresentationChartBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPresentationChartBarEvents,
    defineCustomElement: defineEuiIconPresentationChartBar
});
