'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconTicket as EuiIconTicketElement, defineCustomElement as defineEuiIconTicket } from "ensemble-ui/dist/components/eui-icon-ticket.js";
import React from 'react';

export type EuiIconTicketEvents = NonNullable<unknown>;

export const EuiIconTicket: StencilReactComponent<EuiIconTicketElement, EuiIconTicketEvents> = /*@__PURE__*/ createComponent<EuiIconTicketElement, EuiIconTicketEvents>({
    tagName: 'eui-icon-ticket',
    elementClass: EuiIconTicketElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconTicketEvents,
    defineCustomElement: defineEuiIconTicket
});
