'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowLeftHeavy as EuiIconArrowLeftHeavyElement, defineCustomElement as defineEuiIconArrowLeftHeavy } from "ensemble-ui/dist/components/eui-icon-arrow-left-heavy.js";
import React from 'react';

export type EuiIconArrowLeftHeavyEvents = NonNullable<unknown>;

export const EuiIconArrowLeftHeavy: StencilReactComponent<EuiIconArrowLeftHeavyElement, EuiIconArrowLeftHeavyEvents> = /*@__PURE__*/ createComponent<EuiIconArrowLeftHeavyElement, EuiIconArrowLeftHeavyEvents>({
    tagName: 'eui-icon-arrow-left-heavy',
    elementClass: EuiIconArrowLeftHeavyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowLeftHeavyEvents,
    defineCustomElement: defineEuiIconArrowLeftHeavy
});
