'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconAcademicCap as EuiIconAcademicCapElement, defineCustomElement as defineEuiIconAcademicCap } from "ensemble-ui/dist/components/eui-icon-academic-cap.js";
import React from 'react';

export type EuiIconAcademicCapEvents = NonNullable<unknown>;

export const EuiIconAcademicCap: StencilReactComponent<EuiIconAcademicCapElement, EuiIconAcademicCapEvents> = /*@__PURE__*/ createComponent<EuiIconAcademicCapElement, EuiIconAcademicCapEvents>({
    tagName: 'eui-icon-academic-cap',
    elementClass: EuiIconAcademicCapElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconAcademicCapEvents,
    defineCustomElement: defineEuiIconAcademicCap
});
