'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBanknotes as EuiIconBanknotesElement, defineCustomElement as defineEuiIconBanknotes } from "ensemble-ui/dist/components/eui-icon-banknotes.js";
import React from 'react';

export type EuiIconBanknotesEvents = NonNullable<unknown>;

export const EuiIconBanknotes: StencilReactComponent<EuiIconBanknotesElement, EuiIconBanknotesEvents> = /*@__PURE__*/ createComponent<EuiIconBanknotesElement, EuiIconBanknotesEvents>({
    tagName: 'eui-icon-banknotes',
    elementClass: EuiIconBanknotesElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBanknotesEvents,
    defineCustomElement: defineEuiIconBanknotes
});
