'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFolder as EuiIconFolderElement, defineCustomElement as defineEuiIconFolder } from "ensemble-ui/dist/components/eui-icon-folder.js";
import React from 'react';

export type EuiIconFolderEvents = NonNullable<unknown>;

export const EuiIconFolder: StencilReactComponent<EuiIconFolderElement, EuiIconFolderEvents> = /*@__PURE__*/ createComponent<EuiIconFolderElement, EuiIconFolderEvents>({
    tagName: 'eui-icon-folder',
    elementClass: EuiIconFolderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFolderEvents,
    defineCustomElement: defineEuiIconFolder
});
