'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPresentationChartLine as EuiIconPresentationChartLineElement, defineCustomElement as defineEuiIconPresentationChartLine } from "ensemble-ui/dist/components/eui-icon-presentation-chart-line.js";
import React from 'react';

export type EuiIconPresentationChartLineEvents = NonNullable<unknown>;

export const EuiIconPresentationChartLine: StencilReactComponent<EuiIconPresentationChartLineElement, EuiIconPresentationChartLineEvents> = /*@__PURE__*/ createComponent<EuiIconPresentationChartLineElement, EuiIconPresentationChartLineEvents>({
    tagName: 'eui-icon-presentation-chart-line',
    elementClass: EuiIconPresentationChartLineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPresentationChartLineEvents,
    defineCustomElement: defineEuiIconPresentationChartLine
});
