'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconVideoCameraSlash as EuiIconVideoCameraSlashElement, defineCustomElement as defineEuiIconVideoCameraSlash } from "ensemble-ui/dist/components/eui-icon-video-camera-slash.js";
import React from 'react';

export type EuiIconVideoCameraSlashEvents = NonNullable<unknown>;

export const EuiIconVideoCameraSlash: StencilReactComponent<EuiIconVideoCameraSlashElement, EuiIconVideoCameraSlashEvents> = /*@__PURE__*/ createComponent<EuiIconVideoCameraSlashElement, EuiIconVideoCameraSlashEvents>({
    tagName: 'eui-icon-video-camera-slash',
    elementClass: EuiIconVideoCameraSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconVideoCameraSlashEvents,
    defineCustomElement: defineEuiIconVideoCameraSlash
});
