'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTurnLeftUp as EuiIconArrowTurnLeftUpElement, defineCustomElement as defineEuiIconArrowTurnLeftUp } from "ensemble-ui/dist/components/eui-icon-arrow-turn-left-up.js";
import React from 'react';

export type EuiIconArrowTurnLeftUpEvents = NonNullable<unknown>;

export const EuiIconArrowTurnLeftUp: StencilReactComponent<EuiIconArrowTurnLeftUpElement, EuiIconArrowTurnLeftUpEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTurnLeftUpElement, EuiIconArrowTurnLeftUpEvents>({
    tagName: 'eui-icon-arrow-turn-left-up',
    elementClass: EuiIconArrowTurnLeftUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTurnLeftUpEvents,
    defineCustomElement: defineEuiIconArrowTurnLeftUp
});
