'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArchiveBox as EuiIconArchiveBoxElement, defineCustomElement as defineEuiIconArchiveBox } from "ensemble-ui/dist/components/eui-icon-archive-box.js";
import React from 'react';

export type EuiIconArchiveBoxEvents = NonNullable<unknown>;

export const EuiIconArchiveBox: StencilReactComponent<EuiIconArchiveBoxElement, EuiIconArchiveBoxEvents> = /*@__PURE__*/ createComponent<EuiIconArchiveBoxElement, EuiIconArchiveBoxEvents>({
    tagName: 'eui-icon-archive-box',
    elementClass: EuiIconArchiveBoxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArchiveBoxEvents,
    defineCustomElement: defineEuiIconArchiveBox
});
