'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSun as EuiIconSunElement, defineCustomElement as defineEuiIconSun } from "ensemble-ui/dist/components/eui-icon-sun.js";
import React from 'react';

export type EuiIconSunEvents = NonNullable<unknown>;

export const EuiIconSun: StencilReactComponent<EuiIconSunElement, EuiIconSunEvents> = /*@__PURE__*/ createComponent<EuiIconSunElement, EuiIconSunEvents>({
    tagName: 'eui-icon-sun',
    elementClass: EuiIconSunElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSunEvents,
    defineCustomElement: defineEuiIconSun
});
