'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "ensemble-ui/dist/components";
import { EuiSideNav as EuiSideNavElement, defineCustomElement as defineEuiSideNav } from "ensemble-ui/dist/components/eui-side-nav.js";

export type EuiSideNavEvents = NonNullable<unknown>;

export const EuiSideNav: StencilReactComponent<EuiSideNavElement, EuiSideNavEvents, Components.EuiSideNav> = /*@__PURE__*/ createComponent<EuiSideNavElement, EuiSideNavEvents, Components.EuiSideNav>({
    tagName: 'eui-side-nav',
    elementClass: EuiSideNavElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiSideNavEvents,
    defineCustomElement: defineEuiSideNav
});
