'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiEmptyStateCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiEmptyState as EuiEmptyStateElement, defineCustomElement as defineEuiEmptyState } from "ensemble-ui/dist/components/eui-empty-state.js";

export type EuiEmptyStateEvents = {
    onPrimaryClick: EventName<EuiEmptyStateCustomEvent<any>>,
    onSecondaryClick: EventName<EuiEmptyStateCustomEvent<any>>
};

export const EuiEmptyState: StencilReactComponent<EuiEmptyStateElement, EuiEmptyStateEvents, Components.EuiEmptyState> = /*@__PURE__*/ createComponent<EuiEmptyStateElement, EuiEmptyStateEvents, Components.EuiEmptyState>({
    tagName: 'eui-empty-state',
    elementClass: EuiEmptyStateElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onPrimaryClick: 'primaryClick',
        onSecondaryClick: 'secondaryClick'
    } as EuiEmptyStateEvents,
    defineCustomElement: defineEuiEmptyState
});
