'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type EuiWeekViewCustomEvent } from "ensemble-ui";
import { EuiWeekView as EuiWeekViewElement, defineCustomElement as defineEuiWeekView } from "ensemble-ui/dist/components/eui-week-view.js";
import React from 'react';

export type EuiWeekViewEvents = { onDayClick: EventName<EuiWeekViewCustomEvent<Date>> };

export const EuiWeekView: StencilReactComponent<EuiWeekViewElement, EuiWeekViewEvents> = /*@__PURE__*/ createComponent<EuiWeekViewElement, EuiWeekViewEvents>({
    tagName: 'eui-week-view',
    elementClass: EuiWeekViewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDayClick: 'dayClick' } as EuiWeekViewEvents,
    defineCustomElement: defineEuiWeekView
});
