'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconEnvelopeOpen as EuiIconEnvelopeOpenElement, defineCustomElement as defineEuiIconEnvelopeOpen } from "ensemble-ui/dist/components/eui-icon-envelope-open.js";
import React from 'react';

export type EuiIconEnvelopeOpenEvents = NonNullable<unknown>;

export const EuiIconEnvelopeOpen: StencilReactComponent<EuiIconEnvelopeOpenElement, EuiIconEnvelopeOpenEvents> = /*@__PURE__*/ createComponent<EuiIconEnvelopeOpenElement, EuiIconEnvelopeOpenEvents>({
    tagName: 'eui-icon-envelope-open',
    elementClass: EuiIconEnvelopeOpenElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEnvelopeOpenEvents,
    defineCustomElement: defineEuiIconEnvelopeOpen
});
