'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiPaginatorCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiPaginator as EuiPaginatorElement, defineCustomElement as defineEuiPaginator } from "ensemble-ui/dist/components/eui-paginator.js";

export type EuiPaginatorEvents = { onCurrentPage: EventName<EuiPaginatorCustomEvent<any>> };

export const EuiPaginator: StencilReactComponent<EuiPaginatorElement, EuiPaginatorEvents, Components.EuiPaginator> = /*@__PURE__*/ createComponent<EuiPaginatorElement, EuiPaginatorEvents, Components.EuiPaginator>({
    tagName: 'eui-paginator',
    elementClass: EuiPaginatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCurrentPage: 'currentPage' } as EuiPaginatorEvents,
    defineCustomElement: defineEuiPaginator
});
