'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPaperClip as EuiIconPaperClipElement, defineCustomElement as defineEuiIconPaperClip } from "ensemble-ui/dist/components/eui-icon-paper-clip.js";
import React from 'react';

export type EuiIconPaperClipEvents = NonNullable<unknown>;

export const EuiIconPaperClip: StencilReactComponent<EuiIconPaperClipElement, EuiIconPaperClipEvents> = /*@__PURE__*/ createComponent<EuiIconPaperClipElement, EuiIconPaperClipEvents>({
    tagName: 'eui-icon-paper-clip',
    elementClass: EuiIconPaperClipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPaperClipEvents,
    defineCustomElement: defineEuiIconPaperClip
});
