'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCalendar as EuiIconCalendarElement, defineCustomElement as defineEuiIconCalendar } from "ensemble-ui/dist/components/eui-icon-calendar.js";
import React from 'react';

export type EuiIconCalendarEvents = NonNullable<unknown>;

export const EuiIconCalendar: StencilReactComponent<EuiIconCalendarElement, EuiIconCalendarEvents> = /*@__PURE__*/ createComponent<EuiIconCalendarElement, EuiIconCalendarEvents>({
    tagName: 'eui-icon-calendar',
    elementClass: EuiIconCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCalendarEvents,
    defineCustomElement: defineEuiIconCalendar
});
