'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiSlider as EuiSliderElement, defineCustomElement as defineEuiSlider } from "ensemble-ui/dist/components/eui-slider.js";
import React from 'react';

export type EuiSliderEvents = { onValueChange: EventName<CustomEvent<number>> };

export const EuiSlider: StencilReactComponent<EuiSliderElement, EuiSliderEvents> = /*@__PURE__*/ createComponent<EuiSliderElement, EuiSliderEvents>({
    tagName: 'eui-slider',
    elementClass: EuiSliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as EuiSliderEvents,
    defineCustomElement: defineEuiSlider
});
