'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBoltSlash as EuiIconBoltSlashElement, defineCustomElement as defineEuiIconBoltSlash } from "ensemble-ui/dist/components/eui-icon-bolt-slash.js";
import React from 'react';

export type EuiIconBoltSlashEvents = NonNullable<unknown>;

export const EuiIconBoltSlash: StencilReactComponent<EuiIconBoltSlashElement, EuiIconBoltSlashEvents> = /*@__PURE__*/ createComponent<EuiIconBoltSlashElement, EuiIconBoltSlashEvents>({
    tagName: 'eui-icon-bolt-slash',
    elementClass: EuiIconBoltSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBoltSlashEvents,
    defineCustomElement: defineEuiIconBoltSlash
});
