'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPower as EuiIconPowerElement, defineCustomElement as defineEuiIconPower } from "ensemble-ui/dist/components/eui-icon-power.js";
import React from 'react';

export type EuiIconPowerEvents = NonNullable<unknown>;

export const EuiIconPower: StencilReactComponent<EuiIconPowerElement, EuiIconPowerEvents> = /*@__PURE__*/ createComponent<EuiIconPowerElement, EuiIconPowerEvents>({
    tagName: 'eui-icon-power',
    elementClass: EuiIconPowerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPowerEvents,
    defineCustomElement: defineEuiIconPower
});
