'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCurrencyEuro as EuiIconCurrencyEuroElement, defineCustomElement as defineEuiIconCurrencyEuro } from "ensemble-ui/dist/components/eui-icon-currency-euro.js";
import React from 'react';

export type EuiIconCurrencyEuroEvents = NonNullable<unknown>;

export const EuiIconCurrencyEuro: StencilReactComponent<EuiIconCurrencyEuroElement, EuiIconCurrencyEuroEvents> = /*@__PURE__*/ createComponent<EuiIconCurrencyEuroElement, EuiIconCurrencyEuroEvents>({
    tagName: 'eui-icon-currency-euro',
    elementClass: EuiIconCurrencyEuroElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCurrencyEuroEvents,
    defineCustomElement: defineEuiIconCurrencyEuro
});
