'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBookOpen as EuiIconBookOpenElement, defineCustomElement as defineEuiIconBookOpen } from "ensemble-ui/dist/components/eui-icon-book-open.js";
import React from 'react';

export type EuiIconBookOpenEvents = NonNullable<unknown>;

export const EuiIconBookOpen: StencilReactComponent<EuiIconBookOpenElement, EuiIconBookOpenEvents> = /*@__PURE__*/ createComponent<EuiIconBookOpenElement, EuiIconBookOpenEvents>({
    tagName: 'eui-icon-book-open',
    elementClass: EuiIconBookOpenElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBookOpenEvents,
    defineCustomElement: defineEuiIconBookOpen
});
