'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTurnDownLeft as EuiIconArrowTurnDownLeftElement, defineCustomElement as defineEuiIconArrowTurnDownLeft } from "ensemble-ui/dist/components/eui-icon-arrow-turn-down-left.js";
import React from 'react';

export type EuiIconArrowTurnDownLeftEvents = NonNullable<unknown>;

export const EuiIconArrowTurnDownLeft: StencilReactComponent<EuiIconArrowTurnDownLeftElement, EuiIconArrowTurnDownLeftEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTurnDownLeftElement, EuiIconArrowTurnDownLeftEvents>({
    tagName: 'eui-icon-arrow-turn-down-left',
    elementClass: EuiIconArrowTurnDownLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTurnDownLeftEvents,
    defineCustomElement: defineEuiIconArrowTurnDownLeft
});
