'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiTab as EuiTabElement, defineCustomElement as defineEuiTab } from "ensemble-ui/dist/components/eui-tab.js";
import React from 'react';

export type EuiTabEvents = NonNullable<unknown>;

export const EuiTab: StencilReactComponent<EuiTabElement, EuiTabEvents> = /*@__PURE__*/ createComponent<EuiTabElement, EuiTabEvents>({
    tagName: 'eui-tab',
    elementClass: EuiTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiTabEvents,
    defineCustomElement: defineEuiTab
});
