'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconKey as EuiIconKeyElement, defineCustomElement as defineEuiIconKey } from "ensemble-ui/dist/components/eui-icon-key.js";
import React from 'react';

export type EuiIconKeyEvents = NonNullable<unknown>;

export const EuiIconKey: StencilReactComponent<EuiIconKeyElement, EuiIconKeyEvents> = /*@__PURE__*/ createComponent<EuiIconKeyElement, EuiIconKeyEvents>({
    tagName: 'eui-icon-key',
    elementClass: EuiIconKeyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconKeyEvents,
    defineCustomElement: defineEuiIconKey
});
