'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiTabCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiTab as EuiTabElement, defineCustomElement as defineEuiTab } from "ensemble-ui/dist/components/eui-tab.js";

export type EuiTabEvents = { onItemSelected: EventName<EuiTabCustomEvent<any>> };

export const EuiTab: StencilReactComponent<EuiTabElement, EuiTabEvents, Components.EuiTab> = /*@__PURE__*/ createComponent<EuiTabElement, EuiTabEvents, Components.EuiTab>({
    tagName: 'eui-tab',
    elementClass: EuiTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onItemSelected: 'itemSelected' } as EuiTabEvents,
    defineCustomElement: defineEuiTab
});
