'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFolderPlus as EuiIconFolderPlusElement, defineCustomElement as defineEuiIconFolderPlus } from "ensemble-ui/dist/components/eui-icon-folder-plus.js";
import React from 'react';

export type EuiIconFolderPlusEvents = NonNullable<unknown>;

export const EuiIconFolderPlus: StencilReactComponent<EuiIconFolderPlusElement, EuiIconFolderPlusEvents> = /*@__PURE__*/ createComponent<EuiIconFolderPlusElement, EuiIconFolderPlusEvents>({
    tagName: 'eui-icon-folder-plus',
    elementClass: EuiIconFolderPlusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFolderPlusEvents,
    defineCustomElement: defineEuiIconFolderPlus
});
