'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowLeftStartOnRectangle as EuiIconArrowLeftStartOnRectangleElement, defineCustomElement as defineEuiIconArrowLeftStartOnRectangle } from "ensemble-ui/dist/components/eui-icon-arrow-left-start-on-rectangle.js";
import React from 'react';

export type EuiIconArrowLeftStartOnRectangleEvents = NonNullable<unknown>;

export const EuiIconArrowLeftStartOnRectangle: StencilReactComponent<EuiIconArrowLeftStartOnRectangleElement, EuiIconArrowLeftStartOnRectangleEvents> = /*@__PURE__*/ createComponent<EuiIconArrowLeftStartOnRectangleElement, EuiIconArrowLeftStartOnRectangleEvents>({
    tagName: 'eui-icon-arrow-left-start-on-rectangle',
    elementClass: EuiIconArrowLeftStartOnRectangleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowLeftStartOnRectangleEvents,
    defineCustomElement: defineEuiIconArrowLeftStartOnRectangle
});
