'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconForward as EuiIconForwardElement, defineCustomElement as defineEuiIconForward } from "ensemble-ui/dist/components/eui-icon-forward.js";
import React from 'react';

export type EuiIconForwardEvents = NonNullable<unknown>;

export const EuiIconForward: StencilReactComponent<EuiIconForwardElement, EuiIconForwardEvents> = /*@__PURE__*/ createComponent<EuiIconForwardElement, EuiIconForwardEvents>({
    tagName: 'eui-icon-forward',
    elementClass: EuiIconForwardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconForwardEvents,
    defineCustomElement: defineEuiIconForward
});
