'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChevronLeft as EuiIconChevronLeftElement, defineCustomElement as defineEuiIconChevronLeft } from "ensemble-ui/dist/components/eui-icon-chevron-left.js";
import React from 'react';

export type EuiIconChevronLeftEvents = NonNullable<unknown>;

export const EuiIconChevronLeft: StencilReactComponent<EuiIconChevronLeftElement, EuiIconChevronLeftEvents> = /*@__PURE__*/ createComponent<EuiIconChevronLeftElement, EuiIconChevronLeftEvents>({
    tagName: 'eui-icon-chevron-left',
    elementClass: EuiIconChevronLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChevronLeftEvents,
    defineCustomElement: defineEuiIconChevronLeft
});
