'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconStar as EuiIconStarElement, defineCustomElement as defineEuiIconStar } from "ensemble-ui/dist/components/eui-icon-star.js";
import React from 'react';

export type EuiIconStarEvents = NonNullable<unknown>;

export const EuiIconStar: StencilReactComponent<EuiIconStarElement, EuiIconStarEvents> = /*@__PURE__*/ createComponent<EuiIconStarElement, EuiIconStarEvents>({
    tagName: 'eui-icon-star',
    elementClass: EuiIconStarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconStarEvents,
    defineCustomElement: defineEuiIconStar
});
