'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChartPie as EuiIconChartPieElement, defineCustomElement as defineEuiIconChartPie } from "ensemble-ui/dist/components/eui-icon-chart-pie.js";
import React from 'react';

export type EuiIconChartPieEvents = NonNullable<unknown>;

export const EuiIconChartPie: StencilReactComponent<EuiIconChartPieElement, EuiIconChartPieEvents> = /*@__PURE__*/ createComponent<EuiIconChartPieElement, EuiIconChartPieEvents>({
    tagName: 'eui-icon-chart-pie',
    elementClass: EuiIconChartPieElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChartPieEvents,
    defineCustomElement: defineEuiIconChartPie
});
