'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowDownHeavy as EuiIconArrowDownHeavyElement, defineCustomElement as defineEuiIconArrowDownHeavy } from "ensemble-ui/dist/components/eui-icon-arrow-down-heavy.js";
import React from 'react';

export type EuiIconArrowDownHeavyEvents = NonNullable<unknown>;

export const EuiIconArrowDownHeavy: StencilReactComponent<EuiIconArrowDownHeavyElement, EuiIconArrowDownHeavyEvents> = /*@__PURE__*/ createComponent<EuiIconArrowDownHeavyElement, EuiIconArrowDownHeavyEvents>({
    tagName: 'eui-icon-arrow-down-heavy',
    elementClass: EuiIconArrowDownHeavyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowDownHeavyEvents,
    defineCustomElement: defineEuiIconArrowDownHeavy
});
