'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiCheckboxCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiCheckbox as EuiCheckboxElement, defineCustomElement as defineEuiCheckbox } from "ensemble-ui/dist/components/eui-checkbox.js";

export type EuiCheckboxEvents = { onValueChange: EventName<EuiCheckboxCustomEvent<'null' | 'false' | 'partial' | 'true'>> };

export const EuiCheckbox: StencilReactComponent<EuiCheckboxElement, EuiCheckboxEvents, Components.EuiCheckbox> = /*@__PURE__*/ createComponent<EuiCheckboxElement, EuiCheckboxEvents, Components.EuiCheckbox>({
    tagName: 'eui-checkbox',
    elementClass: EuiCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as EuiCheckboxEvents,
    defineCustomElement: defineEuiCheckbox
});
