'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPrinter as EuiIconPrinterElement, defineCustomElement as defineEuiIconPrinter } from "ensemble-ui/dist/components/eui-icon-printer.js";
import React from 'react';

export type EuiIconPrinterEvents = NonNullable<unknown>;

export const EuiIconPrinter: StencilReactComponent<EuiIconPrinterElement, EuiIconPrinterEvents> = /*@__PURE__*/ createComponent<EuiIconPrinterElement, EuiIconPrinterEvents>({
    tagName: 'eui-icon-printer',
    elementClass: EuiIconPrinterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPrinterEvents,
    defineCustomElement: defineEuiIconPrinter
});
