'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowLongUp as EuiIconArrowLongUpElement, defineCustomElement as defineEuiIconArrowLongUp } from "ensemble-ui/dist/components/eui-icon-arrow-long-up.js";
import React from 'react';

export type EuiIconArrowLongUpEvents = NonNullable<unknown>;

export const EuiIconArrowLongUp: StencilReactComponent<EuiIconArrowLongUpElement, EuiIconArrowLongUpEvents> = /*@__PURE__*/ createComponent<EuiIconArrowLongUpElement, EuiIconArrowLongUpEvents>({
    tagName: 'eui-icon-arrow-long-up',
    elementClass: EuiIconArrowLongUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowLongUpEvents,
    defineCustomElement: defineEuiIconArrowLongUp
});
