'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconQrCode as EuiIconQrCodeElement, defineCustomElement as defineEuiIconQrCode } from "ensemble-ui/dist/components/eui-icon-qr-code.js";
import React from 'react';

export type EuiIconQrCodeEvents = NonNullable<unknown>;

export const EuiIconQrCode: StencilReactComponent<EuiIconQrCodeElement, EuiIconQrCodeEvents> = /*@__PURE__*/ createComponent<EuiIconQrCodeElement, EuiIconQrCodeEvents>({
    tagName: 'eui-icon-qr-code',
    elementClass: EuiIconQrCodeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconQrCodeEvents,
    defineCustomElement: defineEuiIconQrCode
});
