'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconScissors as EuiIconScissorsElement, defineCustomElement as defineEuiIconScissors } from "ensemble-ui/dist/components/eui-icon-scissors.js";
import React from 'react';

export type EuiIconScissorsEvents = NonNullable<unknown>;

export const EuiIconScissors: StencilReactComponent<EuiIconScissorsElement, EuiIconScissorsEvents> = /*@__PURE__*/ createComponent<EuiIconScissorsElement, EuiIconScissorsEvents>({
    tagName: 'eui-icon-scissors',
    elementClass: EuiIconScissorsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconScissorsEvents,
    defineCustomElement: defineEuiIconScissors
});
