'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconH1 as EuiIconH1Element, defineCustomElement as defineEuiIconH1 } from "ensemble-ui/dist/components/eui-icon-h1.js";
import React from 'react';

export type EuiIconH1Events = NonNullable<unknown>;

export const EuiIconH1: StencilReactComponent<EuiIconH1Element, EuiIconH1Events> = /*@__PURE__*/ createComponent<EuiIconH1Element, EuiIconH1Events>({
    tagName: 'eui-icon-h1',
    elementClass: EuiIconH1Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconH1Events,
    defineCustomElement: defineEuiIconH1
});
