'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBackward as EuiIconBackwardElement, defineCustomElement as defineEuiIconBackward } from "ensemble-ui/dist/components/eui-icon-backward.js";
import React from 'react';

export type EuiIconBackwardEvents = NonNullable<unknown>;

export const EuiIconBackward: StencilReactComponent<EuiIconBackwardElement, EuiIconBackwardEvents> = /*@__PURE__*/ createComponent<EuiIconBackwardElement, EuiIconBackwardEvents>({
    tagName: 'eui-icon-backward',
    elementClass: EuiIconBackwardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBackwardEvents,
    defineCustomElement: defineEuiIconBackward
});
