'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconDocumentMinus as EuiIconDocumentMinusElement, defineCustomElement as defineEuiIconDocumentMinus } from "ensemble-ui/dist/components/eui-icon-document-minus.js";
import React from 'react';

export type EuiIconDocumentMinusEvents = NonNullable<unknown>;

export const EuiIconDocumentMinus: StencilReactComponent<EuiIconDocumentMinusElement, EuiIconDocumentMinusEvents> = /*@__PURE__*/ createComponent<EuiIconDocumentMinusElement, EuiIconDocumentMinusEvents>({
    tagName: 'eui-icon-document-minus',
    elementClass: EuiIconDocumentMinusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconDocumentMinusEvents,
    defineCustomElement: defineEuiIconDocumentMinus
});
