'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiStepper as EuiStepperElement, defineCustomElement as defineEuiStepper } from "ensemble-ui/dist/components/eui-stepper.js";
import React from 'react';

export type EuiStepperEvents = { onStepSelect: EventName<CustomEvent<number>> };

export const EuiStepper: StencilReactComponent<EuiStepperElement, EuiStepperEvents> = /*@__PURE__*/ createComponent<EuiStepperElement, EuiStepperEvents>({
    tagName: 'eui-stepper',
    elementClass: EuiStepperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onStepSelect: 'stepSelect' } as EuiStepperEvents,
    defineCustomElement: defineEuiStepper
});
