'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArchiveBoxXMark as EuiIconArchiveBoxXMarkElement, defineCustomElement as defineEuiIconArchiveBoxXMark } from "ensemble-ui/dist/components/eui-icon-archive-box-x-mark.js";
import React from 'react';

export type EuiIconArchiveBoxXMarkEvents = NonNullable<unknown>;

export const EuiIconArchiveBoxXMark: StencilReactComponent<EuiIconArchiveBoxXMarkElement, EuiIconArchiveBoxXMarkEvents> = /*@__PURE__*/ createComponent<EuiIconArchiveBoxXMarkElement, EuiIconArchiveBoxXMarkEvents>({
    tagName: 'eui-icon-archive-box-x-mark',
    elementClass: EuiIconArchiveBoxXMarkElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArchiveBoxXMarkEvents,
    defineCustomElement: defineEuiIconArchiveBoxXMark
});
