'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFire as EuiIconFireElement, defineCustomElement as defineEuiIconFire } from "ensemble-ui/dist/components/eui-icon-fire.js";
import React from 'react';

export type EuiIconFireEvents = NonNullable<unknown>;

export const EuiIconFire: StencilReactComponent<EuiIconFireElement, EuiIconFireEvents> = /*@__PURE__*/ createComponent<EuiIconFireElement, EuiIconFireEvents>({
    tagName: 'eui-icon-fire',
    elementClass: EuiIconFireElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFireEvents,
    defineCustomElement: defineEuiIconFire
});
