'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconShieldCheck as EuiIconShieldCheckElement, defineCustomElement as defineEuiIconShieldCheck } from "ensemble-ui/dist/components/eui-icon-shield-check.js";
import React from 'react';

export type EuiIconShieldCheckEvents = NonNullable<unknown>;

export const EuiIconShieldCheck: StencilReactComponent<EuiIconShieldCheckElement, EuiIconShieldCheckEvents> = /*@__PURE__*/ createComponent<EuiIconShieldCheckElement, EuiIconShieldCheckEvents>({
    tagName: 'eui-icon-shield-check',
    elementClass: EuiIconShieldCheckElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconShieldCheckEvents,
    defineCustomElement: defineEuiIconShieldCheck
});
