'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPhoto as EuiIconPhotoElement, defineCustomElement as defineEuiIconPhoto } from "ensemble-ui/dist/components/eui-icon-photo.js";
import React from 'react';

export type EuiIconPhotoEvents = NonNullable<unknown>;

export const EuiIconPhoto: StencilReactComponent<EuiIconPhotoElement, EuiIconPhotoEvents> = /*@__PURE__*/ createComponent<EuiIconPhotoElement, EuiIconPhotoEvents>({
    tagName: 'eui-icon-photo',
    elementClass: EuiIconPhotoElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPhotoEvents,
    defineCustomElement: defineEuiIconPhoto
});
