'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCurrencyBangladeshi as EuiIconCurrencyBangladeshiElement, defineCustomElement as defineEuiIconCurrencyBangladeshi } from "ensemble-ui/dist/components/eui-icon-currency-bangladeshi.js";
import React from 'react';

export type EuiIconCurrencyBangladeshiEvents = NonNullable<unknown>;

export const EuiIconCurrencyBangladeshi: StencilReactComponent<EuiIconCurrencyBangladeshiElement, EuiIconCurrencyBangladeshiEvents> = /*@__PURE__*/ createComponent<EuiIconCurrencyBangladeshiElement, EuiIconCurrencyBangladeshiEvents>({
    tagName: 'eui-icon-currency-bangladeshi',
    elementClass: EuiIconCurrencyBangladeshiElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCurrencyBangladeshiEvents,
    defineCustomElement: defineEuiIconCurrencyBangladeshi
});
