'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconEyeSlash as EuiIconEyeSlashElement, defineCustomElement as defineEuiIconEyeSlash } from "ensemble-ui/dist/components/eui-icon-eye-slash.js";
import React from 'react';

export type EuiIconEyeSlashEvents = NonNullable<unknown>;

export const EuiIconEyeSlash: StencilReactComponent<EuiIconEyeSlashElement, EuiIconEyeSlashEvents> = /*@__PURE__*/ createComponent<EuiIconEyeSlashElement, EuiIconEyeSlashEvents>({
    tagName: 'eui-icon-eye-slash',
    elementClass: EuiIconEyeSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconEyeSlashEvents,
    defineCustomElement: defineEuiIconEyeSlash
});
