'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowDownRight as EuiIconArrowDownRightElement, defineCustomElement as defineEuiIconArrowDownRight } from "ensemble-ui/dist/components/eui-icon-arrow-down-right.js";
import React from 'react';

export type EuiIconArrowDownRightEvents = NonNullable<unknown>;

export const EuiIconArrowDownRight: StencilReactComponent<EuiIconArrowDownRightElement, EuiIconArrowDownRightEvents> = /*@__PURE__*/ createComponent<EuiIconArrowDownRightElement, EuiIconArrowDownRightEvents>({
    tagName: 'eui-icon-arrow-down-right',
    elementClass: EuiIconArrowDownRightElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowDownRightEvents,
    defineCustomElement: defineEuiIconArrowDownRight
});
