'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowLongLeft as EuiIconArrowLongLeftElement, defineCustomElement as defineEuiIconArrowLongLeft } from "ensemble-ui/dist/components/eui-icon-arrow-long-left.js";
import React from 'react';

export type EuiIconArrowLongLeftEvents = NonNullable<unknown>;

export const EuiIconArrowLongLeft: StencilReactComponent<EuiIconArrowLongLeftElement, EuiIconArrowLongLeftEvents> = /*@__PURE__*/ createComponent<EuiIconArrowLongLeftElement, EuiIconArrowLongLeftEvents>({
    tagName: 'eui-icon-arrow-long-left',
    elementClass: EuiIconArrowLongLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowLongLeftEvents,
    defineCustomElement: defineEuiIconArrowLongLeft
});
