'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBars3 as EuiIconBars3Element, defineCustomElement as defineEuiIconBars3 } from "ensemble-ui/dist/components/eui-icon-bars-3.js";
import React from 'react';

export type EuiIconBars3Events = NonNullable<unknown>;

export const EuiIconBars3: StencilReactComponent<EuiIconBars3Element, EuiIconBars3Events> = /*@__PURE__*/ createComponent<EuiIconBars3Element, EuiIconBars3Events>({
    tagName: 'eui-icon-bars-3',
    elementClass: EuiIconBars3Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBars3Events,
    defineCustomElement: defineEuiIconBars3
});
