'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPaintBrush as EuiIconPaintBrushElement, defineCustomElement as defineEuiIconPaintBrush } from "ensemble-ui/dist/components/eui-icon-paint-brush.js";
import React from 'react';

export type EuiIconPaintBrushEvents = NonNullable<unknown>;

export const EuiIconPaintBrush: StencilReactComponent<EuiIconPaintBrushElement, EuiIconPaintBrushEvents> = /*@__PURE__*/ createComponent<EuiIconPaintBrushElement, EuiIconPaintBrushEvents>({
    tagName: 'eui-icon-paint-brush',
    elementClass: EuiIconPaintBrushElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPaintBrushEvents,
    defineCustomElement: defineEuiIconPaintBrush
});
