'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPlusCircle as EuiIconPlusCircleElement, defineCustomElement as defineEuiIconPlusCircle } from "ensemble-ui/dist/components/eui-icon-plus-circle.js";
import React from 'react';

export type EuiIconPlusCircleEvents = NonNullable<unknown>;

export const EuiIconPlusCircle: StencilReactComponent<EuiIconPlusCircleElement, EuiIconPlusCircleEvents> = /*@__PURE__*/ createComponent<EuiIconPlusCircleElement, EuiIconPlusCircleEvents>({
    tagName: 'eui-icon-plus-circle',
    elementClass: EuiIconPlusCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPlusCircleEvents,
    defineCustomElement: defineEuiIconPlusCircle
});
