'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPencilSquare as EuiIconPencilSquareElement, defineCustomElement as defineEuiIconPencilSquare } from "ensemble-ui/dist/components/eui-icon-pencil-square.js";
import React from 'react';

export type EuiIconPencilSquareEvents = NonNullable<unknown>;

export const EuiIconPencilSquare: StencilReactComponent<EuiIconPencilSquareElement, EuiIconPencilSquareEvents> = /*@__PURE__*/ createComponent<EuiIconPencilSquareElement, EuiIconPencilSquareEvents>({
    tagName: 'eui-icon-pencil-square',
    elementClass: EuiIconPencilSquareElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPencilSquareEvents,
    defineCustomElement: defineEuiIconPencilSquare
});
