'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconBellSlash as EuiIconBellSlashElement, defineCustomElement as defineEuiIconBellSlash } from "ensemble-ui/dist/components/eui-icon-bell-slash.js";
import React from 'react';

export type EuiIconBellSlashEvents = NonNullable<unknown>;

export const EuiIconBellSlash: StencilReactComponent<EuiIconBellSlashElement, EuiIconBellSlashEvents> = /*@__PURE__*/ createComponent<EuiIconBellSlashElement, EuiIconBellSlashEvents>({
    tagName: 'eui-icon-bell-slash',
    elementClass: EuiIconBellSlashElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconBellSlashEvents,
    defineCustomElement: defineEuiIconBellSlash
});
