'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFolderMinus as EuiIconFolderMinusElement, defineCustomElement as defineEuiIconFolderMinus } from "ensemble-ui/dist/components/eui-icon-folder-minus.js";
import React from 'react';

export type EuiIconFolderMinusEvents = NonNullable<unknown>;

export const EuiIconFolderMinus: StencilReactComponent<EuiIconFolderMinusElement, EuiIconFolderMinusEvents> = /*@__PURE__*/ createComponent<EuiIconFolderMinusElement, EuiIconFolderMinusEvents>({
    tagName: 'eui-icon-folder-minus',
    elementClass: EuiIconFolderMinusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFolderMinusEvents,
    defineCustomElement: defineEuiIconFolderMinus
});
