'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCake as EuiIconCakeElement, defineCustomElement as defineEuiIconCake } from "ensemble-ui/dist/components/eui-icon-cake.js";
import React from 'react';

export type EuiIconCakeEvents = NonNullable<unknown>;

export const EuiIconCake: StencilReactComponent<EuiIconCakeElement, EuiIconCakeEvents> = /*@__PURE__*/ createComponent<EuiIconCakeElement, EuiIconCakeEvents>({
    tagName: 'eui-icon-cake',
    elementClass: EuiIconCakeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCakeEvents,
    defineCustomElement: defineEuiIconCake
});
