'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconClipboard as EuiIconClipboardElement, defineCustomElement as defineEuiIconClipboard } from "ensemble-ui/dist/components/eui-icon-clipboard.js";
import React from 'react';

export type EuiIconClipboardEvents = NonNullable<unknown>;

export const EuiIconClipboard: StencilReactComponent<EuiIconClipboardElement, EuiIconClipboardEvents> = /*@__PURE__*/ createComponent<EuiIconClipboardElement, EuiIconClipboardEvents>({
    tagName: 'eui-icon-clipboard',
    elementClass: EuiIconClipboardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconClipboardEvents,
    defineCustomElement: defineEuiIconClipboard
});
