'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowDownOnSquare as EuiIconArrowDownOnSquareElement, defineCustomElement as defineEuiIconArrowDownOnSquare } from "ensemble-ui/dist/components/eui-icon-arrow-down-on-square.js";
import React from 'react';

export type EuiIconArrowDownOnSquareEvents = NonNullable<unknown>;

export const EuiIconArrowDownOnSquare: StencilReactComponent<EuiIconArrowDownOnSquareElement, EuiIconArrowDownOnSquareEvents> = /*@__PURE__*/ createComponent<EuiIconArrowDownOnSquareElement, EuiIconArrowDownOnSquareEvents>({
    tagName: 'eui-icon-arrow-down-on-square',
    elementClass: EuiIconArrowDownOnSquareElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowDownOnSquareEvents,
    defineCustomElement: defineEuiIconArrowDownOnSquare
});
