'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconUser as EuiIconUserElement, defineCustomElement as defineEuiIconUser } from "ensemble-ui/dist/components/eui-icon-user.js";
import React from 'react';

export type EuiIconUserEvents = NonNullable<unknown>;

export const EuiIconUser: StencilReactComponent<EuiIconUserElement, EuiIconUserEvents> = /*@__PURE__*/ createComponent<EuiIconUserElement, EuiIconUserEvents>({
    tagName: 'eui-icon-user',
    elementClass: EuiIconUserElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconUserEvents,
    defineCustomElement: defineEuiIconUser
});
