'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCloudArrowUp as EuiIconCloudArrowUpElement, defineCustomElement as defineEuiIconCloudArrowUp } from "ensemble-ui/dist/components/eui-icon-cloud-arrow-up.js";
import React from 'react';

export type EuiIconCloudArrowUpEvents = NonNullable<unknown>;

export const EuiIconCloudArrowUp: StencilReactComponent<EuiIconCloudArrowUpElement, EuiIconCloudArrowUpEvents> = /*@__PURE__*/ createComponent<EuiIconCloudArrowUpElement, EuiIconCloudArrowUpEvents>({
    tagName: 'eui-icon-cloud-arrow-up',
    elementClass: EuiIconCloudArrowUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCloudArrowUpEvents,
    defineCustomElement: defineEuiIconCloudArrowUp
});
