'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowUp as EuiIconArrowUpElement, defineCustomElement as defineEuiIconArrowUp } from "ensemble-ui/dist/components/eui-icon-arrow-up.js";
import React from 'react';

export type EuiIconArrowUpEvents = NonNullable<unknown>;

export const EuiIconArrowUp: StencilReactComponent<EuiIconArrowUpElement, EuiIconArrowUpEvents> = /*@__PURE__*/ createComponent<EuiIconArrowUpElement, EuiIconArrowUpEvents>({
    tagName: 'eui-icon-arrow-up',
    elementClass: EuiIconArrowUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowUpEvents,
    defineCustomElement: defineEuiIconArrowUp
});
