'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconRocketLaunch as EuiIconRocketLaunchElement, defineCustomElement as defineEuiIconRocketLaunch } from "ensemble-ui/dist/components/eui-icon-rocket-launch.js";
import React from 'react';

export type EuiIconRocketLaunchEvents = NonNullable<unknown>;

export const EuiIconRocketLaunch: StencilReactComponent<EuiIconRocketLaunchElement, EuiIconRocketLaunchEvents> = /*@__PURE__*/ createComponent<EuiIconRocketLaunchElement, EuiIconRocketLaunchEvents>({
    tagName: 'eui-icon-rocket-launch',
    elementClass: EuiIconRocketLaunchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconRocketLaunchEvents,
    defineCustomElement: defineEuiIconRocketLaunch
});
