'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCheckCircle as EuiIconCheckCircleElement, defineCustomElement as defineEuiIconCheckCircle } from "ensemble-ui/dist/components/eui-icon-check-circle.js";
import React from 'react';

export type EuiIconCheckCircleEvents = NonNullable<unknown>;

export const EuiIconCheckCircle: StencilReactComponent<EuiIconCheckCircleElement, EuiIconCheckCircleEvents> = /*@__PURE__*/ createComponent<EuiIconCheckCircleElement, EuiIconCheckCircleEvents>({
    tagName: 'eui-icon-check-circle',
    elementClass: EuiIconCheckCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCheckCircleEvents,
    defineCustomElement: defineEuiIconCheckCircle
});
