'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowRightEndOnRectangle as EuiIconArrowRightEndOnRectangleElement, defineCustomElement as defineEuiIconArrowRightEndOnRectangle } from "ensemble-ui/dist/components/eui-icon-arrow-right-end-on-rectangle.js";
import React from 'react';

export type EuiIconArrowRightEndOnRectangleEvents = NonNullable<unknown>;

export const EuiIconArrowRightEndOnRectangle: StencilReactComponent<EuiIconArrowRightEndOnRectangleElement, EuiIconArrowRightEndOnRectangleEvents> = /*@__PURE__*/ createComponent<EuiIconArrowRightEndOnRectangleElement, EuiIconArrowRightEndOnRectangleEvents>({
    tagName: 'eui-icon-arrow-right-end-on-rectangle',
    elementClass: EuiIconArrowRightEndOnRectangleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowRightEndOnRectangleEvents,
    defineCustomElement: defineEuiIconArrowRightEndOnRectangle
});
