'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconLockClosed as EuiIconLockClosedElement, defineCustomElement as defineEuiIconLockClosed } from "ensemble-ui/dist/components/eui-icon-lock-closed.js";
import React from 'react';

export type EuiIconLockClosedEvents = NonNullable<unknown>;

export const EuiIconLockClosed: StencilReactComponent<EuiIconLockClosedElement, EuiIconLockClosedEvents> = /*@__PURE__*/ createComponent<EuiIconLockClosedElement, EuiIconLockClosedEvents>({
    tagName: 'eui-icon-lock-closed',
    elementClass: EuiIconLockClosedElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconLockClosedEvents,
    defineCustomElement: defineEuiIconLockClosed
});
