'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFunnel as EuiIconFunnelElement, defineCustomElement as defineEuiIconFunnel } from "ensemble-ui/dist/components/eui-icon-funnel.js";
import React from 'react';

export type EuiIconFunnelEvents = NonNullable<unknown>;

export const EuiIconFunnel: StencilReactComponent<EuiIconFunnelElement, EuiIconFunnelEvents> = /*@__PURE__*/ createComponent<EuiIconFunnelElement, EuiIconFunnelEvents>({
    tagName: 'eui-icon-funnel',
    elementClass: EuiIconFunnelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFunnelEvents,
    defineCustomElement: defineEuiIconFunnel
});
