'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChatBubbleLeft as EuiIconChatBubbleLeftElement, defineCustomElement as defineEuiIconChatBubbleLeft } from "ensemble-ui/dist/components/eui-icon-chat-bubble-left.js";
import React from 'react';

export type EuiIconChatBubbleLeftEvents = NonNullable<unknown>;

export const EuiIconChatBubbleLeft: StencilReactComponent<EuiIconChatBubbleLeftElement, EuiIconChatBubbleLeftEvents> = /*@__PURE__*/ createComponent<EuiIconChatBubbleLeftElement, EuiIconChatBubbleLeftEvents>({
    tagName: 'eui-icon-chat-bubble-left',
    elementClass: EuiIconChatBubbleLeftElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChatBubbleLeftEvents,
    defineCustomElement: defineEuiIconChatBubbleLeft
});
