'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiChips as EuiChipsElement, defineCustomElement as defineEuiChips } from "ensemble-ui/dist/components/eui-chips.js";
import React from 'react';

export type EuiChipsEvents = { onItemSelected: EventName<CustomEvent<any>> };

export const EuiChips: StencilReactComponent<EuiChipsElement, EuiChipsEvents> = /*@__PURE__*/ createComponent<EuiChipsElement, EuiChipsEvents>({
    tagName: 'eui-chips',
    elementClass: EuiChipsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onItemSelected: 'itemSelected' } as EuiChipsEvents,
    defineCustomElement: defineEuiChips
});
