'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTurnRightDown as EuiIconArrowTurnRightDownElement, defineCustomElement as defineEuiIconArrowTurnRightDown } from "ensemble-ui/dist/components/eui-icon-arrow-turn-right-down.js";
import React from 'react';

export type EuiIconArrowTurnRightDownEvents = NonNullable<unknown>;

export const EuiIconArrowTurnRightDown: StencilReactComponent<EuiIconArrowTurnRightDownElement, EuiIconArrowTurnRightDownEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTurnRightDownElement, EuiIconArrowTurnRightDownEvents>({
    tagName: 'eui-icon-arrow-turn-right-down',
    elementClass: EuiIconArrowTurnRightDownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTurnRightDownEvents,
    defineCustomElement: defineEuiIconArrowTurnRightDown
});
