'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconFaceSmile as EuiIconFaceSmileElement, defineCustomElement as defineEuiIconFaceSmile } from "ensemble-ui/dist/components/eui-icon-face-smile.js";
import React from 'react';

export type EuiIconFaceSmileEvents = NonNullable<unknown>;

export const EuiIconFaceSmile: StencilReactComponent<EuiIconFaceSmileElement, EuiIconFaceSmileEvents> = /*@__PURE__*/ createComponent<EuiIconFaceSmileElement, EuiIconFaceSmileEvents>({
    tagName: 'eui-icon-face-smile',
    elementClass: EuiIconFaceSmileElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconFaceSmileEvents,
    defineCustomElement: defineEuiIconFaceSmile
});
