'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPlus as EuiIconPlusElement, defineCustomElement as defineEuiIconPlus } from "ensemble-ui/dist/components/eui-icon-plus.js";
import React from 'react';

export type EuiIconPlusEvents = NonNullable<unknown>;

export const EuiIconPlus: StencilReactComponent<EuiIconPlusElement, EuiIconPlusEvents> = /*@__PURE__*/ createComponent<EuiIconPlusElement, EuiIconPlusEvents>({
    tagName: 'eui-icon-plus',
    elementClass: EuiIconPlusElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPlusEvents,
    defineCustomElement: defineEuiIconPlus
});
