'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiYear as EuiYearElement, defineCustomElement as defineEuiYear } from "ensemble-ui/dist/components/eui-year.js";
import React from 'react';

export type EuiYearEvents = NonNullable<unknown>;

export const EuiYear: StencilReactComponent<EuiYearElement, EuiYearEvents> = /*@__PURE__*/ createComponent<EuiYearElement, EuiYearEvents>({
    tagName: 'eui-year',
    elementClass: EuiYearElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiYearEvents,
    defineCustomElement: defineEuiYear
});
