'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCursorArrowRays as EuiIconCursorArrowRaysElement, defineCustomElement as defineEuiIconCursorArrowRays } from "ensemble-ui/dist/components/eui-icon-cursor-arrow-rays.js";
import React from 'react';

export type EuiIconCursorArrowRaysEvents = NonNullable<unknown>;

export const EuiIconCursorArrowRays: StencilReactComponent<EuiIconCursorArrowRaysElement, EuiIconCursorArrowRaysEvents> = /*@__PURE__*/ createComponent<EuiIconCursorArrowRaysElement, EuiIconCursorArrowRaysEvents>({
    tagName: 'eui-icon-cursor-arrow-rays',
    elementClass: EuiIconCursorArrowRaysElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCursorArrowRaysEvents,
    defineCustomElement: defineEuiIconCursorArrowRays
});
