'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconServerStack as EuiIconServerStackElement, defineCustomElement as defineEuiIconServerStack } from "ensemble-ui/dist/components/eui-icon-server-stack.js";
import React from 'react';

export type EuiIconServerStackEvents = NonNullable<unknown>;

export const EuiIconServerStack: StencilReactComponent<EuiIconServerStackElement, EuiIconServerStackEvents> = /*@__PURE__*/ createComponent<EuiIconServerStackElement, EuiIconServerStackEvents>({
    tagName: 'eui-icon-server-stack',
    elementClass: EuiIconServerStackElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconServerStackEvents,
    defineCustomElement: defineEuiIconServerStack
});
