'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowTrendingUp as EuiIconArrowTrendingUpElement, defineCustomElement as defineEuiIconArrowTrendingUp } from "ensemble-ui/dist/components/eui-icon-arrow-trending-up.js";
import React from 'react';

export type EuiIconArrowTrendingUpEvents = NonNullable<unknown>;

export const EuiIconArrowTrendingUp: StencilReactComponent<EuiIconArrowTrendingUpElement, EuiIconArrowTrendingUpEvents> = /*@__PURE__*/ createComponent<EuiIconArrowTrendingUpElement, EuiIconArrowTrendingUpEvents>({
    tagName: 'eui-icon-arrow-trending-up',
    elementClass: EuiIconArrowTrendingUpElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowTrendingUpEvents,
    defineCustomElement: defineEuiIconArrowTrendingUp
});
