'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type EuiCalendarNavigatorCustomEvent } from "ensemble-ui";
import { EuiCalendarNavigator as EuiCalendarNavigatorElement, defineCustomElement as defineEuiCalendarNavigator } from "ensemble-ui/dist/components/eui-calendar-navigator.js";
import React from 'react';

export type EuiCalendarNavigatorEvents = { onDateChange: EventName<EuiCalendarNavigatorCustomEvent<Date>> };

export const EuiCalendarNavigator: StencilReactComponent<EuiCalendarNavigatorElement, EuiCalendarNavigatorEvents> = /*@__PURE__*/ createComponent<EuiCalendarNavigatorElement, EuiCalendarNavigatorEvents>({
    tagName: 'eui-calendar-navigator',
    elementClass: EuiCalendarNavigatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDateChange: 'dateChange' } as EuiCalendarNavigatorEvents,
    defineCustomElement: defineEuiCalendarNavigator
});
