'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type EuiSliderCustomEvent } from "ensemble-ui";
import type { Components } from "ensemble-ui/dist/components";
import { EuiSlider as EuiSliderElement, defineCustomElement as defineEuiSlider } from "ensemble-ui/dist/components/eui-slider.js";

export type EuiSliderEvents = { onChange: EventName<EuiSliderCustomEvent<number>> };

export const EuiSlider: StencilReactComponent<EuiSliderElement, EuiSliderEvents, Components.EuiSlider> = /*@__PURE__*/ createComponent<EuiSliderElement, EuiSliderEvents, Components.EuiSlider>({
    tagName: 'eui-slider',
    elementClass: EuiSliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChange: 'change' } as EuiSliderEvents,
    defineCustomElement: defineEuiSlider
});
