'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChatBubbleBottomCenter as EuiIconChatBubbleBottomCenterElement, defineCustomElement as defineEuiIconChatBubbleBottomCenter } from "ensemble-ui/dist/components/eui-icon-chat-bubble-bottom-center.js";
import React from 'react';

export type EuiIconChatBubbleBottomCenterEvents = NonNullable<unknown>;

export const EuiIconChatBubbleBottomCenter: StencilReactComponent<EuiIconChatBubbleBottomCenterElement, EuiIconChatBubbleBottomCenterEvents> = /*@__PURE__*/ createComponent<EuiIconChatBubbleBottomCenterElement, EuiIconChatBubbleBottomCenterEvents>({
    tagName: 'eui-icon-chat-bubble-bottom-center',
    elementClass: EuiIconChatBubbleBottomCenterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChatBubbleBottomCenterEvents,
    defineCustomElement: defineEuiIconChatBubbleBottomCenter
});
