'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconItalic as EuiIconItalicElement, defineCustomElement as defineEuiIconItalic } from "ensemble-ui/dist/components/eui-icon-italic.js";
import React from 'react';

export type EuiIconItalicEvents = NonNullable<unknown>;

export const EuiIconItalic: StencilReactComponent<EuiIconItalicElement, EuiIconItalicEvents> = /*@__PURE__*/ createComponent<EuiIconItalicElement, EuiIconItalicEvents>({
    tagName: 'eui-icon-italic',
    elementClass: EuiIconItalicElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconItalicEvents,
    defineCustomElement: defineEuiIconItalic
});
