'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPause as EuiIconPauseElement, defineCustomElement as defineEuiIconPause } from "ensemble-ui/dist/components/eui-icon-pause.js";
import React from 'react';

export type EuiIconPauseEvents = NonNullable<unknown>;

export const EuiIconPause: StencilReactComponent<EuiIconPauseElement, EuiIconPauseEvents> = /*@__PURE__*/ createComponent<EuiIconPauseElement, EuiIconPauseEvents>({
    tagName: 'eui-icon-pause',
    elementClass: EuiIconPauseElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPauseEvents,
    defineCustomElement: defineEuiIconPause
});
