'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconChatBubbleLeftEllipsis as EuiIconChatBubbleLeftEllipsisElement, defineCustomElement as defineEuiIconChatBubbleLeftEllipsis } from "ensemble-ui/dist/components/eui-icon-chat-bubble-left-ellipsis.js";
import React from 'react';

export type EuiIconChatBubbleLeftEllipsisEvents = NonNullable<unknown>;

export const EuiIconChatBubbleLeftEllipsis: StencilReactComponent<EuiIconChatBubbleLeftEllipsisElement, EuiIconChatBubbleLeftEllipsisEvents> = /*@__PURE__*/ createComponent<EuiIconChatBubbleLeftEllipsisElement, EuiIconChatBubbleLeftEllipsisEvents>({
    tagName: 'eui-icon-chat-bubble-left-ellipsis',
    elementClass: EuiIconChatBubbleLeftEllipsisElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconChatBubbleLeftEllipsisEvents,
    defineCustomElement: defineEuiIconChatBubbleLeftEllipsis
});
