'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconViewfinderCircle as EuiIconViewfinderCircleElement, defineCustomElement as defineEuiIconViewfinderCircle } from "ensemble-ui/dist/components/eui-icon-viewfinder-circle.js";
import React from 'react';

export type EuiIconViewfinderCircleEvents = NonNullable<unknown>;

export const EuiIconViewfinderCircle: StencilReactComponent<EuiIconViewfinderCircleElement, EuiIconViewfinderCircleEvents> = /*@__PURE__*/ createComponent<EuiIconViewfinderCircleElement, EuiIconViewfinderCircleEvents>({
    tagName: 'eui-icon-viewfinder-circle',
    elementClass: EuiIconViewfinderCircleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconViewfinderCircleEvents,
    defineCustomElement: defineEuiIconViewfinderCircle
});
