'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconCursorArrowRipple as EuiIconCursorArrowRippleElement, defineCustomElement as defineEuiIconCursorArrowRipple } from "ensemble-ui/dist/components/eui-icon-cursor-arrow-ripple.js";
import React from 'react';

export type EuiIconCursorArrowRippleEvents = NonNullable<unknown>;

export const EuiIconCursorArrowRipple: StencilReactComponent<EuiIconCursorArrowRippleElement, EuiIconCursorArrowRippleEvents> = /*@__PURE__*/ createComponent<EuiIconCursorArrowRippleElement, EuiIconCursorArrowRippleEvents>({
    tagName: 'eui-icon-cursor-arrow-ripple',
    elementClass: EuiIconCursorArrowRippleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconCursorArrowRippleEvents,
    defineCustomElement: defineEuiIconCursorArrowRipple
});
