'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconWrenchScrewdriver as EuiIconWrenchScrewdriverElement, defineCustomElement as defineEuiIconWrenchScrewdriver } from "ensemble-ui/dist/components/eui-icon-wrench-screwdriver.js";
import React from 'react';

export type EuiIconWrenchScrewdriverEvents = NonNullable<unknown>;

export const EuiIconWrenchScrewdriver: StencilReactComponent<EuiIconWrenchScrewdriverElement, EuiIconWrenchScrewdriverEvents> = /*@__PURE__*/ createComponent<EuiIconWrenchScrewdriverElement, EuiIconWrenchScrewdriverEvents>({
    tagName: 'eui-icon-wrench-screwdriver',
    elementClass: EuiIconWrenchScrewdriverElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconWrenchScrewdriverEvents,
    defineCustomElement: defineEuiIconWrenchScrewdriver
});
