'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconH3 as EuiIconH3Element, defineCustomElement as defineEuiIconH3 } from "ensemble-ui/dist/components/eui-icon-h3.js";
import React from 'react';

export type EuiIconH3Events = NonNullable<unknown>;

export const EuiIconH3: StencilReactComponent<EuiIconH3Element, EuiIconH3Events> = /*@__PURE__*/ createComponent<EuiIconH3Element, EuiIconH3Events>({
    tagName: 'eui-icon-h3',
    elementClass: EuiIconH3Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconH3Events,
    defineCustomElement: defineEuiIconH3
});
