'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconSquare3Stack3d as EuiIconSquare3Stack3dElement, defineCustomElement as defineEuiIconSquare3Stack3d } from "ensemble-ui/dist/components/eui-icon-square-3-stack-3d.js";
import React from 'react';

export type EuiIconSquare3Stack3dEvents = NonNullable<unknown>;

export const EuiIconSquare3Stack3d: StencilReactComponent<EuiIconSquare3Stack3dElement, EuiIconSquare3Stack3dEvents> = /*@__PURE__*/ createComponent<EuiIconSquare3Stack3dElement, EuiIconSquare3Stack3dEvents>({
    tagName: 'eui-icon-square-3-stack-3d',
    elementClass: EuiIconSquare3Stack3dElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconSquare3Stack3dEvents,
    defineCustomElement: defineEuiIconSquare3Stack3d
});
