'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconArrowPathRoundedSquare as EuiIconArrowPathRoundedSquareElement, defineCustomElement as defineEuiIconArrowPathRoundedSquare } from "ensemble-ui/dist/components/eui-icon-arrow-path-rounded-square.js";
import React from 'react';

export type EuiIconArrowPathRoundedSquareEvents = NonNullable<unknown>;

export const EuiIconArrowPathRoundedSquare: StencilReactComponent<EuiIconArrowPathRoundedSquareElement, EuiIconArrowPathRoundedSquareEvents> = /*@__PURE__*/ createComponent<EuiIconArrowPathRoundedSquareElement, EuiIconArrowPathRoundedSquareEvents>({
    tagName: 'eui-icon-arrow-path-rounded-square',
    elementClass: EuiIconArrowPathRoundedSquareElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconArrowPathRoundedSquareEvents,
    defineCustomElement: defineEuiIconArrowPathRoundedSquare
});
