'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { EuiIconPhoneXMark as EuiIconPhoneXMarkElement, defineCustomElement as defineEuiIconPhoneXMark } from "ensemble-ui/dist/components/eui-icon-phone-x-mark.js";
import React from 'react';

export type EuiIconPhoneXMarkEvents = NonNullable<unknown>;

export const EuiIconPhoneXMark: StencilReactComponent<EuiIconPhoneXMarkElement, EuiIconPhoneXMarkEvents> = /*@__PURE__*/ createComponent<EuiIconPhoneXMarkElement, EuiIconPhoneXMarkEvents>({
    tagName: 'eui-icon-phone-x-mark',
    elementClass: EuiIconPhoneXMarkElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as EuiIconPhoneXMarkEvents,
    defineCustomElement: defineEuiIconPhoneXMark
});
